// Interface strings. Vietnamese is the default; English is the toggle.
export const STRINGS = {
  vi: {
    appName: 'Yoga English',
    nav: { poses: 'Tư thế', anatomy: 'Cơ thể', speech: 'Luyện nói', phrases: 'Câu nói' },
    poses: {
      title: 'Tư thế', all: 'Tất cả', vinyasa: 'Vinyasa', ashtanga: 'Ashtanga', yin: 'Yin',
      cues: 'Câu cue', breath: 'Hơi thở', modifications: 'Biến thể và dụng cụ', safety: 'An toàn',
      muscles: 'Cơ tham gia', working: 'Đang làm việc', lengthening: 'Đang kéo dài', joints: 'Khớp',
      minutes: 'phút', ashtangaNote: 'Chuỗi sơ cấp Ashtanga', yinNote: 'Tư thế Yin',
      addToPhrasebook: 'Lưu câu này', saved: 'Đã lưu',
    },
    anatomy: {
      title: 'Cơ thể',
      muscles: 'Cơ', bones: 'Xương và khớp', movements: 'Chuyển động',
      front: 'Mặt trước', back: 'Mặt sau',
      hint: 'Chạm vào một vùng. Nửa bên này của hình là lớp cơ nông, nửa kia là lớp sâu.',
      bonesHint: 'Chạm vào một xương hoặc khớp.',
      showRegions: 'Hiện các vùng', hideRegions: 'Ẩn các vùng',
      search: 'Tìm tiếng Anh hoặc tiếng Việt…',
      index: 'Danh mục',
      technical: 'Tên chuyên môn', plain: 'Cách nói trong lớp',
      does: 'Nó làm gì', feel: 'Bạn cảm thấy ở đâu', inClass: 'Trong lớp',
      works: 'Làm việc trong', stretches: 'Được kéo giãn trong', poses: 'Tư thế liên quan',
      sayRight: 'Nói cho đúng', near: 'Gần đó', under: 'Nằm sâu bên dưới',
      deep: 'cơ sâu', surface: 'cơ nông', latin: 'Tên Latin', pair: 'Ngược lại',
      regions: {
        neck: 'Cổ', 'shoulder-girdle': 'Vai', chest: 'Ngực', back: 'Lưng', arm: 'Tay', trunk: 'Thân',
        hip: 'Hông', thigh: 'Đùi', 'lower-leg': 'Cẳng chân', foot: 'Bàn chân', head: 'Đầu', spine: 'Cột sống',
        pelvis: 'Khung chậu', leg: 'Chân',
      },
      styles: { vinyasa: 'Vinyasa', yin: 'Yin', ashtanga: 'Ashtanga' },
    },
    speech: {
      title: 'Luyện nói',
      intro: 'Viết câu bạn muốn nói trong lớp, bằng tiếng Anh của bạn. Không cần đúng.',
      placeholder: 'Ví dụ: Bend your knee front, the knee not over the toe…',
      contextPlaceholder: 'Tư thế hoặc tình huống (không bắt buộc), ví dụ: Warrior II',
      send: 'Sửa giúp tôi', working: 'Đang nghe câu của bạn…', slowNote: 'Mất khoảng mười giây.',
      natural: 'Giáo viên bản xứ sẽ nói', changes: 'Những gì đã đổi', pronunciation: 'Chú ý phát âm',
      praise: 'Điểm tốt', listen: 'Nghe', save: 'Lưu câu này', again: 'Câu khác',
      dictate: 'Đọc câu', listening: 'Đang nghe…',
      noSpeech: 'Trình duyệt này không nhận giọng nói. Hãy gõ câu vào.',
      error: 'Chưa kết nối được. Thử lại sau một chút.',
      saved: 'Câu đã lưu', savedEmpty: 'Những câu bạn lưu sẽ nằm ở đây.', remove: 'Xoá',
    },
    phrases: { title: 'Câu nói trong lớp', intro: 'Theo từng khoảnh khắc của buổi dạy. Chạm để nghe.' },
    settings: {
      title: 'Cài đặt', language: 'Ngôn ngữ giao diện', support: 'Mức hỗ trợ tiếng Việt',
      supportFull: 'Nhiều', supportBalanced: 'Vừa', supportLight: 'Ít',
      supportHelp: 'Nhiều: tiếng Việt trước. Vừa: tiếng Anh trước. Ít: chạm để xem tiếng Việt.',
      theme: 'Giao diện', light: 'Sáng', dark: 'Tối', auto: 'Theo máy',
      backup: 'Sao lưu', restore: 'Khôi phục',
    },
    common: {
      back: 'Quay lại', play: 'Nghe', playAll: 'Nghe tất cả', stop: 'Dừng', close: 'Đóng',
      suggestFix: 'Góp ý sửa', suggestIntro: 'Thấy gì chưa đúng, nhất là tiếng Việt? Viết vào đây.',
      suggestSend: 'Gửi', suggestThanks: 'Cảm ơn bạn. Đã ghi lại.',
      sanskrit: 'Sanskrit', english: 'Tiếng Anh', vietnamese: 'Tiếng Việt', showVi: 'Xem tiếng Việt', soon: 'Sắp có',
    },
  },
  en: {
    appName: 'Yoga English',
    nav: { poses: 'Poses', anatomy: 'Anatomy', speech: 'Speech', phrases: 'Phrases' },
    poses: {
      title: 'Poses', all: 'All', vinyasa: 'Vinyasa', ashtanga: 'Ashtanga', yin: 'Yin',
      cues: 'Cues', breath: 'Breath', modifications: 'Modifications and props', safety: 'Safety',
      muscles: 'Muscles involved', working: 'Working', lengthening: 'Lengthening', joints: 'Joints',
      minutes: 'minutes', ashtangaNote: 'Ashtanga primary series', yinNote: 'Yin pose',
      addToPhrasebook: 'Save this line', saved: 'Saved',
    },
    anatomy: {
      title: 'Anatomy',
      muscles: 'Muscles', bones: 'Bones and joints', movements: 'Movements',
      front: 'Front', back: 'Back',
      hint: 'Tap a region. One side of the figure shows surface muscles, the other the deep layer.',
      bonesHint: 'Tap a bone or joint.',
      showRegions: 'Show regions', hideRegions: 'Hide regions',
      search: 'Search in English or Vietnamese…',
      index: 'Index',
      technical: 'Technical name', plain: 'Plain teaching phrase',
      does: 'What it does', feel: 'Where you feel it', inClass: 'In class',
      works: 'Works in', stretches: 'Stretches in', poses: 'Related poses',
      sayRight: 'Say it right', near: 'Nearby', under: 'Deep beneath',
      deep: 'deep', surface: 'surface', latin: 'Latin', pair: 'Opposite',
      regions: {
        neck: 'Neck', 'shoulder-girdle': 'Shoulder', chest: 'Chest', back: 'Back', arm: 'Arm', trunk: 'Trunk',
        hip: 'Hip', thigh: 'Thigh', 'lower-leg': 'Lower leg', foot: 'Foot', head: 'Head', spine: 'Spine',
        pelvis: 'Pelvis', leg: 'Leg',
      },
      styles: { vinyasa: 'Vinyasa', yin: 'Yin', ashtanga: 'Ashtanga' },
    },
    speech: {
      title: 'Speech',
      intro: 'Write the cue you want to say in class, in your own English. It does not have to be right.',
      placeholder: 'For example: Bend your knee front, the knee not over the toe…',
      contextPlaceholder: 'Pose or situation (optional), e.g. Warrior II',
      send: 'Coach me', working: 'Listening to your cue…', slowNote: 'This takes about ten seconds.',
      natural: 'A native teacher would say', changes: 'What changed', pronunciation: 'Watch the pronunciation',
      praise: 'What was already good', listen: 'Listen', save: 'Save this line', again: 'Another cue',
      dictate: 'Dictate', listening: 'Listening…',
      noSpeech: 'This browser cannot hear you. Type the cue instead.',
      error: 'Could not reach the coach. Try again in a moment.',
      saved: 'Saved lines', savedEmpty: 'Lines you save will live here.', remove: 'Remove',
    },
    phrases: { title: 'Class talk', intro: 'By moment of the class. Tap to hear.' },
    settings: {
      title: 'Settings', language: 'Interface language', support: 'Vietnamese support',
      supportFull: 'Full', supportBalanced: 'Balanced', supportLight: 'Light',
      supportHelp: 'Full: Vietnamese first. Balanced: English first. Light: tap to see Vietnamese.',
      theme: 'Theme', light: 'Light', dark: 'Dark', auto: 'System',
      backup: 'Backup', restore: 'Restore',
    },
    common: {
      back: 'Back', play: 'Play', playAll: 'Play all', stop: 'Stop', close: 'Close',
      suggestFix: 'Suggest a fix', suggestIntro: 'Something wrong, especially the Vietnamese? Write it here.',
      suggestSend: 'Send', suggestThanks: 'Thank you. Noted.',
      sanskrit: 'Sanskrit', english: 'English', vietnamese: 'Vietnamese', showVi: 'Show Vietnamese', soon: 'Coming soon',
    },
  },
}
