// Interface strings. Vietnamese is the default; English is the toggle.
// Keep these short: they sit on a phone screen.
export const STRINGS = {
  vi: {
    appName: 'Yoga English',
    nav: { home: 'Hôm nay', learn: 'Học', practice: 'Luyện', review: 'Ôn tập', mine: 'Của tôi' },
    home: {
      greeting: 'Chào bạn',
      dueToday: 'Thẻ cần ôn hôm nay',
      noDue: 'Hôm nay không có thẻ nào cần ôn.',
      review: 'Ôn tập',
      beforeClass: 'Trước giờ dạy',
      recent: 'Mở gần đây',
      startHere: 'Bắt đầu từ đây',
      poses: 'Thư viện tư thế',
      body: 'Bản đồ cơ thể',
      coach: 'Luyện câu cue',
      known: 'từ bạn đã biết',
    },
    learn: {
      title: 'Học',
      poses: 'Tư thế',
      posesSub: 'Tên, câu cue, biến thể và cơ tham gia',
      body: 'Cơ thể',
      bodySub: 'Xương, khớp, cơ và chuyển động',
      philosophy: 'Triết lý và thiền',
      philosophySub: 'Sanskrit, Pali và các bài nói ngắn',
      soon: 'Sắp có',
    },
    poses: {
      title: 'Tư thế',
      all: 'Tất cả',
      vinyasa: 'Vinyasa',
      ashtanga: 'Ashtanga',
      yin: 'Yin',
      cues: 'Câu cue',
      breath: 'Hơi thở',
      modifications: 'Biến thể và dụng cụ',
      safety: 'An toàn',
      muscles: 'Cơ tham gia',
      working: 'Đang làm việc',
      lengthening: 'Đang kéo dài',
      hold: 'Giữ',
      minutes: 'phút',
      breaths: 'nhịp thở',
      ashtangaNote: 'Chuỗi sơ cấp Ashtanga',
      yinNote: 'Tư thế Yin',
      sayNames: 'Nghe ba tên gọi',
      transitions: 'Chuyển tiếp sang',
      addToPhrasebook: 'Lưu vào sổ tay',
      saved: 'Đã lưu',
    },
    body: {
      title: 'Bản đồ cơ thể',
      front: 'Mặt trước',
      back: 'Mặt sau',
      tapHint: 'Chạm vào một vùng để nghe và xem',
      technical: 'Từ chuyên môn',
      plain: 'Cách nói trong lớp',
      example: 'Ví dụ câu cue',
      usedIn: 'Dùng trong tư thế',
      bones: 'Xương và khớp',
      musclesTab: 'Cơ',
      say: 'Phát âm',
    },
    practice: {
      title: 'Luyện',
      coach: 'Luyện câu cue',
      coachSub: 'Viết câu cue của bạn, nhận bản tự nhiên và lời giải thích',
      talk: 'Nói chuyện với học viên',
      talkSub: 'Tập trả lời khi học viên hỏi hoặc than đau',
      flow: 'Nghe và tập theo',
      flowSub: 'Giọng bản xứ dẫn cả chuỗi, bạn tập trên thảm',
      builder: 'Soạn giáo án',
      builderSub: 'Chọn tư thế, nhận kịch bản đầy đủ, tập đọc',
    },
    coach: {
      title: 'Luyện câu cue',
      intro: 'Viết câu bạn muốn nói trong lớp, bằng tiếng Anh của bạn. Không cần đúng.',
      placeholder: 'Ví dụ: Bend your knee front, the knee not over the toe…',
      context: 'Tư thế hoặc tình huống (không bắt buộc)',
      contextPlaceholder: 'Ví dụ: Warrior II, lớp Vinyasa',
      send: 'Sửa giúp tôi',
      working: 'Đang nghe câu của bạn…',
      natural: 'Giáo viên bản xứ sẽ nói',
      changes: 'Những gì đã đổi',
      pronunciation: 'Chú ý phát âm',
      praise: 'Điểm tốt',
      listen: 'Nghe',
      save: 'Lưu vào sổ tay',
      again: 'Câu khác',
      dictate: 'Đọc câu',
      listening: 'Đang nghe…',
      noSpeech: 'Trình duyệt này không hỗ trợ nhận giọng nói. Hãy gõ câu vào.',
      error: 'Chưa kết nối được. Thử lại sau một chút.',
      slowNote: 'Mất khoảng mười giây.',
    },
    review: {
      title: 'Ôn tập',
      due: 'cần ôn',
      none: 'Không còn thẻ nào hôm nay. Nghỉ ngơi nhé.',
      reveal: 'Xem đáp án',
      again: 'Chưa nhớ',
      hard: 'Khó',
      good: 'Nhớ',
      easy: 'Dễ',
      sayIt: 'Nói câu này bằng tiếng Anh',
      hearIt: 'Nghe và hiểu',
      namePose: 'Tên tư thế này là gì?',
      done: 'Xong phần ôn hôm nay',
      known: 'từ bạn đã biết',
      next: 'Tiếp',
      startEmpty: 'Thẻ ôn tập sẽ xuất hiện khi bạn mở các tư thế và từ mới.',
    },
    mine: {
      title: 'Của tôi',
      phrasebook: 'Sổ tay',
      phrasebookSub: 'Câu cue và từ bạn đã lưu',
      classes: 'Giáo án đã lưu',
      settings: 'Cài đặt',
      language: 'Ngôn ngữ giao diện',
      support: 'Mức hỗ trợ tiếng Việt',
      supportFull: 'Nhiều',
      supportBalanced: 'Vừa',
      supportLight: 'Ít',
      supportHelp: 'Nhiều: tiếng Việt trước. Vừa: tiếng Anh trước. Ít: chạm để xem tiếng Việt.',
      theme: 'Giao diện',
      light: 'Sáng',
      dark: 'Tối',
      auto: 'Theo máy',
      empty: 'Chưa có gì. Lưu một câu từ Luyện câu cue hoặc một tư thế.',
      remove: 'Xoá',
      suggest: 'Góp ý sửa nội dung',
    },
    common: {
      back: 'Quay lại',
      play: 'Nghe',
      playAll: 'Nghe tất cả',
      stop: 'Dừng',
      close: 'Đóng',
      suggestFix: 'Góp ý sửa',
      suggestIntro: 'Thấy gì chưa đúng, nhất là tiếng Việt? Viết vào đây.',
      suggestSend: 'Gửi',
      suggestThanks: 'Cảm ơn bạn. Đã ghi lại.',
      sanskrit: 'Sanskrit',
      pali: 'Pali',
      english: 'Tiếng Anh',
      vietnamese: 'Tiếng Việt',
      showVi: 'Xem tiếng Việt',
    },
  },
  en: {
    appName: 'Yoga English',
    nav: { home: 'Today', learn: 'Learn', practice: 'Practice', review: 'Review', mine: 'Mine' },
    home: {
      greeting: 'Hello',
      dueToday: 'Cards due today',
      noDue: 'Nothing due today.',
      review: 'Review',
      beforeClass: 'Before class',
      recent: 'Recently opened',
      startHere: 'Start here',
      poses: 'Pose library',
      body: 'Body map',
      coach: 'Cue Coach',
      known: 'words you know',
    },
    learn: {
      title: 'Learn',
      poses: 'Poses',
      posesSub: 'Names, cues, modifications and the muscles involved',
      body: 'Body',
      bodySub: 'Bones, joints, muscles and movements',
      philosophy: 'Philosophy and meditation',
      philosophySub: 'Sanskrit, Pali and short talks',
      soon: 'Coming soon',
    },
    poses: {
      title: 'Poses',
      all: 'All',
      vinyasa: 'Vinyasa',
      ashtanga: 'Ashtanga',
      yin: 'Yin',
      cues: 'Cues',
      breath: 'Breath',
      modifications: 'Modifications and props',
      safety: 'Safety',
      muscles: 'Muscles involved',
      working: 'Working',
      lengthening: 'Lengthening',
      hold: 'Hold',
      minutes: 'minutes',
      breaths: 'breaths',
      ashtangaNote: 'Ashtanga primary series',
      yinNote: 'Yin pose',
      sayNames: 'Hear the three names',
      transitions: 'Moves on to',
      addToPhrasebook: 'Save to phrasebook',
      saved: 'Saved',
    },
    body: {
      title: 'Body map',
      front: 'Front',
      back: 'Back',
      tapHint: 'Tap a region to hear it and read more',
      technical: 'Technical word',
      plain: 'Plain teaching phrase',
      example: 'Example cue',
      usedIn: 'Used in poses',
      bones: 'Bones and joints',
      musclesTab: 'Muscles',
      say: 'Say it',
    },
    practice: {
      title: 'Practice',
      coach: 'Cue Coach',
      coachSub: 'Write your cue, get the natural version and the reasons',
      talk: 'Teacher Talk',
      talkSub: 'Practise answering a student who asks or hurts',
      flow: 'Listen and Flow',
      flowSub: 'A native voice cues a sequence while you follow on the mat',
      builder: 'Class Builder',
      builderSub: 'Pick poses, get a full script, rehearse it',
    },
    coach: {
      title: 'Cue Coach',
      intro: 'Write the cue you want to say in class, in your own English. It does not have to be right.',
      placeholder: 'For example: Bend your knee front, the knee not over the toe…',
      context: 'Pose or situation (optional)',
      contextPlaceholder: 'For example: Warrior II, Vinyasa class',
      send: 'Coach me',
      working: 'Listening to your cue…',
      natural: 'A native teacher would say',
      changes: 'What changed',
      pronunciation: 'Watch the pronunciation',
      praise: 'What was already good',
      listen: 'Listen',
      save: 'Save to phrasebook',
      again: 'Another cue',
      dictate: 'Dictate',
      listening: 'Listening…',
      noSpeech: 'This browser cannot hear you. Type the cue instead.',
      error: 'Could not reach the coach. Try again in a moment.',
      slowNote: 'This takes about ten seconds.',
    },
    review: {
      title: 'Review',
      due: 'due',
      none: 'Nothing left today. Rest.',
      reveal: 'Show the answer',
      again: 'Again',
      hard: 'Hard',
      good: 'Good',
      easy: 'Easy',
      sayIt: 'Say this in English',
      hearIt: 'Listen and understand',
      namePose: 'What is this pose called?',
      done: 'Done for today',
      known: 'words you know',
      next: 'Next',
      startEmpty: 'Review cards appear as you open poses and new words.',
    },
    mine: {
      title: 'Mine',
      phrasebook: 'Phrasebook',
      phrasebookSub: 'Cues and words you have saved',
      classes: 'Saved classes',
      settings: 'Settings',
      language: 'Interface language',
      support: 'Vietnamese support',
      supportFull: 'Full',
      supportBalanced: 'Balanced',
      supportLight: 'Light',
      supportHelp: 'Full: Vietnamese first. Balanced: English first. Light: tap to see Vietnamese.',
      theme: 'Theme',
      light: 'Light',
      dark: 'Dark',
      auto: 'System',
      empty: 'Nothing yet. Save a cue from Cue Coach or a pose.',
      remove: 'Remove',
      suggest: 'Suggest a content fix',
    },
    common: {
      back: 'Back',
      play: 'Play',
      playAll: 'Play all',
      stop: 'Stop',
      close: 'Close',
      suggestFix: 'Suggest a fix',
      suggestIntro: 'Something wrong, especially the Vietnamese? Write it here.',
      suggestSend: 'Send',
      suggestThanks: 'Thank you. Noted.',
      sanskrit: 'Sanskrit',
      pali: 'Pali',
      english: 'English',
      vietnamese: 'Vietnamese',
      showVi: 'Show Vietnamese',
    },
  },
}
