// Interface strings. Vietnamese is the default; English is the toggle.
export const STRINGS = {
  vi: {
    appName: 'Yoga English',
    nav: { poses: 'Tư thế', anatomy: 'Cơ thể', speech: 'Luyện nói', phrases: 'Câu nói' },
    home: {
      morning: 'Chào buổi sáng', afternoon: 'Chào buổi chiều', evening: 'Chào buổi tối',
      lead: 'Một chút trước giờ lên lớp.',
      nextUp: 'Việc tiếp theo', continueLesson: 'Tiếp tục', startLesson: 'Bắt đầu', againLesson: 'Học lại',
      poseToday: 'Tư thế cho lớp hôm nay', openPose: 'Xem tư thế',
      theBody: 'Cơ thể', theBodyLead: 'Chạm vào một vùng để nghe tên và cách nói trong lớp.',
    },
    poses: {
      title: 'Tư thế', all: 'Tất cả', vinyasa: 'Vinyasa', ashtanga: 'Ashtanga', yin: 'Yin',
      cues: 'Câu cue', breath: 'Hơi thở', modifications: 'Biến thể và dụng cụ', safety: 'An toàn',
      muscles: 'Cơ tham gia', working: 'Đang làm việc', lengthening: 'Đang kéo dài', joints: 'Khớp',
      minutes: 'phút', ashtangaNote: 'Chuỗi sơ cấp Ashtanga', yinNote: 'Tư thế Yin',
      addToPhrasebook: 'Lưu câu này', saved: 'Đã lưu',
    },
    anatomy: {
      title: 'Cơ thể',
      muscles: 'Cơ', bones: 'Xương và khớp', movements: 'Chuyển động',
      front: 'Mặt trước', back: 'Mặt sau',
      hint: 'Chạm vào một vùng. Nửa bên này của hình là lớp cơ nông, nửa kia là lớp sâu.',
      bonesHint: 'Chạm vào một xương hoặc khớp.',
      showRegions: 'Hiện các vùng', hideRegions: 'Ẩn các vùng',
      search: 'Tìm tiếng Anh hoặc tiếng Việt…',
      index: 'Danh mục',
      technical: 'Tên chuyên môn', plain: 'Cách nói trong lớp',
      does: 'Nó làm gì', feel: 'Bạn cảm thấy ở đâu', inClass: 'Trong lớp',
      works: 'Làm việc trong', stretches: 'Được kéo giãn trong', poses: 'Tư thế liên quan',
      sayRight: 'Nói cho đúng', near: 'Gần đó', under: 'Nằm sâu bên dưới',
      deep: 'cơ sâu', surface: 'cơ nông', latin: 'Tên Latin', pair: 'Ngược lại',
      regions: {
        neck: 'Cổ', 'shoulder-girdle': 'Vai', chest: 'Ngực', back: 'Lưng', arm: 'Tay', trunk: 'Thân',
        hip: 'Hông', thigh: 'Đùi', 'lower-leg': 'Cẳng chân', foot: 'Bàn chân', head: 'Đầu', spine: 'Cột sống',
        pelvis: 'Khung chậu', leg: 'Chân',
      },
      styles: { vinyasa: 'Vinyasa', yin: 'Yin', ashtanga: 'Ashtanga' },
      kinds: { muscle: 'Cơ', bone: 'Xương', joint: 'Khớp', landmark: 'Mốc xương', movement: 'Chuyển động' },
    },
    speech: {
      title: 'Luyện nói',
      intro: 'Viết câu bạn muốn nói trong lớp, bằng tiếng Anh của bạn. Không cần đúng.',
      placeholder: 'Ví dụ: Bend your knee front, the knee not over the toe…',
      contextPlaceholder: 'Tư thế hoặc tình huống (không bắt buộc), ví dụ: Warrior II',
      send: 'Sửa giúp tôi', working: 'Đang nghe câu của bạn…', slowNote: 'Mất khoảng mười giây.',
      natural: 'Giáo viên bản xứ sẽ nói', changes: 'Những gì đã đổi', pronunciation: 'Chú ý phát âm',
      praise: 'Điểm tốt', listen: 'Nghe', save: 'Lưu câu này', again: 'Câu khác',
      dictate: 'Đọc câu', listening: 'Đang nghe…',
      noSpeech: 'Trình duyệt này không nhận giọng nói. Hãy gõ câu vào.',
      error: 'Chưa kết nối được. Thử lại sau một chút.',
      saved: 'Câu đã lưu', savedEmpty: 'Những câu bạn lưu sẽ nằm ở đây.', remove: 'Xoá',
    },
    phrases: { title: 'Câu nói trong lớp', intro: 'Theo từng khoảnh khắc của buổi dạy. Chạm để nghe.' },
    learn: {
      lessons: 'Bài học theo vùng', lessonsIntro: 'Mỗi bài: gặp từ trên hình, nghe, gắn nhãn, ghép câu cue, rồi nói thử.',
      words: 'từ', minutes: 'phút', done: 'Xong', soon: 'Sắp có', again: 'Học lại', resume: 'Tiếp tục',
      start: 'Bắt đầu', next: 'Tiếp', back: 'Lùi', check: 'Kiểm tra', finish: 'Xong', close: 'Đóng', slide: 'Trang',
      youWillMeet: 'Bạn sẽ gặp', how: 'Cách học',
      technical: 'Tên chuyên môn', plain: 'Trong lớp nói', feel: 'Học viên cảm thấy', inClass: 'Giáo viên bản xứ nói', care: 'Khi học viên đau',
      tapFigure: 'Chạm vào hình để nghe từ', latin: 'Latin',
      correct: 'Chính xác', notQuite: 'Chưa đúng', allRight: 'Đúng hết.',
      labelTap: 'Chạm một tên, rồi chạm vào ô của nó.', labelNext: 'Giờ chạm vào ô đúng.', labelPlaced: 'Đã đặt hết. Kiểm tra nhé.',
      labelWrong: 'Ô màu đất giờ hiện tên đúng. Chạm vào ô để nghe lại.',
      sortTap: 'Chạm một thẻ, rồi chạm vào nhóm.', sortDrop: 'Chạm để đặt', sortPlaced: 'Đã đặt hết',
      orderUp: 'Lên', orderDown: 'Xuống', orderShouldBe: 'phải là số', listenAll: 'Nghe cả chuỗi',
      hotspotTap: 'Chạm vào hình', hotspotAgain: 'Chưa phải chỗ đó. Thử lại, còn một lần.', replay: 'Nghe lại',
      reveal: 'Xem đáp án', thenSay: 'Câu bạn nói',
      chainTap: 'Chạm từng mảnh theo đúng thứ tự. Chạm vào mảnh đã đặt để bỏ ra.', chainRight: 'Câu đúng', listenCue: 'Nghe câu',
      dictationHint: 'Nghe bao nhiêu lần cũng được. Gõ câu bạn nghe.', dictationPlaceholder: 'Gõ câu bạn nghe…',
      dictationClose: 'Gần rồi. Những từ còn thiếu được đánh dấu. Nghe lại và sửa.', showAnswer: 'Hiện câu đúng', target: 'Câu đúng', typed: 'Bạn gõ',
      record: 'Ghi âm', stop: 'Dừng', recording: 'Đang ghi…', checking: 'Đang nghe bạn…', model: 'Nghe mẫu', heard: 'Gemini nghe thấy',
      good: 'Tốt', almost: 'Gần được', tryAgain: 'Thử lại', skip: 'Để sau', nextWord: 'Từ tiếp', noMic: 'Không mở được micro trên trình duyệt này.',
      sayError: 'Chưa gửi được bản ghi. Thử lại sau một chút.', wordOf: 'Từ', of: 'trên',
      issues: { final: 'âm cuối', cluster: 'cụm phụ âm', th: 'âm th', stress: 'trọng âm', vowel: 'nguyên âm', other: 'khác' },
      doneTitle: 'Xong.', doneLead: 'Bạn đã gặp tất cả các từ của bài này.', known: 'đã biết',
      facets: { labelled: 'gắn nhãn', said: 'nói', cued: 'dùng trong câu cue' },
      nextLesson: 'Bài tiếp theo', toAnatomy: 'Về Cơ thể', toPose: 'Xem tư thế', seePose: 'Xem tư thế đầy đủ',
      lengthening: 'Cơ đang được kéo giãn', working: 'Cơ đang làm việc', safety: 'An toàn', breath: 'Hơi thở',
      kinds: { label: 'Gắn nhãn', sort: 'Phân loại', order: 'Sắp xếp', hotspot: 'Chạm vào hình', predict: 'Dự đoán', chain: 'Ghép câu', dictation: 'Nghe và gõ', sayit: 'Nói thử' },
      pose: 'Tư thế', activity: 'Luyện tập', lessonDone: 'Đã học xong', lessonStarted: 'Đang học',
    },
    settings: {
      title: 'Cài đặt', language: 'Ngôn ngữ giao diện', support: 'Mức hỗ trợ tiếng Việt',
      supportFull: 'Nhiều', supportBalanced: 'Vừa', supportLight: 'Ít',
      supportHelp: 'Nhiều: tiếng Việt trước. Vừa: tiếng Anh trước. Ít: chạm để xem tiếng Việt.',
      theme: 'Giao diện', light: 'Sáng', dark: 'Tối', auto: 'Theo máy',
      backup: 'Sao lưu', restore: 'Khôi phục',
    },
    common: {
      back: 'Quay lại', play: 'Nghe', playAll: 'Nghe tất cả', stop: 'Dừng', close: 'Đóng',
      suggestFix: 'Góp ý sửa', suggestIntro: 'Thấy gì chưa đúng, nhất là tiếng Việt? Viết vào đây.',
      suggestSend: 'Gửi', suggestThanks: 'Cảm ơn bạn. Đã ghi lại.',
      sanskrit: 'Sanskrit', english: 'Tiếng Anh', vietnamese: 'Tiếng Việt', showVi: 'Xem tiếng Việt', soon: 'Sắp có',
    },
  },
  en: {
    appName: 'Yoga English',
    nav: { poses: 'Poses', anatomy: 'Anatomy', speech: 'Speech', phrases: 'Phrases' },
    home: {
      morning: 'Good morning', afternoon: 'Good afternoon', evening: 'Good evening',
      lead: 'A few minutes before class.',
      nextUp: 'Up next', continueLesson: 'Continue', startLesson: 'Begin', againLesson: 'Learn it again',
      poseToday: 'A pose for today’s class', openPose: 'Open the pose',
      theBody: 'The body', theBodyLead: 'Tap a region to hear its name and how to say it in class.',
    },
    poses: {
      title: 'Poses', all: 'All', vinyasa: 'Vinyasa', ashtanga: 'Ashtanga', yin: 'Yin',
      cues: 'Cues', breath: 'Breath', modifications: 'Modifications and props', safety: 'Safety',
      muscles: 'Muscles involved', working: 'Working', lengthening: 'Lengthening', joints: 'Joints',
      minutes: 'minutes', ashtangaNote: 'Ashtanga primary series', yinNote: 'Yin pose',
      addToPhrasebook: 'Save this line', saved: 'Saved',
    },
    anatomy: {
      title: 'Anatomy',
      muscles: 'Muscles', bones: 'Bones and joints', movements: 'Movements',
      front: 'Front', back: 'Back',
      hint: 'Tap a region. One side of the figure shows surface muscles, the other the deep layer.',
      bonesHint: 'Tap a bone or joint.',
      showRegions: 'Show regions', hideRegions: 'Hide regions',
      search: 'Search in English or Vietnamese…',
      index: 'Index',
      technical: 'Technical name', plain: 'Plain teaching phrase',
      does: 'What it does', feel: 'Where you feel it', inClass: 'In class',
      works: 'Works in', stretches: 'Stretches in', poses: 'Related poses',
      sayRight: 'Say it right', near: 'Nearby', under: 'Deep beneath',
      deep: 'deep', surface: 'surface', latin: 'Latin', pair: 'Opposite',
      regions: {
        neck: 'Neck', 'shoulder-girdle': 'Shoulder', chest: 'Chest', back: 'Back', arm: 'Arm', trunk: 'Trunk',
        hip: 'Hip', thigh: 'Thigh', 'lower-leg': 'Lower leg', foot: 'Foot', head: 'Head', spine: 'Spine',
        pelvis: 'Pelvis', leg: 'Leg',
      },
      styles: { vinyasa: 'Vinyasa', yin: 'Yin', ashtanga: 'Ashtanga' },
      kinds: { muscle: 'Muscle', bone: 'Bone', joint: 'Joint', landmark: 'Landmark', movement: 'Movement' },
    },
    speech: {
      title: 'Speech',
      intro: 'Write the cue you want to say in class, in your own English. It does not have to be right.',
      placeholder: 'For example: Bend your knee front, the knee not over the toe…',
      contextPlaceholder: 'Pose or situation (optional), e.g. Warrior II',
      send: 'Coach me', working: 'Listening to your cue…', slowNote: 'This takes about ten seconds.',
      natural: 'A native teacher would say', changes: 'What changed', pronunciation: 'Watch the pronunciation',
      praise: 'What was already good', listen: 'Listen', save: 'Save this line', again: 'Another cue',
      dictate: 'Dictate', listening: 'Listening…',
      noSpeech: 'This browser cannot hear you. Type the cue instead.',
      error: 'Could not reach the coach. Try again in a moment.',
      saved: 'Saved lines', savedEmpty: 'Lines you save will live here.', remove: 'Remove',
    },
    phrases: { title: 'Class talk', intro: 'By moment of the class. Tap to hear.' },
    learn: {
      lessons: 'Lessons by region', lessonsIntro: 'Each lesson: meet the words on the figure, hear them, label them, build cues, then say them.',
      words: 'words', minutes: 'min', done: 'Done', soon: 'Soon', again: 'Learn again', resume: 'Continue',
      start: 'Begin', next: 'Next', back: 'Back', check: 'Check', finish: 'Done', close: 'Close', slide: 'Slide',
      youWillMeet: 'You will meet', how: 'How it works',
      technical: 'Technical name', plain: 'In class', feel: 'Students feel', inClass: 'A native teacher says', care: 'When a student hurts',
      tapFigure: 'Tap the figure to hear the word', latin: 'Latin',
      correct: 'Correct', notQuite: 'Not quite', allRight: 'Every box right.',
      labelTap: 'Tap a name, then tap its box.', labelNext: 'Now tap the right box.', labelPlaced: 'All placed. Check when ready.',
      labelWrong: 'The clay boxes now show the right name. Tap a box to hear it again.',
      sortTap: 'Tap a card, then tap its group.', sortDrop: 'Tap to place', sortPlaced: 'All placed',
      orderUp: 'Up', orderDown: 'Down', orderShouldBe: 'should be', listenAll: 'Hear the whole sequence',
      hotspotTap: 'Tap the figure', hotspotAgain: 'Not there. One more try.', replay: 'Play again',
      reveal: 'Reveal', thenSay: 'What you say',
      chainTap: 'Tap the pieces in order. Tap a placed piece to take it back.', chainRight: 'The cue', listenCue: 'Hear the cue',
      dictationHint: 'Listen as many times as you like. Type what you hear.', dictationPlaceholder: 'Type the cue…',
      dictationClose: 'Close. The missing words are marked. Listen again and fix them.', showAnswer: 'Show the cue', target: 'The cue', typed: 'You typed',
      record: 'Record', stop: 'Stop', recording: 'Recording…', checking: 'Listening to you…', model: 'Hear the model', heard: 'Gemini heard',
      good: 'Good', almost: 'Almost', tryAgain: 'Try again', skip: 'Later', nextWord: 'Next word', noMic: 'This browser cannot open the microphone.',
      sayError: 'Could not send the recording. Try again in a moment.', wordOf: 'Word', of: 'of',
      issues: { final: 'final sound', cluster: 'consonant cluster', th: 'th', stress: 'stress', vowel: 'vowel', other: 'other' },
      doneTitle: 'Done.', doneLead: 'You have met every word in this lesson.', known: 'known',
      facets: { labelled: 'labelled', said: 'said', cued: 'used in a cue' },
      nextLesson: 'Next lesson', toAnatomy: 'Back to Anatomy', toPose: 'See the pose', seePose: 'See the full pose',
      lengthening: 'Muscles stretching', working: 'Muscles working', safety: 'Safety', breath: 'Breath',
      kinds: { label: 'Label it', sort: 'Sort', order: 'Put in order', hotspot: 'Tap the figure', predict: 'Predict', chain: 'Build the cue', dictation: 'Listen and type', sayit: 'Say it' },
      pose: 'Pose', activity: 'Practice', lessonDone: 'Done', lessonStarted: 'In progress',
    },
    settings: {
      title: 'Settings', language: 'Interface language', support: 'Vietnamese support',
      supportFull: 'Full', supportBalanced: 'Balanced', supportLight: 'Light',
      supportHelp: 'Full: Vietnamese first. Balanced: English first. Light: tap to see Vietnamese.',
      theme: 'Theme', light: 'Light', dark: 'Dark', auto: 'System',
      backup: 'Backup', restore: 'Restore',
    },
    common: {
      back: 'Back', play: 'Play', playAll: 'Play all', stop: 'Stop', close: 'Close',
      suggestFix: 'Suggest a fix', suggestIntro: 'Something wrong, especially the Vietnamese? Write it here.',
      suggestSend: 'Send', suggestThanks: 'Thank you. Noted.',
      sanskrit: 'Sanskrit', english: 'English', vietnamese: 'Vietnamese', showVi: 'Show Vietnamese', soon: 'Coming soon',
    },
  },
}
