"""Assemble research/comparison.html from the manifests, transcripts and
coach outputs. Re-run after regenerating anything."""
import html
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from samples import SAMPLES
from coach_prompt import CUES

HERE = os.path.dirname(__file__)
TTS = os.path.join(HERE, "tts")
COACH = os.path.join(HERE, "coach")


def load(path, default):
    if not os.path.exists(path):
        return default
    with open(path, encoding="utf-8") as f:
        return json.load(f)


edge = load(os.path.join(TTS, "manifest_edge.json"), [])
gem = load(os.path.join(TTS, "manifest_gemini.json"), [])
transcripts = load(os.path.join(TTS, "transcripts.json"), {})

# Vietnamese edge voices were generated by a retry outside the manifest.
for vid, voice in [("edge-hoaimy", "vi-VN-HoaiMyNeural"), ("edge-namminh", "vi-VN-NamMinhNeural")]:
    fn = f"{vid}__vietnamese.mp3"
    if os.path.exists(os.path.join(TTS, fn)) and not any(m["file"] == fn for m in edge):
        edge.append({"provider": vid, "voice": voice, "sample": "vietnamese", "file": fn, "ok": True})

PROVIDERS = [
    # id, display, cost badge, note
    ("edge-aria", "edge-tts · Aria (US)", "free", "The Dashboard's current voice. No style control."),
    ("edge-ava", "edge-tts · Ava Multilingual (US)", "free", "Newer Microsoft voice; can also attempt Vietnamese."),
    ("edge-andrew", "edge-tts · Andrew Multilingual (US, male)", "free", "Newer Microsoft voice; can also attempt Vietnamese."),
    ("edge-sonia", "edge-tts · Sonia (UK)", "free", "British, calm register."),
    ("edge-hoaimy", "edge-tts · Hoài My (vi-VN)", "free", "Microsoft's Vietnamese female voice."),
    ("edge-namminh", "edge-tts · Nam Minh (vi-VN, male)", "free", "Microsoft's Vietnamese male voice."),
    ("gem38-sulafat", "Gemini 3.8 Flash TTS · Sulafat (warm)", "paid", "Style-directed. $9 per 1M audio tokens."),
    ("gem38-achernar", "Gemini 3.8 Flash TTS · Achernar (soft)", "paid", "Style-directed. $9 per 1M audio tokens."),
    ("gem38-charon", "Gemini 3.8 Flash TTS · Charon (male)", "paid", "Style-directed. $9 per 1M audio tokens."),
    ("gem38lite-sulafat", "Gemini 3.8 Flash-Lite TTS · Sulafat", "paid", "Cheaper tier. $6 per 1M audio tokens."),
    ("gem25pro-sulafat", "Gemini 2.5 Pro TTS (preview) · Sulafat", "paid", "Older model, prompt-directed. For reference."),
]

ALL = edge + gem
by_key = {(m["provider"], m["sample"]): m for m in ALL if m.get("ok")}


def norm(s):
    s = s.lower()
    s = s.replace(" ii", " two").replace(" 2", " two")
    s = re.sub(r"[^\w\sàáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđ]", " ", s)
    return re.sub(r"\s+", " ", s).strip()


def check(sample, fn):
    t = transcripts.get(fn, {}).get("transcript", "")
    if not t:
        return ("", "not checked")
    a, b = norm(sample["text"]).replace(" ", ""), norm(t).replace(" ", "")
    if a == b:
        return ("ok", "says exactly the sample text")
    # tolerate the transcriber truncating or re-punctuating
    if b in a or a.startswith(b[: max(10, len(b) - 5)]):
        return ("ok", "matches (transcriber cut short)")
    if any(w in b for w in ["you are a", "speak ", "say exactly"]):
        return ("bad", "read the style prompt aloud")
    return ("warn", f"transcribed as: {t}")


def seconds(fn):
    s = transcripts.get(fn, {}).get("seconds")
    return f"{s:.0f}s" if s else ""


def esc(s):
    return html.escape(str(s), quote=True)


# ---------- TTS section ----------
tts_rows = []
for s in SAMPLES:
    cards = []
    for pid, label, badge, note in PROVIDERS:
        m = by_key.get((pid, s["id"]))
        if not m:
            continue
        status, msg = check(s, m["file"])
        cards.append(f"""
        <div class="voice">
          <div class="voice-head">
            <span class="voice-name">{esc(label)}</span>
            <span class="badge {badge}">{'free' if badge == 'free' else 'Gemini key'}</span>
          </div>
          <audio controls preload="metadata" src="tts/{esc(m['file'])}"></audio>
          <div class="voice-meta">
            <span class="dur">{seconds(m['file'])}</span>
            <span class="chk {status}" title="{esc(msg)}">{'✓' if status == 'ok' else '!' if status else '·'} {esc(msg)}</span>
          </div>
        </div>""")
    tts_rows.append(f"""
    <section class="sample">
      <h3>{esc(s['label'])}</h3>
      <p class="text">“{esc(s['text'])}”</p>
      <p class="style"><span>Direction given to Gemini:</span> {esc(s['style'])}</p>
      <div class="voices">{''.join(cards)}</div>
    </section>""")

# ---------- Coach section ----------
COACH_MODELS = [
    ("gemini-3.8-flash", "Gemini 3.8 Flash", "$0.75 in / $3.75 out per 1M · thinks before answering"),
    ("gemini-3.6-flash", "Gemini 3.6 Flash", "same price as 3.8 · the model the Y8 backend uses"),
    ("gemini-3.5-flash-lite", "Gemini 3.5 Flash-Lite", "$0.30 in / $2.50 out per 1M · no thinking, 3s"),
]
REF_MODELS = [
    ("claude-sonnet-5-5", "Claude Sonnet 5.5 (reference only)"),
    ("claude-opus-5-5", "Claude Opus 5.5 (reference only)"),
]


def coach_card(title, sub, rec):
    res = rec.get("result") if isinstance(rec, dict) else rec
    if not res:
        return f'<div class="model"><h4>{esc(title)}</h4><p class="err">{esc(rec.get("error", "no result"))}</p></div>'
    changes = "".join(
        f'<li><span class="from">{esc(c["from"])}</span> <span class="arr">→</span> <span class="to">{esc(c["to"])}</span><div class="vi">{esc(c["why_vi"])}</div></li>'
        for c in res.get("changes", []))
    pron = "".join(
        f'<li><b>{esc(p["word"])}</b><div class="vi">{esc(p["tip_vi"])}</div></li>' for p in res.get("pronunciation", []))
    meta = ""
    if isinstance(rec, dict) and rec.get("usage"):
        u = rec["usage"]
        tok_in = u.get("promptTokenCount", 0)
        tok_out = u.get("candidatesTokenCount", 0) + u.get("thoughtsTokenCount", 0)
        meta = f'<div class="meta">{rec.get("seconds", "?")}s · {tok_in} tokens in, {tok_out} out (incl. thinking)</div>'
    return f"""
    <div class="model">
      <h4>{esc(title)}<small>{esc(sub)}</small></h4>
      <p class="natural">“{esc(res['natural'])}”</p>
      <ul class="changes">{changes}</ul>
      <div class="pron-h">Pronunciation</div>
      <ul class="pron">{pron}</ul>
      <p class="praise">{esc(res.get('praise_vi', ''))}</p>
      {meta}
    </div>"""


coach_blocks = []
gem_results = {m: {r["cue"]: r for r in load(os.path.join(COACH, f"{m}.json"), [])} for m, _, _ in COACH_MODELS}
ref_results = {m: {r["id"]: r for r in load(os.path.join(COACH, f"{m}.json"), [])} for m, _ in REF_MODELS}
for c in CUES:
    cards = "".join(coach_card(label, sub, gem_results[m].get(c["id"], {})) for m, label, sub in COACH_MODELS)
    refs = "".join(coach_card(label, "not an option: no Claude API", ref_results[m].get(c["id"], {})) for m, label in REF_MODELS)
    coach_blocks.append(f"""
    <section class="cue">
      <h3>{esc(c['context'])}</h3>
      <p class="orig"><span>Her cue:</span> “{esc(c['cue'])}”</p>
      <div class="models">{cards}</div>
      <details><summary>Reference: what Claude produced for the same cue (ruled out, Gemini only)</summary><div class="models">{refs}</div></details>
    </section>""")

page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Yoga English · voice and coach tests</title>
<style>
  :root {{
    --bg: #f6f3ee; --card: #ffffff; --ink: #2b2a27; --muted: #6f6a62; --line: #e6e0d6;
    --sage: #6f8f7a; --sage-soft: #e4ece6; --clay: #b9704f; --clay-soft: #f3e3da; --gold-soft: #f4ecd8;
  }}
  * {{ box-sizing: border-box; }}
  body {{ margin: 0; background: var(--bg); color: var(--ink); font: 16px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }}
  main {{ max-width: 1100px; margin: 0 auto; padding: 24px 16px 80px; }}
  header h1 {{ font-weight: 500; font-size: 28px; margin: 0 0 4px; letter-spacing: -0.01em; }}
  header p {{ color: var(--muted); margin: 0; }}
  h2 {{ font-weight: 500; font-size: 22px; margin: 48px 0 8px; }}
  h3 {{ font-weight: 500; font-size: 18px; margin: 0 0 6px; }}
  .lead {{ color: var(--muted); margin: 0 0 20px; max-width: 70ch; }}
  .note {{ background: var(--gold-soft); border-radius: 12px; padding: 12px 16px; margin: 16px 0; max-width: 80ch; }}
  .sample, .cue {{ background: var(--card); border: 1px solid var(--line); border-radius: 16px; padding: 18px; margin: 14px 0; }}
  .text {{ font-size: 18px; margin: 0 0 4px; }}
  .style {{ color: var(--muted); font-size: 14px; margin: 0 0 14px; }}
  .style span {{ color: var(--sage); }}
  .voices {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 10px; }}
  .voice {{ border: 1px solid var(--line); border-radius: 12px; padding: 10px 12px; background: #fcfbf9; }}
  .voice-head {{ display: flex; justify-content: space-between; align-items: baseline; gap: 8px; margin-bottom: 6px; }}
  .voice-name {{ font-size: 14px; }}
  .badge {{ font-size: 11px; padding: 2px 8px; border-radius: 999px; white-space: nowrap; }}
  .badge.free {{ background: var(--sage-soft); color: #3f5e4b; }}
  .badge.paid {{ background: var(--clay-soft); color: #7d4a32; }}
  audio {{ width: 100%; height: 36px; }}
  .voice-meta {{ display: flex; gap: 10px; font-size: 12px; color: var(--muted); margin-top: 4px; align-items: baseline; }}
  .dur {{ min-width: 2.5em; }}
  .chk.ok {{ color: #3f5e4b; }} .chk.bad {{ color: #a33; }} .chk.warn {{ color: #8a6d1f; }}
  table {{ border-collapse: collapse; width: 100%; background: var(--card); border-radius: 12px; overflow: hidden; font-size: 15px; }}
  th, td {{ text-align: left; padding: 10px 12px; border-bottom: 1px solid var(--line); vertical-align: top; }}
  th {{ font-weight: 500; color: var(--muted); font-size: 13px; }}
  td.num {{ font-variant-numeric: tabular-nums; white-space: nowrap; }}
  .orig {{ font-size: 17px; margin: 0 0 14px; }}
  .orig span {{ color: var(--clay); font-size: 14px; display: block; }}
  .models {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 12px; }}
  .model {{ border: 1px solid var(--line); border-radius: 12px; padding: 12px 14px; background: #fcfbf9; }}
  .model h4 {{ margin: 0 0 8px; font-weight: 500; font-size: 15px; }}
  .model h4 small {{ display: block; color: var(--muted); font-weight: 400; font-size: 12px; }}
  .natural {{ font-size: 16px; margin: 0 0 10px; }}
  ul {{ padding-left: 0; list-style: none; margin: 0; }}
  .changes li {{ margin: 0 0 8px; font-size: 14px; }}
  .from {{ text-decoration: line-through; color: var(--muted); }}
  .arr {{ color: var(--sage); }}
  .vi {{ color: #4a4640; font-size: 13.5px; margin-top: 2px; }}
  .pron-h {{ font-size: 12px; color: var(--muted); margin: 10px 0 4px; text-transform: uppercase; letter-spacing: 0.06em; }}
  .pron li {{ font-size: 14px; margin-bottom: 6px; }}
  .praise {{ font-size: 13.5px; color: #3f5e4b; background: var(--sage-soft); border-radius: 8px; padding: 6px 10px; margin: 10px 0 0; }}
  .meta {{ font-size: 12px; color: var(--muted); margin-top: 8px; }}
  details {{ margin-top: 12px; }}
  summary {{ cursor: pointer; color: var(--muted); font-size: 14px; }}
  details .models {{ margin-top: 12px; }}
  .err {{ color: #a33; font-size: 14px; }}
  @media (max-width: 600px) {{ .voices, .models {{ grid-template-columns: 1fr; }} }}
</style>
</head>
<body>
<main>
<header>
  <h1>Yoga English · voice and coaching tests</h1>
  <p>6 October 2026 · Every voice reads the same five sentences. Every model receives the same three cues and the same prompt.</p>
</header>

<h2>1. Text-to-speech</h2>
<p class="lead">Only free voices and Gemini voices were tested, following your rule. ElevenLabs, OpenAI and Azure were ruled out on cost before testing. Each clip was transcribed back by Gemini to confirm it says the sample text and nothing else.</p>
<div class="note">The first Gemini 3.8 run <b>read my style instructions aloud</b> (“You are a calm, warm yoga teacher…”), because 3.8 moved to a new request format where the text is a verbatim transcript and the direction goes in a separate style field. The clips below are from the corrected run. The older 2.5 model takes the direction inside the prompt and worked first time.</div>
{''.join(tts_rows)}

<h3 style="margin-top:28px">What it would cost</h3>
<p class="lead">Assumes the full content set is about 2,000 fixed clips averaging 8 seconds (4.4 hours of audio), generated once, plus the Cue Coach speaking about 20 corrected cues a day. Gemini bills audio at 25 tokens per second. Prices are the standard tier through 31 December 2026; <b>Google has announced they double on 1 January 2027</b>, so fixed content should be generated this year. Every Gemini model here also has a free-of-charge tier with rate limits, so light live use may cost nothing.</p>
<table>
  <tr><th>Voice</th><th>Price</th><th>All fixed content, once</th><th>Live Cue Coach, per month</th><th>Notes</th></tr>
  <tr><td>edge-tts (Microsoft, unofficial)</td><td>free</td><td class="num">$0</td><td class="num">$0</td><td>No account. Unofficial endpoint, so it could break; fixed content is safe once generated. Cannot run live from the phone without a small server.</td></tr>
  <tr><td>Gemini 3.8 Flash TTS</td><td>$9 / 1M audio tokens</td><td class="num">about $3.60</td><td class="num">about $1.40</td><td>Style-directed. 30 voices. Vietnamese supported.</td></tr>
  <tr><td>Gemini 3.8 Flash-Lite TTS</td><td>$6 / 1M audio tokens</td><td class="num">about $2.40</td><td class="num">about $0.90</td><td>Same API, cheaper tier.</td></tr>
  <tr><td>Gemini 2.5 Pro TTS (preview)</td><td>$20 / 1M audio tokens</td><td class="num">about $8</td><td class="num">about $3</td><td>Older; preview models get retired.</td></tr>
  <tr><td colspan="5" style="color:var(--muted);font-size:13px">Ruled out by the free rule, listed for completeness: ElevenLabs $50 to $100 per 1M characters (about $20 to $40 for the fixed content); OpenAI gpt-4o-mini-tts about $0.015 per minute (about $4); Google Cloud Chirp 3 HD $30 per 1M characters (about $12) and needs a Google Cloud project; Azure Neural HD $22 per 1M characters (about $9) and needs an Azure account.</td></tr>
</table>

<h2>2. Cue Coach</h2>
<p class="lead">Three cues written the way an intermediate Vietnamese speaker might write them. Each model was asked for the natural teacher version, two to four changes explained in Vietnamese, up to three pronunciation warnings, and one honest line of praise. Gemini 3.8 Flash and 3.6 Flash think before answering (slower, costs more output tokens); Flash-Lite answers in about three seconds.</p>
{''.join(coach_blocks)}

<h3 style="margin-top:28px">Cost of the Cue Coach</h3>
<table>
  <tr><th>Model</th><th>Per corrected cue</th><th>20 cues a day, per month</th><th>Latency measured</th></tr>
  <tr><td>Gemini 3.8 Flash</td><td class="num">about $0.007</td><td class="num">about $4</td><td class="num">15 to 20 s</td></tr>
  <tr><td>Gemini 3.6 Flash</td><td class="num">about $0.007</td><td class="num">about $4</td><td class="num">11 s</td></tr>
  <tr><td>Gemini 3.5 Flash-Lite</td><td class="num">about $0.001</td><td class="num">about $0.70</td><td class="num">3 s</td></tr>
</table>
<p class="lead" style="margin-top:12px">Twenty cues a day is a heavy estimate; a few a day is more likely, and the free tier may cover it entirely.</p>
</main>
</body>
</html>
"""

out = os.path.join(HERE, "comparison.html")
with open(out, "w", encoding="utf-8") as f:
    f.write(page)
print("wrote", out, len(page), "bytes")
