/**
 * Movement and direction language: the verbs and position words that carry a
 * cue. This is where Vietnamese speakers' cues most often go wrong, so each
 * has an example in a real cue. Only the ones the three slice poses use.
 */
export const MOVEMENT = [
  { id: 'root-down', domain: 'movement', group: 'verb', en: 'root down', vi: 'bám rễ xuống, ấn chắc xuống', say: 'ROOT DOWN', traps: ['final-t', 'final-n'],
    example: { en: 'Root down through the outer edge of your back foot.', vi: 'Ấn chắc xuống qua cạnh ngoài của bàn chân sau.' } },
  { id: 'lengthen', domain: 'movement', group: 'verb', en: 'lengthen', vi: 'kéo dài', say: 'LENG-then', traps: ['th', 'final-n'],
    example: { en: 'Lengthen through the crown of your head.', vi: 'Kéo dài lên qua đỉnh đầu.' } },
  { id: 'draw-in', domain: 'movement', group: 'verb', en: 'draw in', vi: 'hóp vào, kéo vào', say: 'DRAW IN', traps: ['cluster-dr'],
    example: { en: 'Draw your belly in gently.', vi: 'Hóp nhẹ bụng vào.' } },
  { id: 'soften', domain: 'movement', group: 'verb', en: 'soften', vi: 'thả lỏng, làm mềm', say: 'SOF-en', traps: ['silent-t', 'final-n'],
    example: { en: 'Soften your jaw and the space between your eyebrows.', vi: 'Thả lỏng hàm và khoảng giữa hai lông mày.' } },
  { id: 'stack', domain: 'movement', group: 'verb', en: 'stack', vi: 'xếp thẳng hàng, đặt thẳng trên', say: 'STAK', traps: ['cluster-st', 'final-k'],
    example: { en: 'Stack your knee over your ankle.', vi: 'Đặt gối thẳng trên cổ chân.' } },
  { id: 'press', domain: 'movement', group: 'verb', en: 'press', vi: 'ấn', say: 'PRES', traps: ['cluster-pr', 'final-s'],
    example: { en: 'Press down through your knuckles.', vi: 'Ấn xuống qua các khớp ngón tay.' } },
  { id: 'reach', domain: 'movement', group: 'verb', en: 'reach', vi: 'vươn', say: 'REECH', traps: ['long-ee', 'final-ch'],
    example: { en: 'Reach your arms out wide.', vi: 'Vươn hai tay sang hai bên.' } },
  { id: 'fold', domain: 'movement', group: 'verb', en: 'fold', vi: 'gập người', say: 'FOHLD', traps: ['cluster-ld'],
    example: { en: 'Fold forward slowly.', vi: 'Từ từ gập người về phía trước.' } },
  { id: 'release', domain: 'movement', group: 'verb', en: 'release', vi: 'thả, buông', say: 'ri-LEES', traps: ['stress', 'final-s'],
    example: { en: 'Release your head and let it hang heavy.', vi: 'Thả đầu xuống, để đầu buông nặng.' } },
  { id: 'gaze', domain: 'movement', group: 'verb', en: 'gaze', vi: 'hướng mắt nhìn', say: 'GAYZ', traps: ['final-z'],
    example: { en: 'Gaze softly over your front fingertips.', vi: 'Nhìn nhẹ nhàng qua đầu ngón tay trước.' } },
  { id: 'tuck', domain: 'movement', group: 'verb', en: 'tuck', vi: 'cuộn, bấm (ngón chân)', say: 'TUK', traps: ['final-k'],
    example: { en: 'Tuck your toes and lift your hips.', vi: 'Bấm các ngón chân xuống và nâng hông lên.' } },
  { id: 'rotate', domain: 'movement', group: 'verb', en: 'rotate', vi: 'xoay', say: 'ROH-tayt', traps: ['stress', 'final-t'],
    example: { en: 'Rotate your upper arms outward.', vi: 'Xoay bắp tay ra ngoài.' } },
  { id: 'find-your-edge', domain: 'movement', group: 'phrase', en: 'find your edge', vi: 'tìm ngưỡng của bạn', say: 'FYND yor EJ', traps: ['cluster-nd', 'final-j'],
    example: { en: 'Find your edge: enough to feel it, not so much that you tense against it.', vi: 'Tìm ngưỡng của bạn: đủ để cảm nhận, nhưng không căng cứng chống lại nó.' } },
  { id: 'toward', domain: 'movement', group: 'direction', en: 'toward', vi: 'về phía', say: 'tuh-WORD', traps: ['stress', 'final-d'],
    example: { en: 'Reach your heels toward the floor.', vi: 'Hướng gót chân về phía sàn.' } },
  { id: 'away-from', domain: 'movement', group: 'direction', en: 'away from', vi: 'ra xa khỏi', say: 'uh-WAY from', traps: ['stress'],
    example: { en: 'Relax your shoulders away from your ears.', vi: 'Thả vai ra xa khỏi tai.' } },
  { id: 'in-line-with', domain: 'movement', group: 'direction', en: 'in line with', vi: 'thẳng hàng với', say: 'in LYN with', traps: ['th', 'final-n'],
    example: { en: 'Keep your front heel in line with the arch of your back foot.', vi: 'Giữ gót chân trước thẳng hàng với lòng bàn chân sau.' } },
  { id: 'over', domain: 'movement', group: 'direction', en: 'over', vi: 'ngay trên', say: 'OH-ver', traps: ['stress'],
    example: { en: 'Bring your shoulders over your wrists.', vi: 'Đưa vai thẳng trên cổ tay.' } },
  { id: 'parallel-to', domain: 'movement', group: 'direction', en: 'parallel to', vi: 'song song với', say: 'PAR-uh-lel to', traps: ['stress'],
    example: { en: 'Arms parallel to the floor.', vi: 'Hai tay song song với sàn.' } },
]
