export const boundAngle = {
  id: 'bound-angle',
  styles: ['vinyasa', 'ashtanga'],
  family: 'hip-opener',
  level: 'gentle',
  en: 'Bound Angle Pose',
  aka: ['Butterfly', 'Cobbler’s Pose'],
  sa: 'Baddha Koṇāsana',
  say: 'BAH-dah koh-NAH-sah-nah',
  vi: 'Góc cố định (Con bướm)',
  ashtanga: {
    series: 'primary',
    section: 'seated',
    position: 33,
    vinyasas: 15,
    breaths: 5,
    drishti: 'nose',
    note: {
      en: 'Two folds held in the eighth vinyasa, five breaths each. In A you fold with a long spine, reaching your chin forward; in B you round your back and bring your head toward your feet.',
      vi: 'Hai lần gập người giữ ở vinyasa thứ tám, mỗi lần năm nhịp thở. Ở A bạn gập người với cột sống dài, cằm vươn về trước; ở B bạn cong tròn lưng và đưa đầu về phía bàn chân.',
    },
  },
  breath: {
    en: 'Inhale to sit tall and open your feet. Exhale to fold. Stay for five breaths in each version.',
    vi: 'Hít vào để ngồi thẳng và mở bàn chân. Thở ra để gập người. Giữ năm nhịp thở ở mỗi phiên bản.',
  },
  cues: [
    { id: 'bound-angle__cue-1', kind: 'transition', en: 'Bring the soles of your feet together and draw your heels in toward you.', vi: 'Áp hai gan bàn chân vào nhau và kéo gót chân vào sát người.' },
    { id: 'bound-angle__cue-2', kind: 'alignment', en: 'Open your feet like a book, with your thumbs on the soles.', vi: 'Mở hai bàn chân như mở một cuốn sách, ngón tay cái đặt trên gan bàn chân.' },
    { id: 'bound-angle__cue-3', kind: 'alignment', en: 'Sit tall, and let your knees drop out to the sides.', vi: 'Ngồi thẳng, và để hai gối hạ dần sang hai bên.' },
    { id: 'bound-angle__cue-4', kind: 'alignment', en: 'Exhale, fold forward with a long spine, reaching your chin forward.', vi: 'Thở ra, gập người về trước với cột sống dài, cằm vươn về trước.' },
    { id: 'bound-angle__cue-5', kind: 'soften', en: 'Let your inner thighs soften. Don’t push your knees down.', vi: 'Để mặt trong đùi mềm ra. Đừng ấn gối xuống.' },
    { id: 'bound-angle__cue-6', kind: 'breath', en: 'Stay for five breaths, gazing toward your nose.', vi: 'Giữ năm nhịp thở, nhìn về phía chóp mũi.' },
    { id: 'bound-angle__cue-7', kind: 'alignment', en: 'For B, round your back and bring your head toward your feet.', vi: 'Ở B, cong tròn lưng và đưa đầu về phía bàn chân.' },
    { id: 'bound-angle__cue-8', kind: 'safety', en: 'If your knees are higher than your hips, sit on a folded blanket.', vi: 'Nếu gối cao hơn hông, hãy ngồi lên một tấm chăn gấp.' },
    { id: 'bound-angle__cue-9', kind: 'transition', en: 'Inhale, come up to sit, and take a vinyasa.', vi: 'Hít vào, ngồi dậy, và làm một vinyasa.' },
  ],
  modifications: [
    { id: 'bound-angle__mod-1', en: 'Sit on a folded blanket so your pelvis can tip forward.', vi: 'Ngồi lên một tấm chăn gấp để khung chậu dễ nghiêng về trước.', props: ['blanket'] },
    { id: 'bound-angle__mod-2', en: 'Place blocks under your knees if they stay high.', vi: 'Kê gạch dưới gối nếu gối vẫn còn cao.', props: ['blocks'] },
    { id: 'bound-angle__mod-3', en: 'Move your feet further away from you for a gentler stretch.', vi: 'Đưa bàn chân ra xa người hơn để kéo giãn nhẹ nhàng hơn.', props: [] },
  ],
  safety: [
    { id: 'bound-angle__safe-1', en: 'Never press your knees down to open them; let them drop in their own time.', vi: 'Đừng bao giờ ấn gối xuống để mở; hãy để gối tự hạ xuống theo thời gian.' },
    { id: 'bound-angle__safe-2', en: 'If you’re pregnant, stay upright on a blanket instead of folding.', vi: 'Nếu bạn đang mang thai, hãy ngồi thẳng trên chăn thay vì gập người.' },
  ],
  muscles: {
    working: [],
    lengthening: ['hip-adductors', 'erector-spinae'],
  },
  joints: ['hip-joint', 'knee', 'sit-bones'],
  transitionsTo: ['wide-angle-seated-fold'],
  figure: 'bound-angle',
}
