export const embryoPose = {
  id: 'embryo-pose',
  styles: ['ashtanga'],
  family: 'seated',
  level: 'strong',
  en: 'Embryo in the Womb',
  aka: ['Womb Pose'],
  sa: 'Garbha Piṇḍāsana',
  say: 'GAR-bah pin-DAH-sah-nah',
  vi: 'Bào thai',
  ashtanga: {
    series: 'primary',
    section: 'seated',
    position: 31,
    vinyasas: 15,
    breaths: 5,
    drishti: 'nose',
    note: {
      en: 'Taken in full lotus, after Tortoise, and held in the eighth vinyasa. After five breaths you roll on your spine nine times, turning in a circle, and come up into Rooster.',
      vi: 'Tập trong thế hoa sen trọn vẹn, sau Con rùa, và giữ ở vinyasa thứ tám. Sau năm nhịp thở, bạn lăn trên cột sống chín lần, xoay thành một vòng tròn, rồi lên thế Gà trống.',
    },
  },
  breath: {
    en: 'Breathe slowly while you hold. As you roll, exhale to roll back and inhale to roll up.',
    vi: 'Thở chậm khi giữ thế. Khi lăn, thở ra để lăn ra sau và hít vào để lăn lên.',
  },
  cues: [
    { id: 'embryo-pose__cue-1', kind: 'transition', en: 'Come into full lotus, right foot first.', vi: 'Vào thế hoa sen trọn vẹn, bàn chân phải trước.' },
    { id: 'embryo-pose__cue-2', kind: 'alignment', en: 'Slide your right hand, then your left, through the gaps between your thighs and calves.', vi: 'Luồn tay phải, rồi tay trái, qua khe giữa đùi và bắp chân.' },
    { id: 'embryo-pose__cue-3', kind: 'alignment', en: 'Bring your arms through as far as your elbows.', vi: 'Đưa tay vào sâu đến khuỷu tay.' },
    { id: 'embryo-pose__cue-4', kind: 'alignment', en: 'Bend your elbows, lift your knees, and take hold of your ears.', vi: 'Gập khuỷu tay, nâng gối lên, và giữ lấy hai tai.' },
    { id: 'embryo-pose__cue-5', kind: 'alignment', en: 'Balance on your sitting bones and lift your chest.', vi: 'Giữ thăng bằng trên xương ngồi và nâng ngực lên.' },
    { id: 'embryo-pose__cue-6', kind: 'soften', en: 'Soften your shoulders, and stay calm if your arms feel snug.', vi: 'Thả lỏng vai, và giữ bình tĩnh nếu tay thấy chật.' },
    { id: 'embryo-pose__cue-7', kind: 'breath', en: 'Stay for five breaths, gazing toward your nose.', vi: 'Giữ năm nhịp thở, nhìn về phía chóp mũi.' },
    { id: 'embryo-pose__cue-8', kind: 'safety', en: 'If your knees hurt in lotus, sit cross-legged and hug your shins instead.', vi: 'Nếu gối đau trong thế hoa sen, hãy ngồi xếp bằng và ôm ống chân thay vào đó.' },
    { id: 'embryo-pose__cue-9', kind: 'transition', en: 'Round your back and roll nine times, turning in a circle, then come up into Rooster.', vi: 'Cong tròn lưng và lăn chín lần, xoay thành vòng tròn, rồi lên thế Gà trống.' },
  ],
  modifications: [
    { id: 'embryo-pose__mod-1', en: 'Sit cross-legged, hug your shins, and rock gently on your back.', vi: 'Ngồi xếp bằng, ôm ống chân, và lăn nhẹ trên lưng.', props: [] },
    { id: 'embryo-pose__mod-2', en: 'Roll on a folded blanket or a thick mat to cushion your spine.', vi: 'Lăn trên chăn gấp hoặc thảm dày để đỡ cho cột sống.', props: ['blanket'] },
    { id: 'embryo-pose__mod-3', en: 'If your arms won’t slide through, a little water on your arms helps. Never force them.', vi: 'Nếu tay chưa luồn qua được, làm ướt tay một chút sẽ dễ hơn. Đừng bao giờ ép.', props: [] },
  ],
  safety: [
    { id: 'embryo-pose__safe-1', en: 'Lotus must come from your hips. Any pain inside your knee means come out.', vi: 'Thế hoa sen phải đến từ khớp háng. Nếu thấy đau bên trong gối, hãy thoát thế ngay.' },
    { id: 'embryo-pose__safe-2', en: 'Keep your chin tucked as you roll, so your head doesn’t hit the floor.', vi: 'Giữ cằm thu vào khi lăn, để đầu không đập xuống sàn.' },
    { id: 'embryo-pose__safe-3', en: 'If you’re pregnant, skip this pose.', vi: 'Nếu bạn đang mang thai, hãy bỏ qua tư thế này.' },
  ],
  muscles: {
    working: ['rectus-abdominis', 'iliopsoas'],
    lengthening: ['erector-spinae'],
  },
  joints: ['knee', 'ankle', 'hip-joint', 'thoracic-spine'],
  transitionsTo: ['rooster-pose'],
  figure: 'embryo-pose',
}
