export const upwardPlank = {
  id: 'upward-plank',
  styles: ['vinyasa', 'ashtanga'],
  family: 'backbend',
  level: 'moderate',
  en: 'Upward Plank',
  aka: ['Reverse Plank'],
  sa: 'Pūrvottānāsana',
  say: 'poor-voh-tah-NAH-sah-nah',
  vi: 'Tấm ván ngược',
  ashtanga: {
    series: 'primary',
    section: 'seated',
    position: 23,
    vinyasas: 15,
    breaths: 5,
    drishti: 'nose',
    note: {
      en: 'The counterpose to Seated Forward Fold: after folding, you open the whole front of your body. It is held in the eighth vinyasa, for five breaths.',
      vi: 'Tư thế đối của Ngồi gập người về trước: sau khi gập, bạn mở toàn bộ mặt trước cơ thể. Tư thế được giữ ở vinyasa thứ tám, năm nhịp thở.',
    },
  },
  breath: {
    en: 'Inhale to lift your hips. Stay for five breaths. Exhale to sit back down.',
    vi: 'Hít vào để nâng hông. Giữ năm nhịp thở. Thở ra để ngồi xuống.',
  },
  cues: [
    { id: 'upward-plank__cue-1', kind: 'transition', en: 'Place your hands a little behind your hips, fingers pointing toward your feet.', vi: 'Đặt hai tay phía sau hông một chút, các ngón tay hướng về phía bàn chân.' },
    { id: 'upward-plank__cue-2', kind: 'transition', en: 'Inhale, press into your hands and feet, and lift your hips high.', vi: 'Hít vào, ấn hai tay và hai bàn chân xuống, nâng hông lên cao.' },
    { id: 'upward-plank__cue-3', kind: 'alignment', en: 'Point your toes and reach the soles of your feet toward the floor.', vi: 'Duỗi mũi chân và hướng gan bàn chân xuống sàn.' },
    { id: 'upward-plank__cue-4', kind: 'alignment', en: 'Keep your legs straight and together.', vi: 'Giữ hai chân thẳng và khép lại.' },
    { id: 'upward-plank__cue-5', kind: 'alignment', en: 'Open your chest and draw your shoulder blades toward each other.', vi: 'Mở ngực và kéo hai bả vai lại gần nhau.' },
    { id: 'upward-plank__cue-6', kind: 'soften', en: 'Let your head release back slowly, and keep your neck soft.', vi: 'Từ từ thả đầu ra sau, giữ cổ mềm.' },
    { id: 'upward-plank__cue-7', kind: 'breath', en: 'Stay for five breaths, gazing toward your nose.', vi: 'Giữ năm nhịp thở, nhìn về phía chóp mũi.' },
    { id: 'upward-plank__cue-8', kind: 'safety', en: 'If your neck feels strained, keep your chin toward your chest.', vi: 'Nếu cổ thấy căng, giữ cằm hướng về phía ngực.' },
    { id: 'upward-plank__cue-9', kind: 'transition', en: 'Exhale, and lower your hips slowly to the floor.', vi: 'Thở ra, từ từ hạ hông xuống sàn.' },
  ],
  modifications: [
    { id: 'upward-plank__mod-1', en: 'Bend your knees and lift into Reverse Tabletop, with your feet flat on the floor.', vi: 'Co gối và nâng lên tư thế Cái bàn ngược, bàn chân đặt phẳng trên sàn.', props: [] },
    { id: 'upward-plank__mod-2', en: 'Turn your fingers out to the sides if your wrists or shoulders feel tight.', vi: 'Xoay các ngón tay sang hai bên nếu cổ tay hoặc vai thấy căng.', props: [] },
  ],
  safety: [
    { id: 'upward-plank__safe-1', en: 'Only let your head go back if your neck is happy there. Otherwise keep your chin in.', vi: 'Chỉ thả đầu ra sau nếu cổ thấy thoải mái. Nếu không, hãy giữ cằm thu vào.' },
    { id: 'upward-plank__safe-2', en: 'If you have a wrist or shoulder injury, take Reverse Tabletop, or skip this pose.', vi: 'Nếu cổ tay hoặc vai đang bị chấn thương, hãy tập Cái bàn ngược, hoặc bỏ qua tư thế này.' },
    { id: 'upward-plank__safe-3', en: 'Later in pregnancy, take Reverse Tabletop with your knees bent, or rest.', vi: 'Ở giai đoạn cuối thai kỳ, tập Cái bàn ngược với gối co, hoặc nghỉ.' },
  ],
  muscles: {
    working: ['gluteus-maximus', 'hamstrings', 'triceps-brachii', 'erector-spinae'],
    lengthening: ['pectoralis-major', 'biceps-brachii'],
  },
  joints: ['wrist', 'shoulder-joint', 'hip-joint', 'cervical-spine'],
  transitionsTo: ['half-bound-lotus-forward-fold'],
  figure: 'upward-plank',
}
