/**
 * Class talk by moment, meditation, and the Sanskrit and Pali words she
 * teaches with. Each line has English, Vietnamese and an audio clip
 * (`phrase__<id>`). Written in the register of a calm native teacher; the
 * Vietnamese is what the line means, not a word-for-word gloss, and students
 * are always "bạn".
 *
 * A group: { id, title, short (chip label), lead (one line under the title),
 *   area: 'class' | 'mind', kind?, parts?, lines }
 *   kind 'script'    lines in order, each with `pauseAfter` seconds; the page
 *                    offers "lead it", which plays them honouring the pauses
 *   kind 'count'     lines in `parts` ({ id, title, note?, voice? }); a part
 *                    whose lines all carry `pauseAfter` can be led too; a
 *                    part's `voice` gives it its own audio style
 *   kind 'concepts'  one card per word (see below)
 *
 * A line: { id, en, vi, say?, term?, lang?, pauseAfter?, part?, meaning? }
 *   en    what the voice says (the audio generator speaks `en`)
 *   term  the IAST spelling, shown in the serif (counts, gazes, mantras)
 *   say   a stress respelling, stressed syllables in capitals
 *   lang  'sa' | 'pi' when the line itself is Sanskrit or Pali; the respelling
 *         then goes into the voice direction
 *
 * A concept line: { id, kind: 'concept', term, lang, say, en, vi, meaning,
 *   bridge, inClass, source? }
 *   en      the word as it is spoken and written in a studio (for Pali, the
 *           IAST itself)
 *   vi      a short Vietnamese name for it
 *   bridge  the Sino-Vietnamese Buddhist word she already knows, or null;
 *           `near: true` marks a parallel rather than the same word
 *   inClass one sentence she can say to a class (clip `phrase__<id>__inclass`)
 *   source  where the bridge was checked
 */
export const PHRASE_GROUPS = [
  {
    id: 'welcome', area: 'class',
    title: { en: 'Welcoming the class', vi: 'Chào lớp' },
    short: { en: 'Welcome', vi: 'Chào lớp' },
    lead: { en: 'Before the first pose: greeting, asking, arriving.', vi: 'Trước tư thế đầu tiên: chào hỏi, hỏi han, ổn định.' },
    lines: [
      { id: 'welcome-7', en: 'Hi, welcome! Have you practised yoga before?', vi: 'Chào bạn, chào mừng bạn đến lớp! Bạn đã tập yoga bao giờ chưa?' },
      { id: 'welcome-8', en: 'Grab a mat and a block, and find a spot wherever you like.', vi: 'Bạn lấy một tấm thảm và một viên gạch, rồi chọn chỗ nào bạn thích.' },
      { id: 'welcome-1', en: 'Welcome, everyone. Find a comfortable seat and let your eyes close.', vi: 'Chào mừng mọi người. Tìm một tư thế ngồi thoải mái và để mắt khép lại.' },
      { id: 'welcome-2', en: 'Before we begin, is anyone working with an injury today, or pregnant?', vi: 'Trước khi bắt đầu, hôm nay có ai đang có chấn thương, hoặc đang mang thai không?' },
      { id: 'welcome-3', en: 'If anything doesn’t feel right in your body today, you can always rest in Child’s Pose.', vi: 'Nếu hôm nay có gì không ổn trong cơ thể, bạn luôn có thể nghỉ ở tư thế Em bé.' },
      { id: 'welcome-4', en: 'Let’s take three slow breaths together to arrive.', vi: 'Cùng hít thở chậm ba hơi để thực sự có mặt ở đây.' },
      { id: 'welcome-5', en: 'Set a small intention for your practice. Something simple.', vi: 'Đặt một ý định nhỏ cho buổi tập. Điều gì đó đơn giản thôi.' },
      { id: 'welcome-6', en: 'Today we’ll move slowly and spend some time in the hips.', vi: 'Hôm nay chúng ta sẽ chuyển động chậm và dành thời gian cho vùng hông.' },
    ],
  },
  {
    id: 'injuries-and-consent', area: 'class',
    title: { en: 'Injuries, pregnancy and touch', vi: 'Chấn thương, thai kỳ và chạm' },
    short: { en: 'Injuries & touch', vi: 'Chấn thương' },
    lead: { en: 'Asking about bodies, and asking before you touch.', vi: 'Hỏi về cơ thể học viên, và hỏi trước khi chạm.' },
    lines: [
      { id: 'inj-1', en: 'Is there anything I should know about your body today? Any injuries or pain?', vi: 'Hôm nay có điều gì về cơ thể bạn mà tôi nên biết không? Có chấn thương hay chỗ nào đau không?' },
      { id: 'inj-2', en: 'If you’d rather not say it out loud, come and tell me quietly.', vi: 'Nếu bạn không muốn nói trước cả lớp, cứ đến nói riêng với tôi.' },
      { id: 'inj-3', en: 'If you’re pregnant, let me know, and I’ll give you options as we go.', vi: 'Nếu bạn đang mang thai, hãy cho tôi biết, tôi sẽ đưa ra lựa chọn phù hợp trong suốt buổi tập.' },
      { id: 'inj-4', en: 'Where exactly do you feel it? Can you show me?', vi: 'Bạn thấy đau chính xác ở đâu? Bạn chỉ cho tôi xem được không?' },
      { id: 'inj-5', en: 'I sometimes offer gentle hands-on adjustments during class.', vi: 'Trong giờ tập, đôi khi tôi sẽ chỉnh tư thế nhẹ nhàng bằng tay.' },
      { id: 'inj-6', en: 'If you’d rather not be touched today, that’s completely fine. Just tell me.', vi: 'Nếu hôm nay bạn không muốn được chạm vào, hoàn toàn không sao. Chỉ cần nói với tôi.' },
      { id: 'inj-7', en: 'I’m going to press gently on your sacrum. Tell me if you’d like more or less.', vi: 'Tôi sẽ ấn nhẹ lên xương cùng của bạn. Muốn mạnh hơn hay nhẹ hơn thì cứ nói nhé.' },
      { id: 'inj-8', en: 'Is this pressure okay?', vi: 'Lực như thế này được không?' },
      { id: 'inj-9', en: 'No problem at all. Thank you for telling me.', vi: 'Không sao cả. Cảm ơn bạn đã cho tôi biết.' },
      { id: 'inj-10', en: 'With that knee, I’d skip this one today. Let’s try this instead.', vi: 'Với đầu gối như vậy, hôm nay bạn nên bỏ qua tư thế này. Mình thử cách này nhé.' },
      { id: 'inj-11', en: 'I’m not a doctor, so please check with your physio first.', vi: 'Tôi không phải bác sĩ, nên bạn hãy hỏi chuyên viên vật lý trị liệu trước nhé.' },
    ],
  },
  {
    id: 'breath', area: 'class',
    title: { en: 'Breath and rhythm', vi: 'Hơi thở và nhịp' },
    short: { en: 'Breath', vi: 'Hơi thở' },
    lead: { en: 'Linking the breath and the movement.', vi: 'Nối hơi thở với chuyển động.' },
    lines: [
      { id: 'breath-1', en: 'Inhale, reach up. Exhale, fold forward.', vi: 'Hít vào, vươn lên. Thở ra, gập người về trước.' },
      { id: 'breath-2', en: 'On your next exhale, slowly come out of the pose.', vi: 'Ở hơi thở ra tiếp theo, từ từ thoát khỏi tư thế.' },
      { id: 'breath-3', en: 'Stay here for five breaths.', vi: 'Giữ ở đây trong năm nhịp thở.' },
      { id: 'breath-4', en: 'Let the breath lead the movement, not the other way around.', vi: 'Để hơi thở dẫn dắt chuyển động, không phải ngược lại.' },
      { id: 'breath-5', en: 'If you lose your breath, you’ve gone too far. Back off a little.', vi: 'Nếu mất hơi thở, bạn đã đi quá xa. Lùi lại một chút.' },
      { id: 'breath-6', en: 'Breathe in through your nose, and out through your nose.', vi: 'Hít vào bằng mũi, và thở ra bằng mũi.' },
      { id: 'breath-7', en: 'Make the exhale a little longer than the inhale.', vi: 'Thở ra dài hơn hít vào một chút.' },
      { id: 'breath-8', en: 'One more breath here. And release.', vi: 'Thêm một hơi thở ở đây. Và thả.' },
    ],
  },
  {
    id: 'transitions', area: 'class',
    title: { en: 'Moving between poses', vi: 'Chuyển tiếp giữa các tư thế' },
    short: { en: 'Transitions', vi: 'Chuyển thế' },
    lead: { en: 'Getting from one pose to the next, and counting the breaths.', vi: 'Đi từ tư thế này sang tư thế khác, và đếm nhịp thở.' },
    lines: [
      { id: 'trans-1', en: 'From Downward Dog, step your right foot forward between your hands.', vi: 'Từ Chó úp mặt, bước chân phải lên trước giữa hai tay.' },
      { id: 'trans-2', en: 'Come onto all fours, wrists under shoulders, knees under hips.', vi: 'Về tư thế bốn điểm, cổ tay dưới vai, gối dưới hông.' },
      { id: 'trans-3', en: 'Take a vinyasa if you’d like, or meet me in Downward Dog.', vi: 'Làm một vinyasa nếu bạn muốn, hoặc gặp tôi ở Chó úp mặt.' },
      { id: 'trans-9', en: 'Take a vinyasa, or skip it and rest in Child’s Pose.', vi: 'Làm một vinyasa, hoặc bỏ qua và nghỉ ở tư thế Em bé.' },
      { id: 'trans-10', en: 'Five breaths here. Inhale, exhale, that’s one.', vi: 'Năm nhịp thở ở đây. Hít vào, thở ra, đó là một.' },
      { id: 'trans-11', en: 'Last breath here. Inhale fully, exhale completely.', vi: 'Hơi thở cuối cùng ở đây. Hít vào thật đầy, thở ra thật hết.' },
      { id: 'trans-4', en: 'Let’s come into Sleeping Swan.', vi: 'Chúng ta vào tư thế Thiên nga ngủ.' },
      { id: 'trans-5', en: 'Slowly make your way to the top of your mat.', vi: 'Từ từ di chuyển về đầu thảm.' },
      { id: 'trans-6', en: 'Other side. Take your time.', vi: 'Đổi bên. Cứ từ từ.' },
      { id: 'trans-7', en: 'Lower all the way down onto your belly.', vi: 'Hạ hẳn người xuống nằm sấp.' },
      { id: 'trans-8', en: 'Roll over onto your back and hug your knees in.', vi: 'Lăn người nằm ngửa và ôm gối vào ngực.' },
    ],
  },
  {
    id: 'props-and-options', area: 'class',
    title: { en: 'Props and options', vi: 'Dụng cụ và lựa chọn' },
    short: { en: 'Props', vi: 'Dụng cụ' },
    lead: { en: 'Blocks, straps, bolsters, the wall, and “you can also…”', vi: 'Gạch, dây, gối tựa, bức tường, và “bạn cũng có thể…”' },
    lines: [
      { id: 'props-1', en: 'Today you’ll need two blocks, a strap and a bolster.', vi: 'Hôm nay bạn cần hai viên gạch, một sợi dây tập và một gối tựa (bolster).' },
      { id: 'props-2', en: 'Bring the floor closer. Place a block under each hand.', vi: 'Đưa sàn lại gần bạn hơn. Đặt một viên gạch dưới mỗi tay.' },
      { id: 'props-3', en: 'If your hamstrings are tight, sit up on a folded blanket.', vi: 'Nếu cơ đùi sau bị căng, hãy ngồi lên một tấm chăn gấp.' },
      { id: 'props-4', en: 'Loop the strap around the ball of your foot, and hold it with both hands.', vi: 'Vòng dây tập quanh phần gan bàn chân trước, và giữ dây bằng hai tay.' },
      { id: 'props-5', en: 'Slide a bolster under your knees and let your legs relax.', vi: 'Đặt gối tựa dưới đầu gối và để hai chân thả lỏng.' },
      { id: 'props-6', en: 'Use the wall for balance. Your fingertips are enough.', vi: 'Dùng tường để giữ thăng bằng. Chỉ cần chạm đầu ngón tay là đủ.' },
      { id: 'props-7', en: 'Add a blanket under your knees if they feel sensitive.', vi: 'Lót thêm chăn dưới đầu gối nếu gối thấy nhạy cảm.' },
      { id: 'props-8', en: 'You can also stay right here. This is the full pose for you today.', vi: 'Bạn cũng có thể ở yên đây. Hôm nay, đây chính là tư thế trọn vẹn của bạn.' },
      { id: 'props-9', en: 'Props aren’t cheating. They bring the pose to you.', vi: 'Dùng dụng cụ không phải là ăn gian. Chúng mang tư thế đến gần bạn hơn.' },
    ],
  },
  {
    id: 'safety', area: 'class',
    title: { en: 'Safety, options and adjustments', vi: 'An toàn, lựa chọn và chỉnh sửa' },
    short: { en: 'Safety', vi: 'An toàn' },
    lead: { en: 'Sensation, pain, rest and pregnancy.', vi: 'Cảm giác, cơn đau, nghỉ ngơi và thai kỳ.' },
    lines: [
      { id: 'safe-1', en: 'If this is too much, bend your knees as much as you need.', vi: 'Nếu quá sức, cứ chùng gối bao nhiêu tuỳ cần.' },
      { id: 'safe-2', en: 'You can always take a block under your hand.', vi: 'Bạn luôn có thể kê một viên gạch dưới tay.' },
      { id: 'safe-3', en: 'Sensation is fine; sharp pain is not. If it’s sharp, come out.', vi: 'Cảm giác căng thì được, đau nhói thì không. Nếu nhói, hãy thoát thế.' },
      { id: 'safe-4', en: 'Would you like a hands-on adjustment? Just nod.', vi: 'Bạn có muốn tôi chỉnh bằng tay không? Gật đầu là được.' },
      { id: 'safe-5', en: 'I’m going to place my hand on your lower back. Is that okay?', vi: 'Tôi sẽ đặt tay lên lưng dưới của bạn. Được không?' },
      { id: 'safe-6', en: 'If you’re pregnant, keep your feet wider and skip the deep twists.', vi: 'Nếu bạn đang mang thai, để hai chân rộng hơn và bỏ qua các tư thế vặn sâu.' },
      { id: 'safe-7', en: 'Listen to your body today, not to yesterday’s body.', vi: 'Lắng nghe cơ thể hôm nay, không phải cơ thể của hôm qua.' },
      { id: 'safe-8', en: 'There’s no wrong way to rest.', vi: 'Không có cách nghỉ nào là sai.' },
    ],
  },
  {
    id: 'yin', area: 'class',
    title: { en: 'Yin holds', vi: 'Giữ thế trong Yin' },
    short: { en: 'Yin', vi: 'Yin' },
    lead: { en: 'The edge, stillness, time, the rebound, and when to come out.', vi: 'Ngưỡng, sự tĩnh lặng, thời gian, dư âm, và lúc nên thoát thế.' },
    lines: [
      { id: 'yin-7', en: 'Come into the shape slowly. Stop at the first place you feel a stretch.', vi: 'Vào tư thế thật chậm. Dừng lại ở chỗ đầu tiên bạn cảm thấy căng.' },
      { id: 'yin-1', en: 'Find your edge. Enough to feel it, not so much that you tense against it.', vi: 'Tìm ngưỡng của bạn. Đủ để cảm nhận, nhưng không căng cứng chống lại nó.' },
      { id: 'yin-8', en: 'Now be still. Let the pose come to you.', vi: 'Giờ thì tĩnh lặng. Để tư thế tự đến với bạn.' },
      { id: 'yin-2', en: 'Let the muscles go soft. Let the weight of your body do the work.', vi: 'Để các cơ mềm ra. Để trọng lượng cơ thể làm việc.' },
      { id: 'yin-3', en: 'We’ll be here for three minutes. There’s nowhere to get to.', vi: 'Chúng ta sẽ ở đây ba phút. Không cần phải đến đâu cả.' },
      { id: 'yin-4', en: 'If the mind wanders, come back to the feeling in the hip.', vi: 'Nếu tâm trí lang thang, quay về với cảm giác ở hông.' },
      { id: 'yin-5', en: 'Halfway there. If you’d like to go a little deeper, you can, but you don’t have to.', vi: 'Được nửa đường rồi. Nếu muốn vào sâu hơn một chút, bạn có thể, nhưng không bắt buộc.' },
      { id: 'yin-9', en: 'Tingling, numbness or sharp pain are signs to come out.', vi: 'Tê rần, tê bì hoặc đau nhói là dấu hiệu bạn cần thoát thế.' },
      { id: 'yin-10', en: 'Use your hands to help your legs out, slowly.', vi: 'Dùng tay giúp hai chân ra khỏi tư thế, thật chậm.' },
      { id: 'yin-6', en: 'Slowly come out, and notice the rebound.', vi: 'Từ từ thoát thế, và cảm nhận dư âm.' },
    ],
  },
  {
    id: 'ashtanga-count', area: 'class', kind: 'count',
    title: { en: 'The Ashtanga count', vi: 'Đếm trong lớp Ashtanga' },
    short: { en: 'Ashtanga count', vi: 'Đếm Ashtanga' },
    lead: { en: 'The led-class count, the gazes, and the opening and closing mantras.', vi: 'Cách đếm trong lớp dẫn, các điểm nhìn, và câu chú mở đầu, kết thúc.' },
    parts: [
      {
        id: 'surya-a', title: { en: 'Sūrya Namaskāra A', vi: 'Chào mặt trời A' },
        note: { en: 'One count, one breath. Lead it to practise the rhythm.', vi: 'Mỗi số đếm là một hơi thở. Dẫn thử để tập nhịp.' },
      },
      {
        id: 'surya-b', title: { en: 'Counting on: daśa to saptadaśa', vi: 'Đếm tiếp: mười đến mười bảy' },
        note: { en: 'The second half of Sūrya Namaskāra B, after the first Warrior.', vi: 'Nửa sau của Chào mặt trời B, sau tư thế Chiến binh đầu tiên.' },
      },
      {
        id: 'supta', title: { en: 'Up to ṣaḍviṃśatiḥ', vi: 'Đến hai mươi sáu' },
        note: { en: 'The left side of Supta Pādāṅguṣṭhāsana, the highest count in the primary series.', vi: 'Bên trái của Supta Pādāṅguṣṭhāsana, số đếm cao nhất trong chuỗi sơ cấp.' },
      },
      {
        id: 'drishti', title: { en: 'Dṛṣṭi: where the eyes rest', vi: 'Dṛṣṭi: điểm nhìn' },
        note: { en: 'The nine gazes; pārśva covers both sides.', vi: 'Chín điểm nhìn; pārśva gồm cả hai bên.' },
      },
      {
        id: 'opening', voice: 'chant', title: { en: 'Opening mantra', vi: 'Câu chú mở đầu' },
        note: { en: 'Chanted before practice, to the teachers and to Patañjali.', vi: 'Tụng trước buổi tập, kính các bậc thầy và Patañjali.' },
      },
      {
        id: 'closing', voice: 'chant', title: { en: 'Closing mantra', vi: 'Câu chú kết thúc' },
        note: { en: 'Chanted at the end of practice, a wish for the well-being of all.', vi: 'Tụng cuối buổi tập, một lời nguyện an lành cho tất cả.' },
      },
    ],
    lines: [
      { id: 'count-1', part: 'surya-a', term: 'ekam', say: 'EH-kum', en: 'Ekam, inhale, reach your arms up.', vi: 'Một, hít vào, vươn hai tay lên.', pauseAfter: 1.5 },
      { id: 'count-2', part: 'surya-a', term: 'dve', say: 'DVAY', en: 'Dve, exhale, fold forward.', vi: 'Hai, thở ra, gập người về trước.', pauseAfter: 1.5 },
      { id: 'count-3', part: 'surya-a', term: 'trīṇi', say: 'TREE-nee', en: 'Trini, inhale, look up.', vi: 'Ba, hít vào, nhìn lên.', pauseAfter: 1.5 },
      { id: 'count-4', part: 'surya-a', term: 'catvāri', say: 'chut-VAH-ree', en: 'Chatvari, exhale, jump back to Chaturanga.', vi: 'Bốn, thở ra, nhảy lùi về Chaturanga.', pauseAfter: 1.5 },
      { id: 'count-5', part: 'surya-a', term: 'pañca', say: 'PUN-chuh', en: 'Pancha, inhale, Upward Dog.', vi: 'Năm, hít vào, Chó ngửa mặt.', pauseAfter: 1.5 },
      { id: 'count-6', part: 'surya-a', term: 'ṣaṭ', say: 'SHUT', en: 'Shat, exhale, Downward Dog. Five breaths.', vi: 'Sáu, thở ra, Chó úp mặt. Năm nhịp thở.', pauseAfter: 20 },
      { id: 'count-7', part: 'surya-a', term: 'sapta', say: 'SUP-tuh', en: 'Sapta, inhale, jump forward, look up.', vi: 'Bảy, hít vào, nhảy lên trước, nhìn lên.', pauseAfter: 1.5 },
      { id: 'count-8', part: 'surya-a', term: 'aṣṭau', say: 'USH-tow', en: 'Ashtau, exhale, fold.', vi: 'Tám, thở ra, gập người.', pauseAfter: 1.5 },
      { id: 'count-9', part: 'surya-a', term: 'nava', say: 'NUH-vuh', en: 'Nava, inhale, come all the way up.', vi: 'Chín, hít vào, đứng thẳng lên.', pauseAfter: 1.5 },
      { id: 'count-samasthitih', part: 'surya-a', term: 'samasthitiḥ', say: 'suh-muh-STI-tee-hee', en: 'Exhale, samasthitih. Stand still, arms by your sides.', vi: 'Thở ra, samasthitiḥ. Đứng yên, hai tay buông dọc thân người.', pauseAfter: 0 },

      { id: 'count-10', part: 'surya-b', term: 'daśa', say: 'DUH-shuh', en: 'Dasha, exhale, Downward Dog.', vi: 'Mười, thở ra, Chó úp mặt.' },
      { id: 'count-11', part: 'surya-b', term: 'ekādaśa', say: 'eh-KAH-duh-shuh', en: 'Ekadasha, inhale, left foot forward, Warrior One.', vi: 'Mười một, hít vào, bước chân trái lên, Chiến binh I.' },
      { id: 'count-12', part: 'surya-b', term: 'dvādaśa', say: 'DVAH-duh-shuh', en: 'Dvadasha, exhale, Chaturanga.', vi: 'Mười hai, thở ra, Chaturanga.' },
      { id: 'count-13', part: 'surya-b', term: 'trayodaśa', say: 'truh-YOH-duh-shuh', en: 'Trayodasha, inhale, Upward Dog.', vi: 'Mười ba, hít vào, Chó ngửa mặt.' },
      { id: 'count-14', part: 'surya-b', term: 'caturdaśa', say: 'chuh-TOOR-duh-shuh', en: 'Chaturdasha, exhale, Downward Dog. Five breaths.', vi: 'Mười bốn, thở ra, Chó úp mặt. Năm nhịp thở.' },
      { id: 'count-15', part: 'surya-b', term: 'pañcadaśa', say: 'PUN-chuh-duh-shuh', en: 'Panchadasha, inhale, jump forward, look up.', vi: 'Mười lăm, hít vào, nhảy lên trước, nhìn lên.' },
      { id: 'count-16', part: 'surya-b', term: 'ṣoḍaśa', say: 'SHOH-duh-shuh', en: 'Shodasha, exhale, fold.', vi: 'Mười sáu, thở ra, gập người.' },
      { id: 'count-17', part: 'surya-b', term: 'saptadaśa', say: 'SUP-tuh-duh-shuh', en: 'Saptadasha, inhale, bend your knees, arms up.', vi: 'Mười bảy, hít vào, chùng gối, hai tay vươn lên.' },

      { id: 'count-18', part: 'supta', term: 'aṣṭādaśa', say: 'ush-TAH-duh-shuh', en: 'Ashtadasha, inhale, head down.', vi: 'Mười tám, hít vào, đặt đầu xuống sàn.' },
      { id: 'count-19', part: 'supta', term: 'ekonaviṃśatiḥ', say: 'eh-koh-nuh-VIM-shuh-tee-hee', en: 'Ekonavimshatih, exhale, leg to the left.', vi: 'Mười chín, thở ra, đưa chân sang trái.' },
      { id: 'count-20', part: 'supta', term: 'viṃśatiḥ', say: 'VIM-shuh-tee-hee', en: 'Vimshatih, inhale, leg back to the centre.', vi: 'Hai mươi, hít vào, đưa chân về giữa.' },
      { id: 'count-21', part: 'supta', term: 'ekaviṃśatiḥ', say: 'eh-kuh-VIM-shuh-tee-hee', en: 'Ekavimshatih, exhale, chin to your shin.', vi: 'Hai mươi mốt, thở ra, cằm chạm ống chân.' },
      { id: 'count-22', part: 'supta', term: 'dvāviṃśatiḥ', say: 'dvah-VIM-shuh-tee-hee', en: 'Dvavimshatih, inhale, head down.', vi: 'Hai mươi hai, hít vào, đặt đầu xuống sàn.' },
      { id: 'count-23', part: 'supta', term: 'trayoviṃśatiḥ', say: 'truh-yoh-VIM-shuh-tee-hee', en: 'Trayovimshatih, exhale, lower your leg.', vi: 'Hai mươi ba, thở ra, hạ chân xuống.' },
      { id: 'count-24', part: 'supta', term: 'caturviṃśatiḥ', say: 'chuh-toor-VIM-shuh-tee-hee', en: 'Chaturvimshatih, inhale, Chakrasana, roll back.', vi: 'Hai mươi bốn, hít vào, Chakrasana, lộn người ra sau.' },
      { id: 'count-25', part: 'supta', term: 'pañcaviṃśatiḥ', say: 'pun-chuh-VIM-shuh-tee-hee', en: 'Panchavimshatih, inhale, Upward Dog.', vi: 'Hai mươi lăm, hít vào, Chó ngửa mặt.' },
      { id: 'count-26', part: 'supta', term: 'ṣaḍviṃśatiḥ', say: 'shud-VIM-shuh-tee-hee', en: 'Shadvimshatih, exhale, Downward Dog.', vi: 'Hai mươi sáu, thở ra, Chó úp mặt.' },

      { id: 'drishti-nasagra', part: 'drishti', term: 'nāsāgra', say: 'nah-SAH-gruh', en: 'Nasagra drishti. Gaze at the tip of your nose.', vi: 'Nhìn vào chóp mũi.' },
      { id: 'drishti-bhrumadhya', part: 'drishti', term: 'bhrūmadhya', say: 'broo-MUD-yuh', en: 'Bhrumadhya drishti. Gaze between your eyebrows.', vi: 'Nhìn vào khoảng giữa hai lông mày.' },
      { id: 'drishti-nabhi', part: 'drishti', term: 'nābhi', say: 'NAH-bee', en: 'Nabhi drishti. Gaze toward your navel.', vi: 'Nhìn về phía rốn.' },
      { id: 'drishti-hastagra', part: 'drishti', term: 'hastāgra', say: 'hus-TAH-gruh', en: 'Hastagra drishti. Gaze at your hand.', vi: 'Nhìn vào bàn tay.' },
      { id: 'drishti-padayoragra', part: 'drishti', term: 'pādayoragra', say: 'PAH-duh-yoh-RUG-ruh', en: 'Padayoragra drishti. Gaze at your toes.', vi: 'Nhìn vào các ngón chân.' },
      { id: 'drishti-parsva', part: 'drishti', term: 'pārśva', say: 'PARSH-vuh', en: 'Parshva drishti. Gaze far to the side.', vi: 'Nhìn xa sang một bên, trái hoặc phải.' },
      { id: 'drishti-angustha', part: 'drishti', term: 'aṅguṣṭha', say: 'un-GOOSH-tuh', en: 'Angushtha drishti. Gaze at your thumbs.', vi: 'Nhìn vào hai ngón tay cái.' },
      { id: 'drishti-urdhva', part: 'drishti', term: 'ūrdhva', say: 'OORD-vuh', en: 'Urdhva drishti. Gaze up.', vi: 'Nhìn lên trên.' },

      {
        id: 'mantra-open-1', part: 'opening', lang: 'sa',
        term: 'oṃ\nvande gurūṇāṃ caraṇāravinde\nsandarśita svātma sukhāvabodhe',
        say: 'OHM. VUN-day goo-ROO-naam chuh-ruh-NAH-ruh-VIN-day, sun-DAR-shi-tuh SVAHT-muh soo-KAH-vuh-BOH-day',
        en: 'Om. Vande gurunam charanaravinde, sandarshita svatma sukhavabodhe.',
        meaning: { en: 'Om. I bow to the lotus feet of the teachers, who awaken the joy of knowing the true Self.', vi: 'Om. Xin cúi đầu trước bàn chân sen của các bậc thầy, những người đánh thức niềm an vui khi nhận ra chân ngã.' },
        vi: 'Om. Xin cúi đầu trước bàn chân sen của các bậc thầy, những người đánh thức niềm an vui khi nhận ra chân ngã.',
      },
      {
        id: 'mantra-open-2', part: 'opening', lang: 'sa',
        term: 'niḥśreyase jāṅgalikāyamāne\nsaṃsāra hālāhala mohaśāntyai',
        say: 'nih-SHRAY-yuh-say JAHN-guh-lee-KAH-yuh-MAH-nay, sum-SAH-ruh HAH-luh-huh-luh MOH-huh-SHAHN-tyai',
        en: 'Nihshreyase jangalikayamane, samsara halahala mohashantyai.',
        meaning: { en: 'Like a healer in the jungle, they bring the highest good and calm the poison of delusion in the cycle of existence.', vi: 'Như vị thầy thuốc giữa rừng sâu, các ngài mang đến điều thiện tối thượng và hoá giải chất độc si mê của vòng luân hồi.' },
        vi: 'Như vị thầy thuốc giữa rừng sâu, các ngài mang đến điều thiện tối thượng và hoá giải chất độc si mê của vòng luân hồi.',
      },
      {
        id: 'mantra-open-3', part: 'opening', lang: 'sa',
        term: 'ābāhu puruṣākāraṃ\nśaṅkhacakrāsi dhāriṇam',
        say: 'AH-bah-hoo poo-roo-SHAH-kah-rum, SHUNG-kuh-CHUK-rah-see DAH-ree-num',
        en: 'Abahu purushakaram, shankha chakrasi dharinam.',
        meaning: { en: 'To Patañjali, human in form above, holding a conch, a discus and a sword,', vi: 'Kính Patañjali, nửa trên mang hình người, tay cầm tù và, bánh xe và thanh gươm,' },
        vi: 'Kính Patañjali, nửa trên mang hình người, tay cầm tù và, bánh xe và thanh gươm,',
      },
      {
        id: 'mantra-open-4', part: 'opening', lang: 'sa',
        term: 'sahasra śirasaṃ śvetaṃ\npraṇamāmi patañjalim\noṃ',
        say: 'suh-HUS-ruh shee-RUH-sum SHVAY-tum, pruh-nuh-MAH-mee puh-TUN-juh-lim. OHM.',
        en: 'Sahasra shirasam shvetam, pranamami patanjalim. Om.',
        meaning: { en: 'radiant white, with a thousand serpent heads: to Patañjali I bow. Om.', vi: 'trắng sáng, với ngàn đầu rắn thần: xin cúi đầu trước Patañjali. Om.' },
        vi: 'trắng sáng, với ngàn đầu rắn thần: xin cúi đầu trước Patañjali. Om.',
      },
      {
        id: 'mantra-close-1', part: 'closing', lang: 'sa',
        term: 'oṃ\nsvasti prajābhyaḥ paripālayantāṃ\nnyāyena mārgeṇa mahīṃ mahīśāḥ',
        say: 'OHM. SVUS-tee pruh-JAH-bhyuh-huh puh-ree-PAH-luh-yun-taam, NYAH-yay-nuh MAR-gay-nuh muh-HEEM muh-HEE-shah-hah',
        en: 'Om. Svasti prajabhyah paripalayantam, nyayena margena mahim mahishah.',
        meaning: { en: 'Om. May all people be well. May those who lead protect the earth with justice.', vi: 'Om. Nguyện muôn người được an lành. Nguyện những người lãnh đạo gìn giữ trái đất bằng lẽ công bằng.' },
        vi: 'Om. Nguyện muôn người được an lành. Nguyện những người lãnh đạo gìn giữ trái đất bằng lẽ công bằng.',
      },
      {
        id: 'mantra-close-2', part: 'closing', lang: 'sa',
        term: 'go-brāhmaṇebhyaḥ śubham astu nityaṃ\nlokāḥ samastāḥ sukhino bhavantu',
        say: 'GOH BRAH-muh-NAY-bhyuh-huh SHOO-bum US-too NIT-yum, LOH-kah-hah suh-MUS-tah-hah SOO-khee-noh BUH-vun-too',
        en: 'Go brahmanebhyah shubham astu nityam, lokah samastah sukhino bhavantu.',
        meaning: { en: 'May the cows and the wise always be blessed. May all beings in all the worlds be happy.', vi: 'Nguyện loài bò và các bậc hiền trí luôn được phúc lành. Nguyện chúng sinh khắp mọi thế giới đều hạnh phúc.' },
        vi: 'Nguyện loài bò và các bậc hiền trí luôn được phúc lành. Nguyện chúng sinh khắp mọi thế giới đều hạnh phúc.',
      },
      {
        id: 'mantra-close-3', part: 'closing', lang: 'sa',
        term: 'oṃ śāntiḥ śāntiḥ śāntiḥ',
        say: 'OHM, SHAHN-tee-hee, SHAHN-tee-hee, SHAHN-tee-hee',
        en: 'Om, shantih, shantih, shantih.',
        meaning: { en: 'Om, peace, peace, peace.', vi: 'Om, bình an, bình an, bình an.' },
        vi: 'Om, bình an, bình an, bình an.',
      },
    ],
  },
  {
    id: 'pranayama', area: 'class',
    title: { en: 'Pranayama', vi: 'Pranayama: luyện thở' },
    short: { en: 'Pranayama', vi: 'Luyện thở' },
    lead: { en: 'Ujjayi, three-part breath, nadi shodhana, box breathing.', vi: 'Ujjayi, thở ba phần, thở luân phiên hai lỗ mũi, thở hình hộp.' },
    lines: [
      { id: 'pran-1', en: 'Let’s begin with ujjayi breath. Breathe in and out through your nose.', vi: 'Chúng ta bắt đầu với hơi thở ujjayi. Hít vào và thở ra bằng mũi.', say: 'oo-JAH-yee' },
      { id: 'pran-2', en: 'Gently narrow the back of your throat, and listen for a soft ocean sound.', vi: 'Khép nhẹ phía sau cổ họng, và lắng nghe một âm thanh nhẹ như tiếng sóng biển.' },
      { id: 'pran-3', en: 'Three-part breath. Fill the belly, then the ribs, then the chest.', vi: 'Hơi thở ba phần. Thở đầy bụng, rồi đến xương sườn, rồi đến ngực.' },
      { id: 'pran-4', en: 'Exhale from the top down: chest, ribs, belly.', vi: 'Thở ra từ trên xuống: ngực, sườn, bụng.' },
      { id: 'pran-5', en: 'For nadi shodhana, fold your index and middle fingers into your right palm.', vi: 'Để thở nadi shodhana, gập ngón trỏ và ngón giữa vào lòng bàn tay phải.', say: 'NAH-dee SHOH-duh-nuh' },
      { id: 'pran-6', en: 'Close your right nostril with your thumb, and inhale through the left.', vi: 'Dùng ngón cái bịt lỗ mũi phải, và hít vào bằng lỗ mũi trái.' },
      { id: 'pran-7', en: 'Close the left with your ring finger, open the right, and exhale.', vi: 'Dùng ngón áp út bịt lỗ mũi trái, mở lỗ mũi phải, và thở ra.' },
      { id: 'pran-8', en: 'Inhale right, switch, exhale left. That’s one round.', vi: 'Hít vào bên phải, đổi bên, thở ra bên trái. Đó là một vòng.' },
      { id: 'pran-9', en: 'Box breathing: inhale for four, hold for four, exhale for four, hold for four.', vi: 'Thở hình hộp: hít vào đếm bốn, giữ đếm bốn, thở ra đếm bốn, giữ đếm bốn.' },
      { id: 'pran-10', en: 'If holding the breath is uncomfortable, simply leave out the holds.', vi: 'Nếu giữ hơi thấy khó chịu, bạn cứ bỏ qua phần giữ hơi.' },
      { id: 'pran-11', en: 'Let go of the technique, and let the breath be natural again.', vi: 'Buông kỹ thuật, để hơi thở tự nhiên trở lại.' },
    ],
  },
  {
    id: 'savasana', area: 'class', kind: 'script',
    title: { en: 'Savasana', vi: 'Savasana' },
    short: { en: 'Savasana', vi: 'Savasana' },
    lead: { en: 'A full relaxation script, about seven minutes, with its pauses.', vi: 'Kịch bản thư giãn trọn vẹn, khoảng bảy phút, có cả những khoảng lặng.' },
    lines: [
      { id: 'sav-8', en: 'Come down onto your back, and let your feet fall open.', vi: 'Nằm ngửa xuống, để hai bàn chân tự nhiên ngả ra hai bên.', pauseAfter: 8 },
      { id: 'sav-9', en: 'Rest your arms a little away from your body, palms facing up.', vi: 'Đặt hai tay cách thân người một chút, lòng bàn tay ngửa lên.', pauseAfter: 8 },
      { id: 'sav-10', en: 'If your lower back feels tight, slide a bolster under your knees.', vi: 'Nếu lưng dưới thấy căng, đặt một gối tựa dưới đầu gối.', pauseAfter: 10 },
      { id: 'sav-11', en: 'Close your eyes, and let them rest.', vi: 'Nhắm mắt lại, và để đôi mắt nghỉ ngơi.', pauseAfter: 10 },
      { id: 'sav-1', en: 'Let your whole body become heavy.', vi: 'Để toàn bộ cơ thể trở nên nặng.', pauseAfter: 20 },
      { id: 'sav-12', en: 'Feel the floor under the back of your head, your shoulders, your hips, your heels.', vi: 'Cảm nhận mặt sàn dưới sau đầu, dưới hai vai, dưới hông và gót chân.', pauseAfter: 20 },
      { id: 'sav-2', en: 'Soften your jaw. Soften the space between your eyebrows.', vi: 'Thả lỏng hàm. Thả lỏng khoảng giữa hai lông mày.', pauseAfter: 20 },
      { id: 'sav-13', en: 'Let your shoulders melt away from your ears. Let your belly be soft.', vi: 'Để hai vai thả lỏng, rời xa tai. Để bụng mềm ra.', pauseAfter: 20 },
      { id: 'sav-3', en: 'Let the breath return to its natural rhythm.', vi: 'Để hơi thở trở về nhịp tự nhiên của nó.', pauseAfter: 30 },
      { id: 'sav-14', en: 'If thoughts come, let them pass like clouds.', vi: 'Nếu suy nghĩ đến, để chúng trôi qua như những đám mây.', pauseAfter: 40 },
      { id: 'sav-4', en: 'There is nothing left to do.', vi: 'Không còn gì phải làm nữa.', pauseAfter: 45 },
      { id: 'sav-15', en: 'Just rest.', vi: 'Chỉ nghỉ ngơi.', pauseAfter: 60 },
      { id: 'sav-5', en: 'Begin to deepen your breath. Wiggle your fingers and toes.', vi: 'Bắt đầu thở sâu hơn. Cử động nhẹ ngón tay và ngón chân.', pauseAfter: 15 },
      { id: 'sav-16', en: 'Stretch your arms overhead, and take a long stretch through your whole body.', vi: 'Vươn hai tay qua đầu, và duỗi dài toàn bộ cơ thể.', pauseAfter: 10 },
      { id: 'sav-6', en: 'Roll onto your right side and rest there for a moment.', vi: 'Lăn sang bên phải và nghỉ ở đó một lát.', pauseAfter: 15 },
      { id: 'sav-7', en: 'Press yourself up to a comfortable seat.', vi: 'Chống tay ngồi dậy về tư thế ngồi thoải mái.', pauseAfter: 0 },
    ],
  },
  {
    id: 'closing', area: 'class',
    title: { en: 'Closing the class', vi: 'Kết thúc lớp' },
    short: { en: 'Closing', vi: 'Kết lớp' },
    lead: { en: 'Ending the class with gratitude.', vi: 'Kết thúc buổi tập với lòng biết ơn.' },
    lines: [
      { id: 'close-1', en: 'Bring your hands together at your heart.', vi: 'Chắp hai tay trước ngực.' },
      { id: 'close-6', en: 'Take a moment to notice how you feel now.', vi: 'Dành một chút để cảm nhận bạn thấy thế nào lúc này.' },
      { id: 'close-2', en: 'Thank you for practising with me today.', vi: 'Cảm ơn bạn đã tập cùng tôi hôm nay.' },
      { id: 'close-3', en: 'The light in me honours the light in you. Namaste.', vi: 'Ánh sáng trong tôi kính chào ánh sáng trong bạn. Namaste.' },
      { id: 'close-7', en: 'Take this calm with you into the rest of your day.', vi: 'Mang sự bình yên này theo bạn trong suốt phần còn lại của ngày.' },
      { id: 'close-4', en: 'Take your time getting up. See you next week.', vi: 'Cứ từ từ đứng dậy. Hẹn gặp lại tuần sau.' },
      { id: 'close-5', en: 'How did that feel? Any questions before you go?', vi: 'Cảm giác thế nào? Có câu hỏi gì trước khi về không?' },
    ],
  },
  {
    id: 'after-class', area: 'class',
    title: { en: 'After class', vi: 'Sau giờ học' },
    short: { en: 'After class', vi: 'Sau giờ học' },
    lead: { en: 'Chatting with students and answering the usual questions.', vi: 'Trò chuyện với học viên và trả lời những câu hỏi thường gặp.' },
    lines: [
      { id: 'after-1', en: 'How was that for you today?', vi: 'Hôm nay bạn thấy buổi tập thế nào?' },
      { id: 'after-2', en: 'Two or three times a week is a great start. A little, often, is better than a lot, once.', vi: 'Hai hoặc ba buổi mỗi tuần là khởi đầu rất tốt. Tập ít mà đều tốt hơn tập nhiều một lần.' },
      { id: 'after-3', en: 'Tight hamstrings are very common. Bend your knees as much as you need, and they’ll open with time.', vi: 'Cơ đùi sau bị căng là chuyện rất thường gặp. Cứ chùng gối bao nhiêu tuỳ cần, theo thời gian cơ sẽ mềm ra.' },
      { id: 'after-4', en: 'Some muscle soreness tomorrow is normal. Sharp pain or joint pain is not, so tell me if you feel that.', vi: 'Ngày mai hơi mỏi cơ là bình thường. Đau nhói hay đau khớp thì không, nên hãy báo tôi nếu bạn thấy vậy.' },
      { id: 'after-5', en: 'Feeling a little emotional after hip openers is normal too.', vi: 'Cảm thấy xúc động một chút sau các tư thế mở hông cũng là bình thường.' },
      { id: 'after-6', en: 'Sorry, could you say that again, a little more slowly?', vi: 'Xin lỗi, bạn nói lại được không, chậm hơn một chút?' },
      { id: 'after-7', en: 'Good question. I’m not sure, but I’ll find out and tell you next time.', vi: 'Câu hỏi hay. Tôi chưa chắc, nhưng tôi sẽ tìm hiểu và nói với bạn lần sau.' },
      { id: 'after-8', en: 'Drink some water, and take it easy tonight.', vi: 'Uống chút nước, và tối nay nghỉ ngơi nhẹ nhàng nhé.' },
      { id: 'after-9', en: 'Thanks for coming. See you on Thursday!', vi: 'Cảm ơn bạn đã đến. Hẹn gặp bạn vào thứ Năm nhé!' },
    ],
  },
  {
    id: 'meditation', area: 'mind', kind: 'script',
    title: { en: 'A vipassana sit', vi: 'Một buổi ngồi thiền vipassana' },
    short: { en: 'Meditation', vi: 'Thiền' },
    lead: { en: 'About ten minutes you can lead: settling, the breath, noting, the body, mettā.', vi: 'Khoảng mười phút bạn có thể dẫn: lắng xuống, hơi thở, ghi nhận, thân, tâm từ.' },
    lines: [
      { id: 'med-1', en: 'Sit comfortably, with your back straight but not stiff, and gently close your eyes.', vi: 'Ngồi thoải mái, lưng thẳng nhưng không cứng, và nhẹ nhàng nhắm mắt lại.', pauseAfter: 10 },
      { id: 'med-2', en: 'Let the body settle. Let it become still.', vi: 'Để cơ thể lắng xuống. Để nó trở nên tĩnh lặng.', pauseAfter: 20 },
      { id: 'med-3', en: 'Bring your attention to the entrance of the nostrils.', vi: 'Đưa sự chú ý đến vùng cửa mũi.', pauseAfter: 10 },
      { id: 'med-4', en: 'Feel the breath coming in, and the breath going out. Just the natural breath.', vi: 'Cảm nhận hơi thở đi vào, và hơi thở đi ra. Chỉ là hơi thở tự nhiên.', pauseAfter: 30 },
      { id: 'med-5', en: 'Don’t control it. Long or short, simply know it as it is.', vi: 'Đừng điều khiển hơi thở. Dài hay ngắn, chỉ cần biết nó đúng như nó là.', pauseAfter: 45 },
      { id: 'med-6', en: 'Notice the touch of the breath below the nostrils, above the upper lip.', vi: 'Để ý sự chạm của hơi thở ở vùng dưới lỗ mũi, phía trên môi trên.', pauseAfter: 45 },
      { id: 'med-7', en: 'If the mind wanders, that’s fine. Gently note “thinking”, and come back to the breath.', vi: 'Nếu tâm đi lang thang, không sao cả. Nhẹ nhàng ghi nhận “suy nghĩ”, rồi quay về hơi thở.', pauseAfter: 45 },
      { id: 'med-8', en: 'Note whatever takes you away: hearing, planning, remembering. Then return.', vi: 'Ghi nhận bất cứ điều gì kéo bạn đi: nghe, lên kế hoạch, nhớ lại. Rồi quay về.', pauseAfter: 60 },
      { id: 'med-9', en: 'There’s no need to be frustrated. Every return is the practice.', vi: 'Không cần bực bội. Mỗi lần quay về chính là sự thực tập.', pauseAfter: 60 },
      { id: 'med-10', en: 'Now move your attention to the top of your head. Feel any sensation there.', vi: 'Bây giờ đưa sự chú ý lên đỉnh đầu. Cảm nhận bất kỳ cảm giác nào ở đó.', pauseAfter: 20 },
      { id: 'med-11', en: 'Slowly move down: the face, the neck, the shoulders, the arms and hands.', vi: 'Từ từ đi xuống: gương mặt, cổ, vai, cánh tay và bàn tay.', pauseAfter: 45 },
      { id: 'med-12', en: 'The chest, the back, the belly. The hips, the legs, the feet.', vi: 'Ngực, lưng, bụng. Hông, chân, bàn chân.', pauseAfter: 45 },
      { id: 'med-13', en: 'Warmth, tingling, pressure, or no sensation at all. Just observe.', vi: 'Ấm, rần rần, áp lực, hay không có cảm giác gì. Chỉ quan sát.', pauseAfter: 30 },
      { id: 'med-14', en: 'Pleasant or unpleasant, every sensation changes. Watch it with a calm, balanced mind.', vi: 'Dễ chịu hay khó chịu, mọi cảm giác đều thay đổi. Quan sát nó với một tâm bình thản, quân bình.', pauseAfter: 60 },
      { id: 'med-15', en: 'Now let go of the technique, and let a feeling of goodwill fill the body.', vi: 'Bây giờ buông kỹ thuật, để cảm giác thiện lành lan toả khắp cơ thể.', pauseAfter: 15 },
      { id: 'med-16', en: 'May I be happy and peaceful. May all beings be happy.', vi: 'Nguyện cho tôi được an vui, bình yên. Nguyện cho tất cả chúng sinh được hạnh phúc.', pauseAfter: 20 },
      { id: 'med-17', en: 'Take a moment before you move. Then slowly open your eyes.', vi: 'Dành một chút trước khi cử động. Rồi từ từ mở mắt.', pauseAfter: 0 },
    ],
  },
  {
    id: 'philosophy-in-class', area: 'mind',
    title: { en: 'Philosophy in class', vi: 'Triết lý trong lớp' },
    short: { en: 'Philosophy', vi: 'Triết lý' },
    lead: { en: 'One-line ideas for a class theme.', vi: 'Những ý một câu cho chủ đề buổi tập.' },
    lines: [
      { id: 'phil-2', en: 'The eight limbs are yama, niyama, asana, pranayama, pratyahara, dharana, dhyana and samadhi.', vi: 'Tám nhánh là yama, niyama, asana, pranayama, pratyahara, dharana, dhyana và samadhi.', say: 'YUH-muh, nee-YUH-muh, AH-suh-nuh, PRAH-nah-YAH-muh, pruh-tyah-HAH-ruh, DAH-ruh-nah, DYAH-nuh, suh-MAH-dee' },
      { id: 'phil-3', en: 'Patanjali defines yoga as the stilling of the movements of the mind.', vi: 'Patanjali định nghĩa yoga là làm lắng dịu những dao động của tâm.', say: 'puh-TUN-juh-lee' },
      { id: 'phil-4', en: 'Our theme today is ahimsa, non-harming. Let it begin with how you treat your own body.', vi: 'Chủ đề hôm nay là ahimsa, không gây hại. Hãy bắt đầu từ cách bạn đối xử với chính cơ thể mình.' },
      { id: 'phil-5', en: 'Today’s theme is santosha, contentment. Can you be happy with the pose you have today?', vi: 'Chủ đề hôm nay là santosha, sự hài lòng. Bạn có thể vui với tư thế mình có hôm nay không?' },
      { id: 'phil-6', en: 'Yoga is not about the shape. It’s about how you meet yourself in the shape.', vi: 'Yoga không nằm ở hình dáng tư thế. Mà ở cách bạn gặp chính mình trong tư thế đó.' },
      { id: 'phil-7', en: 'Patanjali says a pose should be sthira and sukha: steady and easy.', vi: 'Patanjali nói tư thế cần sthira và sukha: vững vàng và thoải mái.', say: 'STEE-ruh, SOO-kuh' },
      { id: 'phil-8', en: 'Where the eyes go, the mind follows. That’s why we use a drishti.', vi: 'Mắt nhìn đâu, tâm theo đó. Vì vậy chúng ta dùng một điểm nhìn, drishti.' },
      { id: 'phil-9', en: 'Mula bandha is a light lift of the pelvic floor that supports the spine from below.', vi: 'Mula bandha là sự nâng nhẹ cơ sàn chậu, nâng đỡ cột sống từ bên dưới.' },
      { id: 'phil-10', en: 'Uddiyana bandha draws the lower belly in and up, and makes the body feel lighter.', vi: 'Uddiyana bandha hóp bụng dưới vào và lên, giúp cơ thể thấy nhẹ hơn.', say: 'oo-dee-YAH-nuh' },
      { id: 'phil-11', en: 'Jalandhara bandha is the chin lock, used mainly when holding the breath in pranayama.', vi: 'Jalandhara bandha là khoá cằm, chủ yếu dùng khi giữ hơi trong luyện thở.', say: 'JAH-lun-duh-ruh' },
      { id: 'phil-12', en: 'As Pattabhi Jois said: practise, and all is coming.', vi: 'Như thầy Pattabhi Jois từng nói: cứ tập, rồi mọi điều sẽ đến.', say: 'puh-TAH-bee JOYCE' },
    ],
  },
  {
    id: 'sanskrit-terms', area: 'mind', kind: 'concepts',
    title: { en: 'Sanskrit words', vi: 'Từ Sanskrit' },
    short: { en: 'Sanskrit', vi: 'Sanskrit' },
    lead: { en: 'The yoga words, with the Vietnamese you may already know.', vi: 'Những từ yoga, kèm từ tiếng Việt bạn có thể đã biết.' },
    lines: [
      {
        id: 'sa-asana', kind: 'concept', term: 'āsana', lang: 'sa', say: 'AH-suh-nuh', en: 'asana', vi: 'tư thế',
        meaning: { en: 'A posture. Patañjali calls it a seat that is steady and easy.', vi: 'Tư thế. Patañjali gọi đó là thế ngồi vững vàng và dễ chịu.' },
        bridge: null,
        inClass: { en: 'In every asana, look for both effort and ease.', vi: 'Trong mỗi tư thế, hãy tìm cả sự nỗ lực lẫn sự thoải mái.' },
      },
      {
        id: 'sa-pranayama', kind: 'concept', term: 'prāṇāyāma', lang: 'sa', say: 'PRAH-nah-YAH-muh', en: 'pranayama', vi: 'luyện thở',
        meaning: { en: 'Breath practice: prāṇa, life energy, and āyāma, to extend and guide it.', vi: 'Luyện thở: prāṇa là năng lượng sống, āyāma là kéo dài và dẫn dắt nó.' },
        bridge: null,
        inClass: { en: 'Now we’ll take a few minutes of pranayama, simple breathing practice.', vi: 'Bây giờ chúng ta dành vài phút cho pranayama, những bài tập thở đơn giản.' },
      },
      {
        id: 'sa-drishti', kind: 'concept', term: 'dṛṣṭi', lang: 'sa', say: 'DRISH-tee', en: 'drishti', vi: 'điểm nhìn',
        meaning: { en: 'Gaze: a still point for the eyes, so the mind gathers too.', vi: 'Điểm nhìn: một điểm tĩnh cho mắt, để tâm cũng tập trung lại.' },
        bridge: null,
        inClass: { en: 'Find your drishti, a still point to rest your eyes on.', vi: 'Tìm điểm nhìn của bạn, một điểm tĩnh để mắt dừng lại.' },
      },
      {
        id: 'sa-bandha', kind: 'concept', term: 'bandha', lang: 'sa', say: 'BUN-duh', en: 'bandha', vi: 'khoá năng lượng',
        meaning: { en: 'A lock: a gentle engagement that holds and directs energy in the body.', vi: 'Khoá: một sự siết nhẹ để giữ và dẫn năng lượng trong cơ thể.' },
        bridge: null,
        inClass: { en: 'Engage your bandhas gently. Not a squeeze, just a lift.', vi: 'Nhẹ nhàng giữ các khoá bandha. Không phải siết chặt, chỉ là nâng lên.' },
      },
      {
        id: 'sa-mula-bandha', kind: 'concept', term: 'mūla bandha', lang: 'sa', say: 'MOO-luh BUN-duh', en: 'mula bandha', vi: 'khoá gốc',
        meaning: { en: 'The root lock: a light lift of the pelvic floor.', vi: 'Khoá gốc: nâng nhẹ cơ sàn chậu.' },
        bridge: null,
        inClass: { en: 'Gently lift the pelvic floor. That is mula bandha.', vi: 'Nhẹ nhàng nâng cơ sàn chậu lên. Đó là mula bandha.' },
      },
      {
        id: 'sa-uddiyana-bandha', kind: 'concept', term: 'uḍḍīyāna bandha', lang: 'sa', say: 'oo-dee-YAH-nuh BUN-duh', en: 'uddiyana bandha', vi: 'khoá bụng',
        meaning: { en: 'The upward-flying lock: drawing the lower belly in and up.', vi: 'Khoá bay lên: hóp bụng dưới vào trong và lên trên.' },
        bridge: null,
        inClass: { en: 'Draw your lower belly in and up, just below the navel.', vi: 'Hóp nhẹ bụng dưới vào và lên, ngay dưới rốn.' },
      },
      {
        id: 'sa-jalandhara-bandha', kind: 'concept', term: 'jālandhara bandha', lang: 'sa', say: 'JAH-lun-duh-ruh BUN-duh', en: 'jalandhara bandha', vi: 'khoá cằm',
        meaning: { en: 'The throat lock: the chin draws down toward the chest.', vi: 'Khoá cổ họng: cằm hạ về phía ngực.' },
        bridge: null,
        inClass: { en: 'Lengthen the back of your neck, and draw your chin toward your chest.', vi: 'Kéo dài sau gáy, và hạ cằm về phía ngực.' },
      },
      {
        id: 'sa-vinyasa', kind: 'concept', term: 'vinyāsa', lang: 'sa', say: 'vin-YAH-suh', en: 'vinyasa', vi: 'chuỗi động tác theo hơi thở',
        meaning: { en: 'Placing in a special way: each movement linked to a breath.', vi: 'Sắp đặt theo cách đặc biệt: mỗi chuyển động gắn với một hơi thở.' },
        bridge: null,
        inClass: { en: 'One breath, one movement. That is vinyasa.', vi: 'Một hơi thở, một chuyển động. Đó là vinyasa.' },
      },
      {
        id: 'sa-ujjayi', kind: 'concept', term: 'ujjāyī', lang: 'sa', say: 'oo-JAH-yee', en: 'ujjayi', vi: 'hơi thở chiến thắng',
        meaning: { en: 'The victorious breath: a soft sound in the throat, like the sea.', vi: 'Hơi thở chiến thắng: một âm thanh nhẹ nơi cổ họng, như tiếng sóng biển.' },
        bridge: null,
        inClass: { en: 'Breathe through your nose, with a soft ocean sound in your throat.', vi: 'Thở bằng mũi, với một âm thanh nhẹ như tiếng sóng nơi cổ họng.' },
      },
      {
        id: 'sa-ashtanga', kind: 'concept', term: 'aṣṭāṅga', lang: 'sa', say: 'ush-TAHNG-guh', en: 'ashtanga', vi: 'tám nhánh của yoga',
        meaning: { en: 'The eight limbs of Patañjali’s yoga: yama, niyama, āsana, prāṇāyāma, pratyāhāra (drawing the senses in), dhāraṇā (concentration), dhyāna, samādhi.', vi: 'Tám nhánh yoga của Patañjali: yama, niyama, āsana, prāṇāyāma, pratyāhāra (thu nhiếp giác quan), dhāraṇā (tập trung), dhyāna (thiền), samādhi (định).' },
        bridge: null,
        inClass: { en: 'Yoga has eight limbs, and the poses are only one of them.', vi: 'Yoga có tám nhánh, và các tư thế chỉ là một trong số đó.' },
      },
      {
        id: 'sa-yama', kind: 'concept', term: 'yama', lang: 'sa', say: 'YUH-muh', en: 'yama', vi: 'điều tiết chế',
        meaning: { en: 'Restraints: five ways of living kindly with others. The first limb.', vi: 'Những điều tiết chế: năm cách sống tử tế với người khác. Nhánh thứ nhất.' },
        bridge: { term: 'ngũ giới', near: true, note: { en: 'Four of the five yamas match the five precepts: not killing, not stealing, no sexual misconduct, not lying. The fifth differs: aparigraha, not grasping, where the precepts have no intoxicants.', vi: 'Bốn trong năm yama trùng với ngũ giới: không sát sinh, không trộm cắp, không tà dâm, không nói dối. Điều thứ năm khác: aparigraha, không chiếm hữu, thay cho không say nghiện.' } },
        source: 'https://vi.wikipedia.org/wiki/Ngũ_giới',
        inClass: { en: 'The first limb is yama: how we treat others, on the mat and off it.', vi: 'Nhánh đầu tiên là yama: cách chúng ta đối xử với người khác, trên thảm và ngoài đời.' },
      },
      {
        id: 'sa-ahimsa', kind: 'concept', term: 'ahiṃsā', lang: 'sa', say: 'uh-HIM-sah', en: 'ahimsa', vi: 'bất hại',
        meaning: { en: 'Non-harming, in action, word and thought, including toward yourself.', vi: 'Không gây hại, trong hành động, lời nói và suy nghĩ, kể cả với chính mình.' },
        bridge: { term: 'bất hại', note: { en: 'The same word in Buddhism; also bất sát sinh, the first precept.', vi: 'Cùng một từ trong Phật giáo; cũng là bất sát sinh, giới thứ nhất.' } },
        source: 'https://vi.wikipedia.org/wiki/Ahimsa',
        inClass: { en: 'Ahimsa in this pose: stay at your edge, not past it.', vi: 'Ahimsa trong tư thế này: ở tại ngưỡng của bạn, đừng vượt qua nó.' },
      },
      {
        id: 'sa-satya', kind: 'concept', term: 'satya', lang: 'sa', say: 'SUT-yuh', en: 'satya', vi: 'chân thật',
        meaning: { en: 'Truthfulness.', vi: 'Sự chân thật.' },
        bridge: { term: 'không nói dối', near: true, note: { en: 'The fourth of the five precepts (ngũ giới): not lying.', vi: 'Giới thứ tư trong ngũ giới: không nói dối.' } },
        source: 'https://vi.wikipedia.org/wiki/Ngũ_giới',
        inClass: { en: 'Satya means being honest with yourself about how your body feels today.', vi: 'Satya là thành thật với chính mình về cảm giác của cơ thể hôm nay.' },
      },
      {
        id: 'sa-asteya', kind: 'concept', term: 'asteya', lang: 'sa', say: 'us-TAY-yuh', en: 'asteya', vi: 'không trộm cắp',
        meaning: { en: 'Non-stealing: not taking what is not given, including time and energy.', vi: 'Không trộm cắp: không lấy những gì không được trao, kể cả thời gian và sức lực.' },
        bridge: { term: 'không trộm cắp', near: true, note: { en: 'The second of the five precepts (ngũ giới).', vi: 'Giới thứ hai trong ngũ giới.' } },
        source: 'https://vi.wikipedia.org/wiki/Ngũ_giới',
        inClass: { en: 'Asteya: don’t take more from your body than it can give today.', vi: 'Asteya: đừng lấy từ cơ thể nhiều hơn những gì nó có thể cho hôm nay.' },
      },
      {
        id: 'sa-brahmacharya', kind: 'concept', term: 'brahmacarya', lang: 'sa', say: 'BRUH-muh-CHAR-yuh', en: 'brahmacharya', vi: 'tiết độ',
        meaning: { en: 'Wise use of energy, moderation. Traditionally, celibacy.', vi: 'Dùng năng lượng một cách khôn ngoan, sự tiết độ. Theo truyền thống là sống thanh tịnh, tiết dục.' },
        bridge: { term: 'phạm hạnh', note: { en: 'The same word in Pali, brahmacariya: phạm hạnh, the pure life.', vi: 'Cùng một từ trong tiếng Pali, brahmacariya: phạm hạnh, đời sống thanh tịnh.' } },
        source: 'https://www.niemphat.vn/downloads/dai-tang-kinh/kinh-nam-tong/kinh-phap-hanh-ht-thien-chau-dich.doc',
        inClass: { en: 'Brahmacharya on the mat: use the energy you need, and keep the rest.', vi: 'Brahmacharya trên thảm: dùng đủ năng lượng cần thiết, và giữ lại phần còn lại.' },
      },
      {
        id: 'sa-aparigraha', kind: 'concept', term: 'aparigraha', lang: 'sa', say: 'uh-puh-ree-GRUH-huh', en: 'aparigraha', vi: 'không chiếm hữu',
        meaning: { en: 'Non-grasping: holding things lightly, without clinging.', vi: 'Không nắm giữ: cầm mọi thứ thật nhẹ, không bám víu.' },
        bridge: null,
        inClass: { en: 'Aparigraha: let go of how the pose looked last week.', vi: 'Aparigraha: buông bỏ hình ảnh tư thế của tuần trước.' },
      },
      {
        id: 'sa-niyama', kind: 'concept', term: 'niyama', lang: 'sa', say: 'nee-YUH-muh', en: 'niyama', vi: 'điều nên giữ',
        meaning: { en: 'Observances: five practices of caring for yourself. The second limb.', vi: 'Những điều nên giữ: năm thực hành chăm sóc chính mình. Nhánh thứ hai.' },
        bridge: null,
        inClass: { en: 'The niyamas turn the practice inward, to how we treat ourselves.', vi: 'Các niyama đưa việc tập hướng vào trong, vào cách chúng ta đối xử với chính mình.' },
      },
      {
        id: 'sa-saucha', kind: 'concept', term: 'śauca', lang: 'sa', say: 'SHOW-chuh', en: 'saucha', vi: 'sự trong sạch',
        meaning: { en: 'Cleanliness and clarity, of body and mind.', vi: 'Sự sạch sẽ và trong sáng, của thân và tâm.' },
        bridge: null,
        inClass: { en: 'Saucha: a clean mat, and a clear mind.', vi: 'Saucha: tấm thảm sạch, và tâm trí trong.' },
      },
      {
        id: 'sa-santosha', kind: 'concept', term: 'santoṣa', lang: 'sa', say: 'sun-TOH-shuh', en: 'santosha', vi: 'sự hài lòng',
        meaning: { en: 'Contentment: being at peace with what is here today.', vi: 'Sự hài lòng: bình an với những gì đang có hôm nay.' },
        bridge: { term: 'tri túc', near: true, note: { en: 'Tri túc: knowing you have enough, as in thiểu dục tri túc.', vi: 'Tri túc: biết đủ, như trong thiểu dục tri túc.' } },
        source: 'https://web.plumvillage.app/th/item/you-have-enough',
        inClass: { en: 'Notice what already feels good in this pose. That is santosha.', vi: 'Nhận ra điều đã thấy dễ chịu trong tư thế này. Đó là santosha.' },
      },
      {
        id: 'sa-tapas', kind: 'concept', term: 'tapas', lang: 'sa', say: 'TUH-pus', en: 'tapas', vi: 'sự bền bỉ',
        meaning: { en: 'Heat and discipline: the steady effort that changes us.', vi: 'Sức nóng và kỷ luật: nỗ lực bền bỉ làm chúng ta thay đổi.' },
        bridge: null,
        inClass: { en: 'Tapas is the heat of steady practice. Stay one more breath.', vi: 'Tapas là sức nóng của sự tập luyện bền bỉ. Ở lại thêm một hơi thở.' },
      },
      {
        id: 'sa-svadhyaya', kind: 'concept', term: 'svādhyāya', lang: 'sa', say: 'svahd-YAH-yuh', en: 'svadhyaya', vi: 'tự học, tự quán',
        meaning: { en: 'Self-study: reading wise texts, and watching yourself honestly.', vi: 'Tự học: đọc sách của bậc hiền trí, và quan sát bản thân một cách trung thực.' },
        bridge: null,
        inClass: { en: 'Svadhyaya: notice your habits in this pose, without judging them.', vi: 'Svadhyaya: nhận ra thói quen của bạn trong tư thế này, mà không phán xét.' },
      },
      {
        id: 'sa-ishvara-pranidhana', kind: 'concept', term: 'īśvara praṇidhāna', lang: 'sa', say: 'EESH-vuh-ruh pruh-nee-DAH-nuh', en: 'ishvara pranidhana', vi: 'buông xả, dâng hiến',
        meaning: { en: 'Surrender to something larger than yourself; offering the practice.', vi: 'Quy thuận điều lớn hơn bản thân; dâng hiến việc tập.' },
        bridge: null,
        inClass: { en: 'Ishvara pranidhana: do your best, then let go of the result.', vi: 'Ishvara pranidhana: làm hết sức mình, rồi buông bỏ kết quả.' },
      },
      {
        id: 'sa-dhyana', kind: 'concept', term: 'dhyāna', lang: 'sa', say: 'DYAH-nuh', en: 'dhyana', vi: 'thiền',
        meaning: { en: 'Meditation: unbroken attention. The seventh limb.', vi: 'Thiền: sự chú tâm liên tục. Nhánh thứ bảy.' },
        bridge: { term: 'thiền', note: { en: 'Thiền (禪) comes from dhyāna, through the old transliteration thiền-na. Zen is the same word.', vi: 'Chữ thiền (禪) bắt nguồn từ dhyāna, qua phiên âm cũ thiền-na. Zen cũng là chữ này.' } },
        source: 'https://vi.wikipedia.org/wiki/Thiền_tông',
        inClass: { en: 'Dhyana is meditation: attention that rests without effort.', vi: 'Dhyana là thiền: sự chú tâm an trú mà không cần gắng sức.' },
      },
      {
        id: 'sa-samadhi', kind: 'concept', term: 'samādhi', lang: 'sa', say: 'suh-MAH-dee', en: 'samadhi', vi: 'định',
        meaning: { en: 'Absorption: the mind fully one with its object. The eighth limb.', vi: 'Định: tâm hoàn toàn hợp nhất với đối tượng. Nhánh thứ tám.' },
        bridge: { term: 'định', note: { en: 'Định, also tam-muội: the same word as in Buddhism.', vi: 'Định, còn gọi là tam-muội: cùng một từ như trong Phật giáo.' } },
        source: 'https://vi.wikipedia.org/wiki/Tam_học',
        inClass: { en: 'Samadhi is the last of the eight limbs. We don’t chase it; we prepare for it.', vi: 'Samadhi là nhánh cuối cùng trong tám nhánh. Ta không đuổi theo nó; ta chuẩn bị cho nó.' },
      },
      {
        id: 'sa-chakra', kind: 'concept', term: 'cakra', lang: 'sa', say: 'CHUK-ruh', en: 'chakra', vi: 'luân xa',
        meaning: { en: 'Wheel: an energy centre along the spine, in yogic and tantric teaching.', vi: 'Bánh xe: một trung tâm năng lượng dọc cột sống, theo giáo lý yoga và mật tông.' },
        bridge: { term: 'luân xa', note: { en: 'Luân xa means wheel, like cakra itself.', vi: 'Luân xa nghĩa là bánh xe, đúng như chữ cakra.' } },
        source: 'https://vi.wikipedia.org/wiki/Luân_xa',
        inClass: { en: 'Bring your attention to the heart centre, the heart chakra.', vi: 'Đưa sự chú ý về trung tâm ngực, luân xa tim.' },
      },
      {
        id: 'sa-mudra', kind: 'concept', term: 'mudrā', lang: 'sa', say: 'MOO-drah', en: 'mudra', vi: 'ấn',
        meaning: { en: 'A seal: a gesture, usually of the hands, that shapes attention.', vi: 'Ấn: một cử chỉ, thường của bàn tay, giúp định hướng sự chú ý.' },
        bridge: { term: 'ấn', note: { en: 'The same word as the ấn of Buddha statues; also ấn tướng.', vi: 'Cùng một từ như ấn trên tượng Phật; còn gọi là ấn tướng.' } },
        source: 'https://vi.wikipedia.org/wiki/Ấn_(Phật_giáo)',
        inClass: { en: 'Rest your hands in chin mudra, thumb and index finger touching.', vi: 'Đặt tay ở chin mudra, ngón cái và ngón trỏ chạm nhau.' },
      },
      {
        id: 'sa-mantra', kind: 'concept', term: 'mantra', lang: 'sa', say: 'MUN-truh', en: 'mantra', vi: 'chân ngôn',
        meaning: { en: 'A sacred sound or phrase, repeated to steady the mind.', vi: 'Một âm hay một câu thiêng liêng, được lặp lại để giữ tâm vững.' },
        bridge: { term: 'chân ngôn', note: { en: 'Chân ngôn (真言), also thần chú.', vi: 'Chân ngôn (真言), còn gọi là thần chú.' } },
        source: 'https://vi.wikipedia.org/wiki/Chân_ngôn',
        inClass: { en: 'We’ll begin with a short mantra. Listen first, then join in if you like.', vi: 'Chúng ta bắt đầu bằng một câu chân ngôn ngắn. Hãy nghe trước, rồi cùng đọc nếu bạn muốn.' },
      },
      {
        id: 'sa-om', kind: 'concept', term: 'oṃ', lang: 'sa', say: 'OHM (ah-oo-mm)', en: 'om', vi: 'Om',
        meaning: { en: 'The first sound: three sounds, A, U, M, and the silence after them.', vi: 'Âm thanh nguyên sơ: ba âm A, U, M, và khoảng lặng sau đó.' },
        bridge: { term: 'Án', note: { en: 'Vietnamese chants write oṃ as Án, as in Án ma ni bát di hồng (oṃ maṇi padme hūṃ).', vi: 'Kinh chú tiếng Việt ghi oṃ là Án, như trong Án ma ni bát di hồng (oṃ maṇi padme hūṃ).' } },
        source: 'https://znews.vn/an-ma-ni-bat-di-hong-co-y-nghia-gi-post1628601.html',
        inClass: { en: 'Let’s chant one Om together. Breathe in, and Om.', vi: 'Cùng nhau xướng một tiếng Om. Hít vào, và Om.' },
      },
      {
        id: 'sa-namaste', kind: 'concept', term: 'namaste', lang: 'sa', say: 'NUH-muh-stay', en: 'namaste', vi: 'kính chào',
        meaning: { en: 'I bow to you: a greeting of respect, hands together at the heart.', vi: 'Tôi cúi chào bạn: lời chào kính trọng, hai tay chắp trước ngực.' },
        bridge: null,
        inClass: { en: 'Namaste. Thank you for your practice.', vi: 'Namaste. Cảm ơn buổi tập của bạn.' },
      },
      {
        id: 'sa-shanti', kind: 'concept', term: 'śānti', lang: 'sa', say: 'SHAHN-tee', en: 'shanti', vi: 'bình an',
        meaning: { en: 'Peace. Often chanted three times at the end of a mantra.', vi: 'Bình an. Thường được xướng ba lần ở cuối một câu chân ngôn.' },
        bridge: null,
        inClass: { en: 'Om, shanti, shanti, shanti. Peace, peace, peace.', vi: 'Om, shanti, shanti, shanti. Bình an, bình an, bình an.' },
      },
      {
        id: 'sa-sthira', kind: 'concept', term: 'sthira', lang: 'sa', say: 'STEE-ruh', en: 'sthira', vi: 'vững vàng',
        meaning: { en: 'Steady, firm, alert.', vi: 'Vững vàng, chắc chắn, tỉnh táo.' },
        bridge: null,
        inClass: { en: 'Find sthira: steady legs, a strong foundation.', vi: 'Tìm sthira: đôi chân vững, nền móng chắc.' },
      },
      {
        id: 'sa-sukha', kind: 'concept', term: 'sukha', lang: 'sa', say: 'SOO-kuh', en: 'sukha', vi: 'thoải mái, an vui',
        meaning: { en: 'Ease, comfort, happiness. With sthira, what Patañjali asks of a pose.', vi: 'Sự thoải mái, dễ chịu, an vui. Cùng với sthira, là điều Patañjali đòi hỏi ở một tư thế.' },
        bridge: null,
        inClass: { en: 'And sukha: a soft face and an easy breath.', vi: 'Và sukha: gương mặt mềm và hơi thở nhẹ.' },
      },
      {
        id: 'sa-prana', kind: 'concept', term: 'prāṇa', lang: 'sa', say: 'PRAH-nuh', en: 'prana', vi: 'năng lượng sống',
        meaning: { en: 'Life energy, carried by the breath.', vi: 'Năng lượng sống, được hơi thở mang đi.' },
        bridge: null,
        inClass: { en: 'Feel the prana, the life energy, moving with each breath.', vi: 'Cảm nhận prana, năng lượng sống, chuyển động theo mỗi hơi thở.' },
      },
      {
        id: 'sa-nadi', kind: 'concept', term: 'nāḍī', lang: 'sa', say: 'NAH-dee', en: 'nadi', vi: 'kênh năng lượng',
        meaning: { en: 'A channel for prāṇa: iḍā on the left, piṅgalā on the right, suṣumnā in the centre.', vi: 'Kênh dẫn prāṇa: iḍā bên trái, piṅgalā bên phải, suṣumnā ở giữa.' },
        bridge: null,
        inClass: { en: 'Alternate nostril breathing is nadi shodhana: clearing the channels.', vi: 'Thở luân phiên hai lỗ mũi gọi là nadi shodhana: làm thông các kênh năng lượng.' },
      },
    ],
  },
  {
    id: 'pali-terms', area: 'mind', kind: 'concepts',
    title: { en: 'Pali words for vipassana', vi: 'Từ Pali trong thiền vipassana' },
    short: { en: 'Pali', vi: 'Pali' },
    lead: { en: 'The vipassana words, starting from the Buddhism you already know.', vi: 'Những từ của thiền vipassana, bắt đầu từ Phật giáo bạn đã biết.' },
    lines: [
      {
        id: 'pi-anicca', kind: 'concept', term: 'anicca', lang: 'pi', say: 'uh-NICH-chuh', en: 'anicca', vi: 'vô thường',
        meaning: { en: 'Impermanence: everything that arises passes away.', vi: 'Vô thường: mọi thứ sinh ra đều sẽ diệt.' },
        bridge: { term: 'vô thường', note: { en: 'The first of the three marks. Sanskrit anitya.', vi: 'Dấu ấn đầu tiên trong ba pháp ấn. Tiếng Phạn: anitya.' } },
        source: 'https://vi.wikipedia.org/wiki/Vô_thường',
        inClass: { en: 'Every sensation arises and passes away. Anicca.', vi: 'Mọi cảm giác đều sinh rồi diệt. Anicca, vô thường.' },
      },
      {
        id: 'pi-dukkha', kind: 'concept', term: 'dukkha', lang: 'pi', say: 'DOOK-khuh', en: 'dukkha', vi: 'khổ',
        meaning: { en: 'Unsatisfactoriness: nothing that changes can fully satisfy.', vi: 'Khổ: không có gì thay đổi mà có thể làm ta thoả mãn trọn vẹn.' },
        bridge: { term: 'khổ', note: { en: 'The first noble truth, khổ đế. Sanskrit duḥkha.', vi: 'Chân lý đầu tiên, khổ đế. Tiếng Phạn: duḥkha.' } },
        source: 'https://vi.wikipedia.org/wiki/Khổ_(Phật_giáo)',
        inClass: { en: 'When we cling to what changes, dukkha follows.', vi: 'Khi ta bám víu vào những gì thay đổi, khổ theo sau.' },
      },
      {
        id: 'pi-anatta', kind: 'concept', term: 'anattā', lang: 'pi', say: 'uh-NUT-tah', en: 'anattā', vi: 'vô ngã',
        meaning: { en: 'Non-self: no fixed, separate self is found in body or mind.', vi: 'Vô ngã: không tìm thấy một cái tôi cố định, tách biệt nào trong thân hay tâm.' },
        bridge: { term: 'vô ngã', note: { en: 'The third mark. Sanskrit anātman.', vi: 'Dấu ấn thứ ba. Tiếng Phạn: anātman.' } },
        source: 'https://vi.wikipedia.org/wiki/Vô_ngã',
        inClass: { en: 'This sensation is not me, not mine. It is just sensation.', vi: 'Cảm giác này không phải tôi, không phải của tôi. Nó chỉ là cảm giác.' },
      },
      {
        id: 'pi-sila', kind: 'concept', term: 'sīla', lang: 'pi', say: 'SEE-luh', en: 'sīla', vi: 'giới',
        meaning: { en: 'Moral conduct: living without harm, in body and speech.', vi: 'Giới: sống không gây hại, bằng thân và lời nói.' },
        bridge: { term: 'giới', note: { en: 'The first of the three trainings: giới, định, tuệ.', vi: 'Môn học đầu tiên trong tam học: giới, định, tuệ.' } },
        source: 'https://vi.wikipedia.org/wiki/Tam_học',
        inClass: { en: 'Sila, kind and honest action, is the ground of meditation.', vi: 'Giới, hành động tử tế và chân thật, là nền tảng của thiền.' },
      },
      {
        id: 'pi-samadhi', kind: 'concept', term: 'samādhi', lang: 'pi', say: 'suh-MAH-dee', en: 'samādhi', vi: 'định',
        meaning: { en: 'Concentration: the mind gathered and steady on one object.', vi: 'Định: tâm thu nhiếp và vững trên một đối tượng.' },
        bridge: { term: 'định', note: { en: 'The second of the three trainings. Also tam-muội.', vi: 'Môn học thứ hai trong tam học. Còn gọi là tam-muội.' } },
        source: 'https://vi.wikipedia.org/wiki/Tam_học',
        inClass: { en: 'Each time you return to the breath, samadhi grows a little stronger.', vi: 'Mỗi lần bạn quay về hơi thở, định lại mạnh thêm một chút.' },
      },
      {
        id: 'pi-panna', kind: 'concept', term: 'paññā', lang: 'pi', say: 'PUN-nyah', en: 'paññā', vi: 'tuệ',
        meaning: { en: 'Wisdom: seeing directly how things really are.', vi: 'Tuệ: thấy trực tiếp bản chất thật của sự vật.' },
        bridge: { term: 'tuệ (bát-nhã)', note: { en: 'The third training, tuệ or huệ. Sanskrit prajñā, written bát-nhã, as in the Heart Sutra.', vi: 'Môn học thứ ba, tuệ hay huệ. Tiếng Phạn prajñā, phiên âm bát-nhã, như trong Bát-nhã Tâm kinh.' } },
        source: 'https://vi.wikipedia.org/wiki/Bát-nhã',
        inClass: { en: 'Panna is not something we think. It is something we see for ourselves.', vi: 'Tuệ không phải điều ta nghĩ ra. Đó là điều ta tự mình thấy.' },
      },
      {
        id: 'pi-metta', kind: 'concept', term: 'mettā', lang: 'pi', say: 'MET-tah', en: 'mettā', vi: 'tâm từ',
        meaning: { en: 'Loving-kindness: a warm wish for all beings to be happy.', vi: 'Tâm từ: lời chúc ấm áp cho tất cả chúng sinh được hạnh phúc.' },
        bridge: { term: 'từ', note: { en: 'The first of the four immeasurables: từ, bi, hỷ, xả. Sanskrit maitrī.', vi: 'Tâm đầu tiên trong tứ vô lượng tâm: từ, bi, hỷ, xả. Tiếng Phạn: maitrī.' } },
        source: 'https://vi.wikipedia.org/wiki/Tứ_vô_lượng_tâm',
        inClass: { en: 'Let’s close with metta. May all beings be happy.', vi: 'Cùng kết thúc bằng tâm từ. Nguyện cho tất cả chúng sinh được hạnh phúc.' },
      },
      {
        id: 'pi-karuna', kind: 'concept', term: 'karuṇā', lang: 'pi', say: 'kuh-ROO-nah', en: 'karuṇā', vi: 'lòng bi',
        meaning: { en: 'Compassion: the wish that beings be free from suffering.', vi: 'Lòng bi: mong cho chúng sinh thoát khỏi khổ đau.' },
        bridge: { term: 'bi', note: { en: 'The second immeasurable. Từ bi is mettā and karuṇā together.', vi: 'Tâm vô lượng thứ hai. Từ bi là mettā và karuṇā đi cùng nhau.' } },
        source: 'https://vi.wikipedia.org/wiki/Tứ_vô_lượng_tâm',
        inClass: { en: 'Meet your own pain with karuna, the way you would comfort a friend.', vi: 'Đón nhận nỗi đau của chính mình bằng lòng bi, như cách bạn an ủi một người bạn.' },
      },
      {
        id: 'pi-mudita', kind: 'concept', term: 'muditā', lang: 'pi', say: 'MOO-dee-tah', en: 'muditā', vi: 'tâm hỷ',
        meaning: { en: 'Sympathetic joy: gladness at the happiness of others.', vi: 'Tâm hỷ: niềm vui trước hạnh phúc của người khác.' },
        bridge: { term: 'hỷ', note: { en: 'The third immeasurable, also written hỉ.', vi: 'Tâm vô lượng thứ ba, cũng viết là hỉ.' } },
        source: 'https://vi.wikipedia.org/wiki/Tứ_vô_lượng_tâm',
        inClass: { en: 'Mudita: be glad for the person next to you when a pose comes easily.', vi: 'Hỷ: vui cho người bạn tập bên cạnh khi họ vào tư thế dễ dàng.' },
      },
      {
        id: 'pi-upekkha', kind: 'concept', term: 'upekkhā', lang: 'pi', say: 'oo-PEK-khah', en: 'upekkhā', vi: 'tâm xả',
        meaning: { en: 'Equanimity: a balanced mind, neither grasping nor pushing away.', vi: 'Tâm xả: tâm quân bình, không nắm giữ cũng không xua đuổi.' },
        bridge: { term: 'xả', note: { en: 'The fourth immeasurable. Sanskrit upekṣā.', vi: 'Tâm vô lượng thứ tư. Tiếng Phạn: upekṣā.' } },
        source: 'https://vi.wikipedia.org/wiki/Tứ_vô_lượng_tâm',
        inClass: { en: 'Observe every sensation with upekkha, a calm and balanced mind.', vi: 'Quan sát mọi cảm giác với tâm xả, một tâm bình thản và quân bình.' },
      },
      {
        id: 'pi-vedana', kind: 'concept', term: 'vedanā', lang: 'pi', say: 'VAY-duh-nah', en: 'vedanā', vi: 'thọ',
        meaning: { en: 'Feeling tone: every sensation is pleasant, unpleasant or neutral.', vi: 'Thọ: mọi cảm giác đều dễ chịu, khó chịu hoặc trung tính.' },
        bridge: { term: 'thọ', note: { en: 'The second of the five aggregates: sắc, thọ, tưởng, hành, thức.', vi: 'Uẩn thứ hai trong ngũ uẩn: sắc, thọ, tưởng, hành, thức.' } },
        source: 'https://vi.wikipedia.org/wiki/Ngũ_uẩn',
        inClass: { en: 'Notice the sensation, and whether it is pleasant, unpleasant or neutral.', vi: 'Nhận biết cảm giác, và nó dễ chịu, khó chịu hay trung tính.' },
      },
      {
        id: 'pi-sankhara', kind: 'concept', term: 'saṅkhāra', lang: 'pi', say: 'sung-KHAH-ruh', en: 'saṅkhāra', vi: 'hành',
        meaning: { en: 'Mental formations: the reactions and habits that shape the mind.', vi: 'Hành: những phản ứng và thói quen định hình tâm.' },
        bridge: { term: 'hành', note: { en: 'The fourth aggregate. Sanskrit saṃskāra.', vi: 'Uẩn thứ tư. Tiếng Phạn: saṃskāra.' } },
        source: 'https://vi.wikipedia.org/wiki/Ngũ_uẩn',
        inClass: { en: 'Each time you observe without reacting, an old sankhara grows weaker.', vi: 'Mỗi lần bạn quan sát mà không phản ứng, một hành cũ lại yếu đi.' },
      },
      {
        id: 'pi-sanna', kind: 'concept', term: 'saññā', lang: 'pi', say: 'SUN-nyah', en: 'saññā', vi: 'tưởng',
        meaning: { en: 'Perception: recognising and labelling what we meet.', vi: 'Tưởng: nhận ra và gọi tên những gì ta gặp.' },
        bridge: { term: 'tưởng', note: { en: 'The third aggregate. Sanskrit saṃjñā.', vi: 'Uẩn thứ ba. Tiếng Phạn: saṃjñā.' } },
        source: 'https://vi.wikipedia.org/wiki/Ngũ_uẩn',
        inClass: { en: 'Feel the sensation itself, before the mind gives it a name.', vi: 'Cảm nhận chính cảm giác, trước khi tâm đặt tên cho nó.' },
      },
      {
        id: 'pi-vinnana', kind: 'concept', term: 'viññāṇa', lang: 'pi', say: 'vin-NYAH-nuh', en: 'viññāṇa', vi: 'thức',
        meaning: { en: 'Consciousness: the knowing of an object through a sense door.', vi: 'Thức: sự biết một đối tượng qua một cửa giác quan.' },
        bridge: { term: 'thức', note: { en: 'The fifth aggregate. Sanskrit vijñāna.', vi: 'Uẩn thứ năm. Tiếng Phạn: vijñāna.' } },
        source: 'https://vi.wikipedia.org/wiki/Ngũ_uẩn',
        inClass: { en: 'There is a sound, and there is the knowing of the sound.', vi: 'Có âm thanh, và có sự biết âm thanh.' },
      },
      {
        id: 'pi-sati', kind: 'concept', term: 'sati', lang: 'pi', say: 'SUH-tee', en: 'sati', vi: 'niệm',
        meaning: { en: 'Mindfulness: remembering to know what is happening now.', vi: 'Niệm: nhớ để biết rõ những gì đang diễn ra ngay lúc này.' },
        bridge: { term: 'niệm (chánh niệm)', note: { en: 'Sammā-sati is chánh niệm, right mindfulness, in the eightfold path.', vi: 'Sammā-sati là chánh niệm, một chi trong bát chánh đạo.' } },
        source: 'https://vi.wikipedia.org/wiki/Chánh_niệm',
        inClass: { en: 'Sati simply means knowing: breathing in, I know I am breathing in.', vi: 'Niệm đơn giản là biết: thở vào, tôi biết mình đang thở vào.' },
      },
      {
        id: 'pi-anapanasati', kind: 'concept', term: 'ānāpānasati', lang: 'pi', say: 'AH-nah-PAH-nuh-SUH-tee', en: 'ānāpānasati', vi: 'niệm hơi thở',
        meaning: { en: 'Mindfulness of breathing: knowing the in-breath and the out-breath.', vi: 'Niệm hơi thở: biết hơi thở vào và hơi thở ra.' },
        bridge: { term: 'an-ban thủ ý', note: { en: 'Also quán niệm hơi thở. An-ban (安般) is the old transliteration of ānāpāna.', vi: 'Còn gọi là quán niệm hơi thở. An-ban (安般) là phiên âm cũ của ānāpāna.' } },
        source: 'https://vinhnghiemvn.com/tudienphathoc/765019_tue_quang_buddhist_multimedia_dictionary_viet_anh/p3.aspx',
        inClass: { en: 'We begin with anapana: just the breath, coming in and going out at the nostrils.', vi: 'Chúng ta bắt đầu với anapana: chỉ hơi thở, đi vào và đi ra ở lỗ mũi.' },
      },
      {
        id: 'pi-vipassana', kind: 'concept', term: 'vipassanā', lang: 'pi', say: 'vee-PUS-suh-nah', en: 'vipassanā', vi: 'thiền minh sát',
        meaning: { en: 'Insight: seeing things clearly as they are, changing and not self.', vi: 'Minh sát: thấy rõ sự vật đúng như chúng là, vô thường và vô ngã.' },
        bridge: { term: 'minh sát, quán', note: { en: 'Also thiền tuệ. With samatha it makes chỉ and quán.', vi: 'Còn gọi là thiền tuệ. Cùng với samatha tạo thành chỉ và quán.' } },
        source: 'https://vi.wikipedia.org/wiki/Vipassanā',
        inClass: { en: 'Vipassana means seeing things as they really are, not as we want them to be.', vi: 'Vipassana là thấy sự vật đúng như chúng là, không phải như ta muốn.' },
      },
      {
        id: 'pi-samatha', kind: 'concept', term: 'samatha', lang: 'pi', say: 'SUH-muh-tuh', en: 'samatha', vi: 'thiền chỉ',
        meaning: { en: 'Calm: settling the mind on one object until it is quiet.', vi: 'Chỉ: an trú tâm trên một đối tượng cho đến khi tâm lắng yên.' },
        bridge: { term: 'chỉ', note: { en: 'Thiền chỉ; with vipassanā it makes chỉ quán, calm and insight.', vi: 'Thiền chỉ; cùng với vipassanā tạo thành chỉ quán.' } },
        source: 'https://vi.wikipedia.org/wiki/Vipassanā',
        inClass: { en: 'First we calm the mind with samatha; then we observe with vipassana.', vi: 'Trước tiên ta làm lắng tâm bằng thiền chỉ; rồi quan sát bằng thiền quán.' },
      },
      {
        id: 'pi-nibbana', kind: 'concept', term: 'nibbāna', lang: 'pi', say: 'nib-BAH-nuh', en: 'nibbāna', vi: 'niết-bàn',
        meaning: { en: 'The end of craving and suffering; complete freedom.', vi: 'Sự chấm dứt tham ái và khổ đau; tự do hoàn toàn.' },
        bridge: { term: 'niết-bàn', note: { en: 'Sanskrit nirvāṇa.', vi: 'Tiếng Phạn: nirvāṇa.' } },
        source: 'https://vi.wikipedia.org/wiki/Niết-bàn',
        inClass: { en: 'Nibbana is the end of the path. Each sitting is one step on it.', vi: 'Niết-bàn là đích của con đường. Mỗi lần ngồi thiền là một bước trên đó.' },
      },
      {
        id: 'pi-kamma', kind: 'concept', term: 'kamma', lang: 'pi', say: 'KUM-muh', en: 'kamma', vi: 'nghiệp',
        alt: 'karma',
        meaning: { en: 'Intentional action, and the results it brings.', vi: 'Hành động có chủ ý, và quả mà nó mang lại.' },
        bridge: { term: 'nghiệp', note: { en: 'Pali kamma and Sanskrit karma are the same word.', vi: 'Pali kamma và tiếng Phạn karma là cùng một từ.' } },
        source: 'https://vi.wikipedia.org/wiki/Nghiệp_(Phật_giáo)',
        inClass: { en: 'Kamma is intention. What we practise today shapes the mind of tomorrow.', vi: 'Nghiệp là ý định. Những gì ta thực tập hôm nay định hình tâm của ngày mai.' },
      },
      {
        id: 'pi-dhamma', kind: 'concept', term: 'dhamma', lang: 'pi', say: 'DHUM-muh', en: 'dhamma', vi: 'pháp',
        alt: 'dharma',
        meaning: { en: 'The teaching, and the truth it points to; also any phenomenon.', vi: 'Giáo pháp, và chân lý mà nó chỉ đến; cũng là mọi hiện tượng.' },
        bridge: { term: 'pháp', note: { en: 'Pali dhamma and Sanskrit dharma are the same word.', vi: 'Pali dhamma và tiếng Phạn dharma là cùng một từ.' } },
        source: 'https://vi.wikipedia.org/wiki/Pháp_(Phật_giáo)',
        inClass: { en: 'The Dhamma is not only in books. It is here, in your own body and mind.', vi: 'Pháp không chỉ có trong sách. Pháp ở ngay đây, trong chính thân và tâm của bạn.' },
      },
      {
        id: 'pi-jhana', kind: 'concept', term: 'jhāna', lang: 'pi', say: 'JHAH-nuh', en: 'jhāna', vi: 'thiền-na',
        meaning: { en: 'Deep meditative absorption, reached through calm.', vi: 'Trạng thái thiền định sâu, đạt được nhờ sự an tĩnh.' },
        bridge: { term: 'thiền-na', note: { en: 'Thiền-na transliterates jhāna and dhyāna, translated tĩnh lự. The word thiền comes from it.', vi: 'Thiền-na là phiên âm của jhāna và dhyāna, dịch nghĩa là tĩnh lự. Chữ thiền đến từ đây.' } },
        source: 'https://luatminhkhue.vn/thien-la-gi-tim-hieu-ve-phap-tu-thien-trong-dao-phat.aspx',
        inClass: { en: 'Jhana comes from calm, and calm comes from patience. Just keep returning to the breath.', vi: 'Thiền-na đến từ sự an tĩnh, và an tĩnh đến từ sự kiên nhẫn. Cứ tiếp tục quay về hơi thở.' },
      },
      {
        id: 'pi-satipatthana', kind: 'concept', term: 'satipaṭṭhāna', lang: 'pi', say: 'SUH-tee-put-TAH-nuh', en: 'satipaṭṭhāna', vi: 'tứ niệm xứ',
        meaning: { en: 'The four foundations of mindfulness: body, feelings, mind and mental objects.', vi: 'Bốn nền tảng của chánh niệm: thân, thọ, tâm, pháp.' },
        bridge: { term: 'tứ niệm xứ', note: { en: 'Thân, thọ, tâm, pháp. Sanskrit smṛtyupasthāna.', vi: 'Thân, thọ, tâm, pháp. Tiếng Phạn: smṛtyupasthāna.' } },
        source: 'https://vi.wikipedia.org/wiki/Tứ_niệm_xứ',
        inClass: { en: 'We start with the body, the first foundation of mindfulness.', vi: 'Chúng ta bắt đầu với thân, nền tảng đầu tiên của chánh niệm.' },
      },
      {
        id: 'pi-dana', kind: 'concept', term: 'dāna', lang: 'pi', say: 'DAH-nuh', en: 'dāna', vi: 'bố thí',
        meaning: { en: 'Generosity: giving freely.', vi: 'Bố thí: cho đi một cách rộng lượng.' },
        bridge: { term: 'bố thí', note: { en: 'The same word in Pali and Sanskrit. Many vipassana centres run on dāna, gifts given freely.', vi: 'Pali và tiếng Phạn cùng một từ. Nhiều trung tâm vipassana hoạt động nhờ dāna, sự đóng góp tự nguyện.' } },
        source: 'https://vi.wikipedia.org/wiki/Bố_thí',
        inClass: { en: 'This class is offered on dana. Give what you can, if you wish.', vi: 'Lớp học này theo tinh thần dāna. Bạn đóng góp tuỳ tâm, nếu muốn.' },
      },
    ],
  },
]
