/**
 * Bones, landmarks and joints a yoga teacher names. Same fields as the
 * muscles, plus `skeleton`: the group ids in public/anatomy/skeleton-front.svg
 * that light up (see skeleton-boxes.json), or null for a landmark that is
 * placed by hand.
 */
export const BONES = [
  {
    id: 'crown', en: 'crown of the head', plain: 'the top of your head', vi: 'đỉnh đầu', viPlain: 'đỉnh đầu',
    say: 'KROWN', traps: ['cluster-kr', 'final-n'], region: 'head', kind: 'landmark', skeleton: ['Cranium'],
    does: { en: 'The point you lengthen toward in almost every pose.', vi: 'Điểm bạn kéo dài hướng tới trong hầu hết mọi tư thế.' },
    cues: [
      { style: 'vinyasa', en: 'Lengthen through the crown of your head.', vi: 'Kéo dài lên qua đỉnh đầu.' },
      { style: 'ashtanga', en: 'Reach the crown of your head forward as you fold.', vi: 'Vươn đỉnh đầu về trước khi bạn gập người.' },
      { style: 'yin', en: 'Let the crown of your head be heavy toward the floor.', vi: 'Để đỉnh đầu nặng xuống hướng về sàn.' },
    ],
    wordTrap: 'Cụm “kr” liền và kết thúc bằng âm “n”. Không nhầm với “crow” (con quạ, cũng là tên tư thế).',
    near: ['cervical-spine'],
  },
  {
    id: 'jaw', en: 'jaw', latin: 'mandible', plain: 'your jaw', vi: 'xương hàm dưới', viPlain: 'hàm',
    say: 'JAW', traps: ['final-none', 'vowel-aw'], region: 'head', kind: 'bone', skeleton: ['Mandible'],
    does: { en: 'Where tension hides; relaxing it softens the whole face.', vi: 'Nơi căng thẳng ẩn náu; thả lỏng hàm làm mềm cả khuôn mặt.' },
    cues: [
      { style: 'yin', en: 'Unclench your jaw; let your teeth part slightly.', vi: 'Thả hàm; để hai hàm răng hơi tách ra.' },
      { style: 'vinyasa', en: 'Soften your jaw and the space between your eyebrows.', vi: 'Thả lỏng hàm và khoảng giữa hai lông mày.' },
    ],
    wordTrap: 'Nguyên âm “aw” dài, như “saw”. Không có phụ âm cuối.',
    near: ['crown', 'cervical-spine'],
  },
  {
    id: 'cervical-spine', en: 'cervical spine', plain: 'your neck', vi: 'đốt sống cổ', viPlain: 'cổ',
    say: 'SER-vi-kul SPYN', traps: ['stress', 'cluster-sp'], region: 'spine', kind: 'bone', skeleton: ['CervicalVertebrae'],
    does: { en: 'Seven small vertebrae; the most mobile and the most delicate part of the spine.', vi: 'Bảy đốt sống nhỏ; phần linh hoạt nhất và cũng mong manh nhất của cột sống.' },
    cues: [
      { style: 'vinyasa', en: 'Keep the back of your neck long; gaze slightly forward, not up.', vi: 'Giữ phía sau cổ dài; nhìn hơi về trước, không ngước lên.' },
      { style: 'ashtanga', en: 'In Shoulderstand, never turn your head.', vi: 'Trong tư thế Đứng bằng vai, không bao giờ quay đầu.' },
      { style: 'yin', en: 'Let your neck be in line with your spine; a folded blanket under the head helps.', vi: 'Để cổ thẳng hàng với cột sống; một chiếc chăn gấp dưới đầu sẽ giúp.' },
    ],
    wordTrap: 'Trọng âm đầu “SER”. Với học viên, “your neck” là đủ; “cervical spine” dùng khi nói về an toàn.',
    near: ['crown', 'thoracic-spine', 'shoulder-blades'],
  },
  {
    id: 'thoracic-spine', en: 'thoracic spine', plain: 'your upper back', vi: 'đốt sống ngực', viPlain: 'lưng trên',
    say: 'thor-AS-ik SPYN', traps: ['th', 'stress'], region: 'spine', kind: 'bone', skeleton: ['ThoracicVertebrae'],
    does: { en: 'Twelve vertebrae that carry the ribs; where twists and backbends should come from, and where most people are stiff.', vi: 'Mười hai đốt sống mang xương sườn; nơi các tư thế vặn và ngả sau nên bắt đầu, và nơi hầu hết mọi người bị cứng.' },
    cues: [
      { style: 'vinyasa', en: 'Lift your chest and open across your upper back.', vi: 'Nâng ngực và mở rộng lưng trên.' },
      { style: 'yin', en: 'Let the upper back round over the bolster.', vi: 'Để lưng trên cong tròn trên gối ôm.' },
      { style: 'ashtanga', en: 'Twist from your upper back, not your lower back.', vi: 'Vặn từ lưng trên, không phải lưng dưới.' },
    ],
    wordTrap: 'Âm “th” đầu và trọng âm “AS”. “Upper back” dễ hơn nhiều.',
    near: ['cervical-spine', 'lumbar-spine', 'ribs', 'shoulder-blades'],
  },
  {
    id: 'lumbar-spine', en: 'lumbar spine', plain: 'your lower back', vi: 'đốt sống thắt lưng', viPlain: 'lưng dưới, thắt lưng',
    say: 'LUM-bar SPYN', traps: ['stress', 'cluster-sp'], region: 'spine', kind: 'bone', skeleton: ['LumbarVertebrae'],
    does: { en: 'Five big vertebrae; built to bear weight and bend forward and back, not to twist much.', vi: 'Năm đốt sống lớn; sinh ra để chịu trọng lượng, gập trước và ngả sau, không để vặn nhiều.' },
    cues: [
      { style: 'vinyasa', en: 'Keep your lower back long; don’t let it collapse.', vi: 'Giữ lưng dưới dài; đừng để nó sụp xuống.' },
      { style: 'ashtanga', en: 'In backbends, lengthen through the lower back before you bend.', vi: 'Trong tư thế ngả sau, kéo dài lưng dưới trước khi ngả.' },
      { style: 'yin', en: 'If your lower back complains, bend your knees or come out.', vi: 'Nếu lưng dưới khó chịu, chùng gối hoặc thoát thế.' },
    ],
    wordTrap: 'Trọng âm “LUM”. Trong lớp luôn nói “lower back”; học viên than đau chỗ này nhiều nhất.',
    near: ['thoracic-spine', 'sacrum', 'pelvis'],
  },
  {
    id: 'sacrum', en: 'sacrum', plain: 'the flat bone at the base of your spine', vi: 'xương cùng', viPlain: 'phần dưới cùng của cột sống',
    say: 'SAY-krum', traps: ['stress', 'cluster-kr'], region: 'pelvis', kind: 'bone', skeleton: ['Sacrum'],
    does: { en: 'The triangle that joins the spine to the pelvis; it moves a little at the SI joints and that little matters.', vi: 'Xương tam giác nối cột sống với khung chậu; nó cử động một chút ở khớp cùng chậu và chút đó rất quan trọng.' },
    cues: [
      { style: 'yin', en: 'Let your sacrum feel heavy toward the floor.', vi: 'Để xương cùng nặng xuống về phía sàn.' },
      { style: 'vinyasa', en: 'In Bridge, slide a block under your sacrum, not your lower back.', vi: 'Trong Cây cầu, đặt viên gạch dưới xương cùng, không phải dưới lưng dưới.' },
    ],
    wordTrap: 'Đọc “SAY-krum”, nguyên âm dài ở đầu.',
    near: ['lumbar-spine', 'tailbone', 'pelvis', 'piriformis'],
  },
  {
    id: 'tailbone', en: 'tailbone', latin: 'coccyx', plain: 'your tailbone', vi: 'xương cụt', viPlain: 'xương cụt',
    say: 'TAYL-bohn', traps: ['final-l', 'final-n'], region: 'pelvis', kind: 'bone', skeleton: ['Coccyx'],
    does: { en: 'The tip of the spine; cueing it tells students which way the pelvis should tilt.', vi: 'Đầu mút của cột sống; cue về nó cho học viên biết khung chậu nên nghiêng hướng nào.' },
    cues: [
      { style: 'vinyasa', en: 'Lengthen your tailbone toward your heels.', vi: 'Kéo dài xương cụt hướng về gót chân.' },
      { style: 'ashtanga', en: 'Tuck your tailbone slightly in Warrior I.', vi: 'Hơi cuộn xương cụt xuống trong Chiến binh I.' },
      { style: 'yin', en: 'Let your tailbone drop and the lower back widen.', vi: 'Để xương cụt hạ xuống và lưng dưới mở rộng.' },
    ],
    wordTrap: 'Hai âm “l” và “n” cuối đều phải nghe được: TAYL-bohn.',
    near: ['sacrum', 'sit-bones'],
  },
  {
    id: 'pelvis', en: 'pelvis', plain: 'your hips', vi: 'xương chậu', viPlain: 'khung chậu',
    say: 'PEL-vis', traps: ['stress', 'cluster-lv', 'final-s'], region: 'pelvis', kind: 'bone', skeleton: ['PelvicGirdle'],
    does: { en: 'The bowl that carries the spine and meets the legs; its tilt sets up every pose.', vi: 'Chiếc “bát” mang cột sống và nối với hai chân; độ nghiêng của nó quyết định mọi tư thế.' },
    cues: [
      { style: 'vinyasa', en: 'Keep your hips level, like a bowl of water you don’t want to spill.', vi: 'Giữ khung chậu cân bằng, như một bát nước bạn không muốn làm đổ.' },
      { style: 'ashtanga', en: 'Square your hips to the front of the mat.', vi: 'Hướng hai hông vuông góc về phía trước thảm.' },
      { style: 'yin', en: 'Let the pelvis settle; there’s nothing to hold.', vi: 'Để khung chậu lắng xuống; không có gì cần giữ.' },
    ],
    wordTrap: 'Người Việt hay nói “pel-vít”: giữ âm “i” ngắn và “s” cuối rõ. “Hips” gần nghĩa và dễ hơn.',
    near: ['sacrum', 'hip-points', 'sit-bones', 'hip-joint'],
  },
  {
    id: 'hip-points', en: 'hip points', latin: 'anterior superior iliac spines (ASIS)', plain: 'the bony points at the front of your hips', vi: 'gai chậu trước trên', viPlain: 'hai mỏm xương phía trước hông',
    say: 'HIP POYNTS', traps: ['short-i', 'cluster-nts'], region: 'pelvis', kind: 'landmark', skeleton: null,
    does: { en: 'Two bony knobs teachers use as headlights: where they point, the pelvis points.', vi: 'Hai mỏm xương giáo viên dùng như “đèn pha”: chúng hướng đâu, khung chậu hướng đó.' },
    cues: [
      { style: 'vinyasa', en: 'Point your hip points forward, like headlights.', vi: 'Hướng hai mỏm hông về trước, như đèn pha xe.' },
      { style: 'ashtanga', en: 'Draw your front hip point back and your back hip point forward.', vi: 'Kéo mỏm hông trước ra sau và mỏm hông sau về trước.' },
    ],
    wordTrap: 'Cụm “nts” cuối: “points”, không phải “poin”. Giáo viên bản xứ nói “hip points”, không nói ASIS với học viên.',
    near: ['pelvis', 'iliopsoas'],
  },
  {
    id: 'sit-bones', en: 'sitting bones', latin: 'ischial tuberosities', plain: 'the bones you sit on', vi: 'ụ ngồi (xương ngồi)', viPlain: 'xương ngồi',
    say: 'SIT-ing BOHNZ', traps: ['short-i', 'final-z'], region: 'pelvis', kind: 'landmark', skeleton: null,
    does: { en: 'The two knobs at the base of the pelvis; the hamstrings hang from them and every seated pose roots through them.', vi: 'Hai mỏm xương ở đáy khung chậu; cơ đùi sau bám vào đó và mọi tư thế ngồi đều bám rễ qua đó.' },
    cues: [
      { style: 'ashtanga', en: 'Root down through your sitting bones and lengthen up.', vi: 'Bám rễ qua xương ngồi và kéo dài lên.' },
      { style: 'vinyasa', en: 'Lift your sitting bones toward the ceiling in Downward Dog.', vi: 'Nâng xương ngồi lên hướng trần nhà trong Chó úp mặt.' },
      { style: 'yin', en: 'Sit on the edge of a blanket so your sitting bones can tip forward.', vi: 'Ngồi trên mép chăn để xương ngồi có thể nghiêng về trước.' },
    ],
    wordTrap: 'Cả “sitting bones” và “sit bones” đều đúng. Nhớ “s/z” cuối ở “bones”.',
    near: ['pelvis', 'tailbone', 'hamstrings'],
  },
  {
    id: 'pubic-bone', en: 'pubic bone', plain: 'the bone at the front of your pelvis', vi: 'xương mu', viPlain: 'xương mu',
    say: 'PYOO-bik BOHN', traps: ['stress', 'final-n'], region: 'pelvis', kind: 'landmark', skeleton: null,
    does: { en: 'The front of the pelvic bowl; drawing it up tucks the pelvis, releasing it lets the lower back arch.', vi: 'Phía trước của “bát” khung chậu; kéo nó lên sẽ cuộn khung chậu, thả nó ra để lưng dưới ưỡn.' },
    cues: [
      { style: 'vinyasa', en: 'Draw your pubic bone toward your navel to lengthen the lower back.', vi: 'Kéo xương mu về phía rốn để kéo dài lưng dưới.' },
      { style: 'ashtanga', en: 'In Cobra, press your pubic bone into the mat.', vi: 'Trong Rắn hổ mang, ấn xương mu xuống thảm.' },
    ],
    wordTrap: 'Nói rõ ràng, giọng bình thường; từ này là bình thường trong lớp yoga tiếng Anh.',
    near: ['pelvis', 'hip-points', 'pelvic-floor'],
  },
  {
    id: 'hip-joint', en: 'hip joint', plain: 'your hip socket', vi: 'khớp háng', viPlain: 'ổ khớp háng',
    say: 'HIP JOYNT', traps: ['short-i', 'cluster-nt'], region: 'pelvis', kind: 'joint', skeleton: null,
    does: { en: 'A ball and socket, made for folding, opening and turning; “fold from your hips” means hinge here.', vi: 'Khớp chỏm cầu, sinh ra để gập, mở và xoay; “gập từ hông” nghĩa là gập ở đây.' },
    cues: [
      { style: 'vinyasa', en: 'Hinge at your hips, not your waist.', vi: 'Gập ở khớp háng, không phải ở eo.' },
      { style: 'yin', en: 'Let the thigh bone settle deeper into the hip socket.', vi: 'Để xương đùi lắng sâu hơn vào ổ khớp háng.' },
      { style: 'ashtanga', en: 'Turn your thigh out from the hip socket, not the knee.', vi: 'Xoay đùi ra ngoài từ ổ khớp háng, không phải từ gối.' },
    ],
    wordTrap: '“Hip” với âm “i” ngắn, khác “heap”. Giữ âm “p” cuối.',
    near: ['pelvis', 'femur', 'gluteus-medius', 'piriformis'],
  },
  {
    id: 'femur', en: 'thigh bone', latin: 'femur', plain: 'your thigh bone', vi: 'xương đùi', viPlain: 'xương đùi',
    say: 'THY bohn (FEE-mer)', traps: ['th', 'final-n'], region: 'leg', kind: 'bone', skeleton: ['FemurLeft'],
    does: { en: 'The longest bone; its head is the ball in the hip socket. “Draw the thigh bone back” is a hip cue.', vi: 'Xương dài nhất; chỏm của nó là quả cầu trong ổ khớp háng. “Kéo xương đùi về sau” là một cue cho hông.' },
    cues: [
      { style: 'vinyasa', en: 'Draw your front thigh bone back into the hip socket.', vi: 'Kéo xương đùi trước lùi vào ổ khớp háng.' },
      { style: 'yin', en: 'Let the weight of the thigh bones sink.', vi: 'Để trọng lượng xương đùi chìm xuống.' },
    ],
    wordTrap: '“Thigh” với âm “th” đầu và không có âm cuối; không đọc thành “tai”.',
    near: ['hip-joint', 'knee', 'quadriceps', 'hamstrings'],
  },
  {
    id: 'knee', en: 'knee', plain: 'your knee', vi: 'khớp gối', viPlain: 'đầu gối',
    say: 'NEE', traps: ['silent-k', 'long-ee'], region: 'leg', kind: 'joint', skeleton: ['PatellaLeft', 'PatellaRight'],
    does: { en: 'A hinge: it bends and straightens, and does not like to twist. The joint yoga injures most.', vi: 'Khớp bản lề: gập và duỗi, không thích bị vặn. Là khớp yoga hay làm tổn thương nhất.' },
    cues: [
      { style: 'vinyasa', en: 'Keep your knee tracking over your second toe.', vi: 'Giữ gối thẳng hướng với ngón chân thứ hai.' },
      { style: 'vinyasa', en: 'Stack your knee over your ankle, not past it.', vi: 'Đặt gối thẳng trên cổ chân, không đưa quá về trước.' },
      { style: 'yin', en: 'If you feel anything sharp in the knee, come out of the pose.', vi: 'Nếu thấy đau nhói ở gối, hãy thoát khỏi tư thế.' },
      { style: 'ashtanga', en: 'Keep a micro-bend; don’t lock your knees.', vi: 'Giữ gối hơi chùng; đừng khoá gối.' },
    ],
    wordTrap: 'Chữ “k” câm, âm “ee” dài: “nee”. Số nhiều “knees” kết thúc bằng âm “z”.',
    near: ['femur', 'kneecap', 'shin-bone', 'quadriceps', 'hamstrings'],
  },
  {
    id: 'kneecap', en: 'kneecap', latin: 'patella', plain: 'your kneecap', vi: 'xương bánh chè', viPlain: 'xương bánh chè',
    say: 'NEE-kap', traps: ['silent-k', 'final-p'], region: 'leg', kind: 'bone', skeleton: ['PatellaLeft', 'PatellaRight'],
    does: { en: 'The small bone in front of the knee; “lift your kneecaps” switches on the thighs.', vi: 'Xương nhỏ phía trước gối; “nâng xương bánh chè” kích hoạt cơ đùi.' },
    cues: [
      { style: 'ashtanga', en: 'Lift your kneecaps to engage your thighs.', vi: 'Nâng xương bánh chè để kích hoạt đùi.' },
      { style: 'yin', en: 'Soften behind the kneecaps; nothing to hold here.', vi: 'Thả lỏng phía sau xương bánh chè; không cần giữ gì ở đây.' },
    ],
    wordTrap: 'Nhấn âm đầu “NEE”; giữ âm “p” cuối.',
    near: ['knee', 'quadriceps'],
  },
  {
    id: 'shin-bone', en: 'shin', latin: 'tibia', plain: 'your shin', vi: 'xương chày', viPlain: 'ống chân',
    say: 'SHIN (TIB-ee-uh)', traps: ['sh', 'short-i', 'final-n'], region: 'leg', kind: 'bone', skeleton: ['TibiaLeft', 'TibiaRight'],
    does: { en: 'The big bone of the lower leg; “shin parallel to the mat” is the Pigeon alignment cue.', vi: 'Xương lớn của cẳng chân; “ống chân song song với thảm” là cue căn chỉnh của tư thế Bồ câu.' },
    cues: [
      { style: 'vinyasa', en: 'Let your shin angle back; it doesn’t need to be parallel to the mat.', vi: 'Để ống chân chếch về sau; không cần song song với thảm.' },
      { style: 'ashtanga', en: 'Keep your front shin vertical in the lunge.', vi: 'Giữ ống chân trước thẳng đứng trong tư thế chùng chân.' },
    ],
    wordTrap: '“Shin” (ống chân) và “chin” (cằm) chỉ khác âm đầu “sh/ch”. Nhấn rõ “sh”.',
    near: ['knee', 'ankle', 'tibialis-anterior', 'calves'],
  },
  {
    id: 'ankle', en: 'ankle', plain: 'your ankle', vi: 'khớp cổ chân', viPlain: 'cổ chân, mắt cá',
    say: 'ANG-kul', traps: ['stress', 'final-l'], region: 'leg', kind: 'joint', skeleton: ['TarsalsLeft', 'TarsalsRight'],
    does: { en: 'Flexes and points the foot; its stiffness decides how deep a squat goes.', vi: 'Gập và duỗi bàn chân; độ cứng của nó quyết định bạn ngồi xổm sâu đến đâu.' },
    cues: [
      { style: 'vinyasa', en: 'Stack your knee over your ankle.', vi: 'Đặt gối thẳng trên cổ chân.' },
      { style: 'ashtanga', en: 'Flex your ankle and point your toes toward your face.', vi: 'Gập cổ chân và hướng ngón chân về phía mặt.' },
      { style: 'yin', en: 'In Toe Squat, go gently; the ankles and toes open slowly.', vi: 'Trong Ngồi trên ngón chân, nhẹ nhàng thôi; cổ chân và ngón chân mở từ từ.' },
    ],
    wordTrap: 'Nhấn âm đầu “ANG”; âm cuối “kul” nhẹ. Số nhiều “ankles” với âm “z”.',
    near: ['shin-bone', 'heel', 'arch', 'calves'],
  },
  {
    id: 'heel', en: 'heel', latin: 'calcaneus', plain: 'your heel', vi: 'xương gót', viPlain: 'gót chân',
    say: 'HEEL', traps: ['long-ee', 'heel-hill', 'final-l'], region: 'foot', kind: 'bone', skeleton: ['TarsalsLeft', 'TarsalsRight'],
    does: { en: 'The bone you root through in standing poses and reach down in Downward Dog.', vi: 'Xương bạn bám rễ qua trong các tư thế đứng và hướng xuống trong Chó úp mặt.' },
    cues: [
      { style: 'vinyasa', en: 'Root down through your back heel.', vi: 'Ấn chắc xuống qua gót chân sau.' },
      { style: 'ashtanga', en: 'Reach your heels toward the floor.', vi: 'Hướng gót chân xuống sàn.' },
      { style: 'yin', en: 'Sit back toward your heels and let the hips rest.', vi: 'Ngồi lùi về gót chân và để hông nghỉ.' },
    ],
    wordTrap: 'Cặp “heel” (gót, âm dài) và “hill” (đồi, âm ngắn): kéo dài “ee”.',
    near: ['ankle', 'achilles-tendon', 'plantar-fascia'],
  },
  {
    id: 'arch', en: 'arch of the foot', plain: 'the arch of your foot', vi: 'vòm bàn chân', viPlain: 'vòm chân',
    say: 'ARCH', traps: ['final-ch', 'vowel-ar'], region: 'foot', kind: 'landmark', skeleton: ['MetatarsalsLeft', 'MetatarsalsRight'],
    does: { en: 'The spring of the foot; lifting it switches on the whole inner leg.', vi: 'Lò xo của bàn chân; nâng nó lên sẽ kích hoạt toàn bộ mặt trong chân.' },
    cues: [
      { style: 'vinyasa', en: 'Lift your inner arches and press the base of your big toes down.', vi: 'Nâng vòm trong bàn chân và ấn gốc ngón cái xuống.' },
      { style: 'ashtanga', en: 'Press the four corners of your feet into the mat.', vi: 'Ấn bốn góc bàn chân xuống thảm.' },
    ],
    wordTrap: 'Kết thúc bằng âm “ch” rõ ràng. Không nhầm với “arm”.',
    near: ['heel', 'toes', 'tibialis-posterior', 'plantar-fascia'],
  },
  {
    id: 'toes', en: 'toes', plain: 'your toes', vi: 'ngón chân', viPlain: 'ngón chân',
    say: 'TOHZ', traps: ['final-z', 'toe-tow'], region: 'foot', kind: 'landmark', skeleton: ['PhalangesFootLeft', 'PhalangesFootRight'],
    does: { en: 'Spread, they widen the base of every standing pose; tucked, they set up Downward Dog.', vi: 'Xoè ra, chúng mở rộng chân đế của mọi tư thế đứng; bấm xuống, chúng chuẩn bị cho Chó úp mặt.' },
    cues: [
      { style: 'vinyasa', en: 'Spread your toes wide.', vi: 'Xoè rộng các ngón chân.' },
      { style: 'ashtanga', en: 'Tuck your toes and lift your hips.', vi: 'Bấm các ngón chân xuống và nâng hông.' },
      { style: 'vinyasa', en: 'Turn your right toes out and your left toes in slightly.', vi: 'Xoay mũi chân phải ra ngoài, mũi chân trái hơi vào trong.' },
    ],
    wordTrap: 'Số nhiều “toes” có âm “z” cuối; “toe” số ít. Người Việt hay bỏ đuôi và nói “toe” cho cả hai.',
    near: ['arch', 'plantar-fascia'],
  },
  {
    id: 'ribs', en: 'ribs', latin: 'rib cage', plain: 'your ribs', vi: 'xương sườn (lồng ngực)', viPlain: 'xương sườn',
    say: 'RIBZ', traps: ['short-i', 'final-bz'], region: 'trunk', kind: 'bone', skeleton: null,
    does: { en: 'The cage around the lungs; it should widen with the breath and not flare up in backbends.', vi: 'Lồng xương bao quanh phổi; nên mở rộng theo hơi thở và không bật lên trong các tư thế ngả sau.' },
    cues: [
      { style: 'vinyasa', en: 'Knit your front ribs in; don’t let them flare.', vi: 'Khép xương sườn trước vào; đừng để chúng bật ra.' },
      { style: 'yin', en: 'Breathe into your side ribs and the back of your ribs.', vi: 'Thở vào hai bên sườn và phía sau lồng ngực.' },
      { style: 'ashtanga', en: 'Lift your ribs away from your hips to make space for the twist.', vi: 'Nâng xương sườn rời xa hông để tạo khoảng trống cho tư thế vặn.' },
    ],
    wordTrap: 'Âm “i” ngắn và đuôi “bz”; đừng đọc thành “reeb”.',
    near: ['thoracic-spine', 'sternum', 'diaphragm', 'serratus-anterior'],
  },
  {
    id: 'sternum', en: 'breastbone', latin: 'sternum', plain: 'the centre of your chest', vi: 'xương ức', viPlain: 'giữa ngực',
    say: 'STER-num', traps: ['cluster-st', 'stress'], region: 'trunk', kind: 'bone', skeleton: ['Manubrium'],
    does: { en: 'The flat bone in the middle of the chest; “lift your sternum” opens the heart without crunching the lower back.', vi: 'Xương dẹt ở giữa ngực; “nâng xương ức” mở ngực mà không ép lưng dưới.' },
    cues: [
      { style: 'vinyasa', en: 'Lift your sternum toward the ceiling.', vi: 'Nâng xương ức lên hướng trần nhà.' },
      { style: 'ashtanga', en: 'In Cobra, lead with your breastbone, not your chin.', vi: 'Trong Rắn hổ mang, dẫn dắt bằng xương ức, không phải cằm.' },
      { style: 'yin', en: 'Let your sternum soften and sink in the forward fold.', vi: 'Để xương ức mềm và lún xuống trong tư thế gập người.' },
    ],
    wordTrap: 'Cụm “st” liền ở đầu. Nhiều giáo viên nói “your heart” hoặc “your chest” thay thế.',
    near: ['ribs', 'collarbones', 'pectoralis-major'],
  },
  {
    id: 'collarbones', en: 'collarbones', latin: 'clavicles', plain: 'your collarbones', vi: 'xương đòn', viPlain: 'xương quai xanh',
    say: 'KOL-er-bohnz', traps: ['stress', 'final-nz'], region: 'shoulder-girdle', kind: 'bone', skeleton: ['ClavicleLeft', 'ClavicleRight'],
    does: { en: 'The two struts across the top of the chest; “broaden your collarbones” fixes rounded shoulders.', vi: 'Hai thanh xương ngang phía trên ngực; “mở rộng xương đòn” sửa vai tròn gù.' },
    cues: [
      { style: 'vinyasa', en: 'Broaden across your collarbones.', vi: 'Mở rộng hai bên xương đòn.' },
      { style: 'ashtanga', en: 'Spread your collarbones and draw your shoulder blades down.', vi: 'Mở xương đòn và kéo hai bả vai xuống.' },
    ],
    wordTrap: 'Nhấn âm đầu “KOL”; đuôi “bohnz” với âm “z”.',
    near: ['sternum', 'shoulder-blades', 'shoulder-joint'],
  },
  {
    id: 'shoulder-blades', en: 'shoulder blades', latin: 'scapulae', plain: 'your shoulder blades', vi: 'xương bả vai', viPlain: 'bả vai',
    say: 'SHOHL-der BLAYDZ', traps: ['cluster-ld', 'cluster-bl', 'final-dz'], region: 'shoulder-girdle', kind: 'bone', skeleton: ['Scapula'],
    does: { en: 'Two flat triangles that glide on the ribs; most shoulder cues are really about where they sit.', vi: 'Hai xương tam giác dẹt trượt trên lồng ngực; hầu hết cue cho vai thực ra nói về vị trí của chúng.' },
    cues: [
      { style: 'vinyasa', en: 'Slide your shoulder blades down your back.', vi: 'Trượt hai bả vai xuống dọc lưng.' },
      { style: 'ashtanga', en: 'Draw your shoulder blades toward each other and lift your chest.', vi: 'Kéo hai bả vai lại gần nhau và nâng ngực.' },
      { style: 'vinyasa', en: 'In Plank, spread your shoulder blades wide across your back.', vi: 'Trong Plank, mở rộng hai bả vai trên lưng.' },
      { style: 'yin', en: 'Let your shoulder blades melt down toward the floor.', vi: 'Để hai bả vai tan chảy xuống về phía sàn.' },
    ],
    wordTrap: 'Hai cụm phụ âm: “ld” trong shoulder và “bl” trong blades; đuôi “dz”. Đọc chậm, đừng bỏ đuôi.',
    near: ['collarbones', 'trapezius', 'rhomboids', 'rotator-cuff'],
  },
  {
    id: 'shoulder-joint', en: 'shoulder', plain: 'your shoulder', vi: 'khớp vai', viPlain: 'vai',
    say: 'SHOHL-der', traps: ['cluster-ld', 'final-r'], region: 'shoulder-girdle', kind: 'joint', skeleton: ['HumerusLeft', 'HumerusRight'],
    does: { en: 'The most mobile joint in the body and the least stable; it needs the rotator cuff and good shoulder-blade position.', vi: 'Khớp linh hoạt nhất cơ thể và kém ổn định nhất; cần chóp xoay và vị trí bả vai tốt.' },
    cues: [
      { style: 'vinyasa', en: 'Relax your shoulders away from your ears.', vi: 'Thả vai xuống, xa khỏi tai.' },
      { style: 'ashtanga', en: 'Stack your shoulders over your wrists.', vi: 'Đặt vai thẳng trên cổ tay.' },
      { style: 'yin', en: 'If the shoulder pinches, bring the arm lower.', vi: 'Nếu vai bị kẹt nhói, hạ tay xuống thấp hơn.' },
    ],
    wordTrap: 'Số nhiều “shoulders” kết thúc bằng “z”. Cụm “ld” ở giữa hay bị nuốt thành “shou-đơ”.',
    near: ['shoulder-blades', 'collarbones', 'deltoids', 'rotator-cuff', 'upper-arm-bone'],
  },
  {
    id: 'upper-arm-bone', en: 'upper arm bone', latin: 'humerus', plain: 'your upper arm', vi: 'xương cánh tay', viPlain: 'cánh tay trên',
    say: 'HYOO-mer-us', traps: ['stress', 'final-s'], region: 'arm', kind: 'bone', skeleton: ['HumerusLeft', 'HumerusRight'],
    does: { en: 'Its head is the ball of the shoulder; “rotate your upper arms out” turns this bone.', vi: 'Chỏm của nó là quả cầu của khớp vai; “xoay bắp tay ra ngoài” là xoay xương này.' },
    cues: [
      { style: 'vinyasa', en: 'Rotate your upper arms outward to make space for your neck.', vi: 'Xoay bắp tay ra ngoài để tạo khoảng trống cho cổ.' },
      { style: 'ashtanga', en: 'Hug your upper arms in toward your ribs.', vi: 'Ôm bắp tay sát vào sườn.' },
    ],
    wordTrap: '“Humerus” nghe giống “humorous” (hài hước); học viên hay cười. “Upper arm” là đủ.',
    near: ['shoulder-joint', 'elbow', 'biceps-brachii', 'triceps-brachii'],
  },
  {
    id: 'elbow', en: 'elbow', plain: 'your elbow', vi: 'khớp khuỷu tay', viPlain: 'khuỷu tay',
    say: 'EL-boh', traps: ['stress', 'cluster-lb'], region: 'arm', kind: 'joint', skeleton: null,
    does: { en: 'A hinge; the cue “don’t lock your elbows” protects it in weight-bearing poses.', vi: 'Khớp bản lề; cue “đừng khoá khuỷu tay” bảo vệ nó trong các tư thế chịu lực.' },
    cues: [
      { style: 'vinyasa', en: 'Keep a soft bend in your elbows.', vi: 'Giữ khuỷu tay hơi chùng.' },
      { style: 'ashtanga', en: 'In Chaturanga, bend your elbows straight back, hugging your ribs.', vi: 'Trong Chaturanga, gập khuỷu thẳng về sau, ôm sát sườn.' },
      { style: 'vinyasa', en: 'Point your elbow creases forward.', vi: 'Hướng nếp gấp khuỷu tay về phía trước.' },
    ],
    wordTrap: 'Nhấn âm đầu “EL”; cụm “lb” ở giữa đọc liền.',
    near: ['upper-arm-bone', 'forearm-bones', 'biceps-brachii', 'triceps-brachii'],
  },
  {
    id: 'forearm-bones', en: 'forearm', latin: 'radius and ulna', plain: 'your forearm', vi: 'xương quay và xương trụ', viPlain: 'cẳng tay',
    say: 'FOR-arm', traps: ['stress', 'final-m'], region: 'arm', kind: 'bone', skeleton: ['RadiusLeft', 'UlnaLeft', 'RadiusRight', 'UlnaRight'],
    does: { en: 'Two bones that roll over each other to turn the palm up or down.', vi: 'Hai xương lăn qua nhau để xoay lòng bàn tay lên hoặc xuống.' },
    cues: [
      { style: 'vinyasa', en: 'Come down onto your forearms, elbows under your shoulders.', vi: 'Hạ xuống chống cẳng tay, khuỷu dưới vai.' },
      { style: 'yin', en: 'Rest on your forearms or lower all the way down.', vi: 'Tựa lên cẳng tay hoặc hạ hẳn xuống.' },
    ],
    wordTrap: 'Hai âm tiết, trọng âm đầu. Đừng nói “four arm”.',
    near: ['elbow', 'wrist', 'forearm-flexors', 'forearm-extensors'],
  },
  {
    id: 'wrist', en: 'wrist', plain: 'your wrist', vi: 'khớp cổ tay', viPlain: 'cổ tay',
    say: 'RIST', traps: ['silent-w', 'cluster-st', 'short-i'], region: 'arm', kind: 'joint', skeleton: ['CarpalsLeft', 'CarpalsRight'],
    does: { en: 'Eight small bones; it takes the weight in Downward Dog and Plank and needs the fingers’ help.', vi: 'Tám xương nhỏ; chịu trọng lượng trong Chó úp mặt và Plank, cần sự hỗ trợ của các ngón tay.' },
    cues: [
      { style: 'vinyasa', en: 'Spread your fingers and press through your knuckles to take weight off your wrists.', vi: 'Xoè ngón tay và ấn qua các khớp ngón để giảm trọng lượng dồn lên cổ tay.' },
      { style: 'vinyasa', en: 'If your wrists hurt, come onto your fists or your forearms.', vi: 'Nếu cổ tay đau, chống nắm tay hoặc cẳng tay.' },
      { style: 'ashtanga', en: 'Stack your shoulders over your wrists.', vi: 'Đặt vai thẳng trên cổ tay.' },
    ],
    wordTrap: 'Chữ “w” câm, đuôi “st” rõ; số nhiều “wrists” có cụm “sts” rất khó: đọc chậm “rists”.',
    near: ['forearm-bones', 'hands', 'forearm-flexors'],
  },
  {
    id: 'hands', en: 'hands and fingers', plain: 'your hands', vi: 'bàn tay và ngón tay', viPlain: 'bàn tay',
    say: 'HANDZ', traps: ['cluster-ndz'], region: 'arm', kind: 'landmark', skeleton: ['HandLeft', 'HandRight'],
    does: { en: 'The foundation of every arm-supported pose: spread, rooted, knuckles pressing.', vi: 'Nền móng của mọi tư thế chống tay: xoè, bám chắc, các khớp ngón ấn xuống.' },
    cues: [
      { style: 'vinyasa', en: 'Spread your fingers wide, middle fingers pointing forward.', vi: 'Xoè rộng ngón tay, ngón giữa hướng về trước.' },
      { style: 'ashtanga', en: 'Press into the base of your index fingers.', vi: 'Ấn vào gốc ngón trỏ.' },
      { style: 'yin', en: 'Turn your palms up and let the fingers curl softly.', vi: 'Ngửa lòng bàn tay và để ngón tay cong nhẹ.' },
    ],
    wordTrap: 'Cụm cuối “ndz” trong “hands”: nhiều người nói “han”. Giữ ít nhất âm “z”.',
    near: ['wrist'],
  },
]
