/** Muscles of the trunk: abdominal wall, deep core, breathing. Fields as in muscles-upper.js. */
export const MUSCLES_CORE = [
  {
    id: 'rectus-abdominis', en: 'rectus abdominis', plain: 'the front of your belly', shortEn: 'abs',
    vi: 'cơ thẳng bụng', viPlain: 'cơ bụng trước', say: 'REK-tus ab-DOM-i-nis', traps: ['stress', 'cluster-kt', 'final-s'],
    region: 'trunk', view: ['front'], deep: false,
    does: { en: 'Curls the trunk forward and holds the ribs down; the “six-pack”.', vi: 'Cuộn thân về trước và giữ xương sườn hạ xuống; cơ “sáu múi”.' },
    feel: { en: 'Working in Boat; stretched long in Cobra, Camel and Wheel.', vi: 'Làm việc trong Con thuyền; được giãn dài trong Rắn hổ mang, Lạc đà và Bánh xe.' },
    cues: [
      { style: 'vinyasa', en: 'Draw your lower ribs in toward your hips.', vi: 'Kéo xương sườn dưới vào hướng về hông.' },
      { style: 'ashtanga', en: 'In Boat, lift your chest and keep the belly firm, not hard.', vi: 'Trong Con thuyền, nâng ngực và giữ bụng chắc, không gồng cứng.' },
      { style: 'yin', en: 'In Sphinx, let the belly be soft and the front body long.', vi: 'Trong Nhân sư, để bụng mềm và phía trước thân dài ra.' },
      { style: 'vinyasa', en: 'Knit your front ribs together as you reach up.', vi: 'Khép hai bên sườn trước lại khi bạn vươn lên.' },
    ],
    works: ['boat-pose', 'plank', 'chaturanga'], stretches: ['cobra', 'camel-pose', 'wheel-pose', 'sphinx'],
    wordTrap: '“Abdominal” nhấn âm thứ hai: ab-DOM-i-nal. Trong lớp, “your belly” ấm áp hơn “your abs”.',
    near: ['external-oblique', 'transversus-abdominis', 'iliopsoas'], under: ['transversus-abdominis'],
  },
  {
    id: 'external-oblique', en: 'obliques', latin: 'obliquus externus abdominis', plain: 'the sides of your waist',
    vi: 'cơ chéo bụng ngoài', viPlain: 'cơ bên eo', say: 'oh-BLEEKS', traps: ['stress', 'cluster-bl', 'final-ks'],
    region: 'trunk', view: ['front', 'back'], deep: false,
    does: { en: 'Twist and side-bend the trunk; the muscles of every twist.', vi: 'Vặn và nghiêng thân sang bên; cơ của mọi tư thế vặn.' },
    feel: { en: 'Working on one side and stretching on the other in a seated twist or Side Plank.', vi: 'Làm việc ở một bên và giãn ở bên kia trong tư thế vặn ngồi hoặc Plank nghiêng.' },
    cues: [
      { style: 'vinyasa', en: 'Twist from your belly, not from your neck.', vi: 'Vặn từ bụng, không phải từ cổ.' },
      { style: 'ashtanga', en: 'Lengthen first, then twist a little more on each exhale.', vi: 'Kéo dài trước, rồi vặn thêm một chút ở mỗi hơi thở ra.' },
      { style: 'vinyasa', en: 'In Side Plank, lift your waist away from the floor.', vi: 'Trong Plank nghiêng, nâng eo lên khỏi sàn.' },
      { style: 'yin', en: 'Let the twist happen without pulling; the breath does the work.', vi: 'Để tư thế vặn tự diễn ra mà không kéo; hơi thở làm việc đó.' },
    ],
    works: ['side-plank', 'revolved-triangle', 'boat-pose'], stretches: ['seated-twist', 'supine-twist', 'side-bend', 'gate-pose'],
    wordTrap: 'Đọc “oh-BLEEKS”, trọng âm sau; nhiều người đọc “ob-li-ques” ba âm. Bao gồm cả cơ chéo trong nằm dưới.',
    near: ['rectus-abdominis', 'serratus-anterior', 'latissimus-dorsi'], under: ['internal-oblique', 'transversus-abdominis'],
  },
  {
    id: 'internal-oblique', en: 'internal oblique', plain: 'the deeper layer of your waist',
    vi: 'cơ chéo bụng trong', viPlain: 'lớp sâu của cơ eo', say: 'in-TER-nal oh-BLEEK', traps: ['stress'],
    region: 'trunk', view: ['front'], deep: true,
    does: { en: 'Twists the trunk toward the same side; works as a pair with the external oblique opposite.', vi: 'Vặn thân về cùng bên; làm việc theo cặp với cơ chéo ngoài bên đối diện.' },
    feel: { en: 'Not felt separately; it is part of the “twist from your waist” feeling.', vi: 'Không cảm nhận riêng được; là một phần của cảm giác “vặn từ eo”.' },
    cues: [
      { style: 'vinyasa', en: 'Draw your navel gently toward your spine as you twist.', vi: 'Hóp nhẹ rốn về phía cột sống khi bạn vặn.' },
    ],
    works: ['revolved-triangle', 'seated-twist'], stretches: ['supine-twist'],
    wordTrap: 'Không cần nói tên này trong lớp; “your waist” hoặc “your obliques” là đủ.',
    near: ['external-oblique', 'transversus-abdominis'], under: ['transversus-abdominis'],
  },
  {
    id: 'transversus-abdominis', en: 'transversus abdominis', plain: 'your deep belly, like a corset', shortEn: 'TVA',
    vi: 'cơ ngang bụng', viPlain: 'cơ bụng sâu', say: 'trans-VER-sus ab-DOM-i-nis', traps: ['cluster-tr', 'stress'],
    region: 'trunk', view: ['front'], deep: true,
    does: { en: 'Wraps the belly like a corset and steadies the spine and pelvis; the “draw in” muscle.', vi: 'Bao quanh bụng như một chiếc áo nịt và giữ vững cột sống, khung chậu; cơ “hóp bụng”.' },
    feel: { en: 'The gentle narrowing of the waist when you exhale fully and the belly draws in on its own.', vi: 'Cảm giác eo hơi thu lại khi bạn thở ra hết và bụng tự hóp vào.' },
    cues: [
      { style: 'vinyasa', en: 'Draw your belly in gently to support your spine.', vi: 'Hóp nhẹ bụng vào để nâng đỡ cột sống.' },
      { style: 'ashtanga', en: 'Engage uddiyana bandha: lift and draw in just below the navel.', vi: 'Kích hoạt uddiyana bandha: nâng và hóp vào ngay dưới rốn.' },
      { style: 'vinyasa', en: 'Hug your low belly in as you lift one leg.', vi: 'Ôm bụng dưới vào khi bạn nhấc một chân.' },
    ],
    works: ['plank', 'boat-pose', 'warrior-3', 'all-balances'], stretches: [],
    wordTrap: 'Giáo viên thường nói “the TVA” hoặc “your deep core”. Với học viên: “draw your belly in” là đủ.',
    near: ['rectus-abdominis', 'internal-oblique', 'pelvic-floor'], under: [],
  },
  {
    id: 'diaphragm', en: 'diaphragm', plain: 'your breathing muscle, under your ribs',
    vi: 'cơ hoành', viPlain: 'cơ thở dưới lồng ngực', say: 'DY-uh-fram', traps: ['stress', 'silent-g', 'final-m'],
    region: 'trunk', view: ['front'], deep: true,
    does: { en: 'The dome under the lungs; it drops to breathe in and lifts to breathe out.', vi: 'Vòm cơ dưới phổi; hạ xuống khi hít vào và nâng lên khi thở ra.' },
    feel: { en: 'The belly rising on the inhale when the breath is low and slow.', vi: 'Bụng phồng lên khi hít vào lúc hơi thở sâu và chậm.' },
    cues: [
      { style: 'yin', en: 'Breathe low into your belly; let your ribs widen on the inhale.', vi: 'Thở sâu xuống bụng; để lồng ngực mở rộng khi hít vào.' },
      { style: 'ashtanga', en: 'Keep the breath steady and audible; let it lead the movement.', vi: 'Giữ hơi thở đều và nghe được; để hơi thở dẫn dắt chuyển động.' },
      { style: 'vinyasa', en: 'Inhale, feel your ribs expand in every direction.', vi: 'Hít vào, cảm nhận lồng ngực nở ra mọi hướng.' },
    ],
    works: ['pranayama', 'every-pose'], stretches: ['supported-fish', 'reclined-bound-angle'],
    wordTrap: 'Chữ “g” câm: đọc “DY-uh-fram”, không phải “dai-a-phờ-ram”. Kết thúc bằng âm “m” khép môi.',
    near: ['rectus-abdominis', 'iliopsoas'], under: [],
  },
  {
    id: 'pelvic-floor', en: 'pelvic floor', plain: 'the floor of your pelvis',
    vi: 'cơ sàn chậu', viPlain: 'sàn chậu', say: 'PEL-vik FLOR', traps: ['cluster-lv', 'cluster-fl'],
    region: 'trunk', view: ['front'], deep: true,
    does: { en: 'The sling at the base of the pelvis; lifts gently with mula bandha and softens in deep breathing.', vi: 'Dải cơ ở đáy khung chậu; nâng nhẹ với mula bandha và mềm ra khi thở sâu.' },
    feel: { en: 'The gentle lift between the sitting bones at the end of an exhale.', vi: 'Cảm giác nâng nhẹ giữa hai xương ngồi ở cuối hơi thở ra.' },
    cues: [
      { style: 'ashtanga', en: 'Engage mula bandha: a gentle lift at the base of the pelvis.', vi: 'Kích hoạt mula bandha: nâng nhẹ ở đáy khung chậu.' },
      { style: 'yin', en: 'Let the pelvic floor soften and widen as you breathe in.', vi: 'Để sàn chậu mềm và mở rộng khi bạn hít vào.' },
    ],
    works: ['mula-bandha', 'all-balances'], stretches: ['malasana', 'happy-baby'],
    wordTrap: '“Pelvic” có cụm “lv” giữa từ: PEL-vik. Chủ đề nhạy cảm với một số học viên; nói nhẹ nhàng, rõ ràng.',
    near: ['transversus-abdominis', 'hip-adductors'], under: [],
  },
]
