/** Muscles of the hip, thigh, lower leg and foot. Fields as in muscles-upper.js. */
export const MUSCLES_LOWER = [
  {
    id: 'iliopsoas', en: 'iliopsoas', latin: 'psoas major + iliacus', plain: 'your deep hip flexors', shortEn: 'psoas',
    vi: 'cơ thắt lưng chậu', viPlain: 'cơ gấp hông sâu', say: 'il-ee-oh-SO-as (SO-as)', traps: ['stress', 'silent-p'],
    region: 'hip', view: ['front'], deep: true,
    does: { en: 'Lifts the thigh toward the belly and pulls the lower back into an arch; tight from sitting.', vi: 'Nâng đùi về phía bụng và kéo lưng dưới ưỡn; bị căng do ngồi nhiều.' },
    feel: { en: 'The deep pull at the front of the back hip in a lunge; the lift in Boat.', vi: 'Cảm giác kéo sâu ở phía trước hông chân sau trong tư thế chùng chân; cảm giác nâng trong Con thuyền.' },
    cues: [
      { style: 'vinyasa', en: 'Sink your hips forward and down, and feel the front of your back hip open.', vi: 'Hạ hông về trước và xuống, cảm nhận phía trước hông chân sau mở ra.' },
      { style: 'yin', en: 'In Dragon, let the weight of the hips do the work; breathe into the front of the hip.', vi: 'Trong tư thế Rồng, để trọng lượng hông làm việc; thở vào phía trước hông.' },
      { style: 'ashtanga', en: 'Tuck your tailbone slightly to lengthen the front of your hips.', vi: 'Hơi cuộn xương cụt xuống để kéo dài phía trước hông.' },
      { style: 'vinyasa', en: 'In Boat, lift from deep in your hips, not just your belly.', vi: 'Trong Con thuyền, nâng từ sâu trong hông, không chỉ từ bụng.' },
    ],
    works: ['boat-pose', 'standing-leg-lifts'], stretches: ['low-lunge', 'dragon', 'warrior-1', 'camel-pose', 'bridge-pose'],
    wordTrap: '“Psoas”: chữ “p” câm, đọc “SO-as”. Hầu hết giáo viên chỉ nói “psoas” hoặc “hip flexors”.',
    near: ['rectus-femoris', 'tensor-fasciae-latae', 'quadratus-lumborum'], under: [],
  },
  {
    id: 'tensor-fasciae-latae', en: 'tensor fasciae latae', plain: 'the muscle at the outer front of your hip', shortEn: 'TFL',
    vi: 'cơ căng mạc đùi', viPlain: 'cơ phía ngoài trước hông', say: 'TEN-sor FASH-ee-ee LAY-tee', traps: ['stress'],
    region: 'hip', view: ['front'], deep: false,
    does: { en: 'Lifts the leg out and forward and tightens the IT band; often overworked in standing poses.', vi: 'Nâng chân ra ngoài và về trước, kéo căng dải chậu chày; thường làm việc quá sức trong các tư thế đứng.' },
    feel: { en: 'The small hard spot just below the hip point that aches in Tree Pose.', vi: 'Điểm cứng nhỏ ngay dưới mỏm hông, hay mỏi trong tư thế Cái cây.' },
    cues: [
      { style: 'vinyasa', en: 'Soften the outer hip of your standing leg; don’t grip.', vi: 'Thả lỏng hông ngoài của chân trụ; đừng gồng.' },
      { style: 'yin', en: 'In Shoelace, let the outer hips release toward the floor.', vi: 'Trong tư thế Dây giày, để hông ngoài buông xuống sàn.' },
    ],
    works: ['tree-pose', 'warrior-3'], stretches: ['shoelace', 'pigeon', 'figure-four'],
    wordTrap: 'Giáo viên gọi là “the TFL” (ti-ef-el). Không cần phát âm tên Latin đầy đủ.',
    near: ['iliopsoas', 'gluteus-medius', 'it-band'], under: [],
  },
  {
    id: 'gluteus-maximus', en: 'gluteus maximus', plain: 'your seat', shortEn: 'glutes',
    vi: 'cơ mông lớn', viPlain: 'cơ mông', say: 'GLOO-tee-us MAK-si-mus', traps: ['cluster-gl', 'stress'],
    region: 'hip', view: ['back'], deep: false,
    does: { en: 'Straightens the hip and turns the leg out; powers Bridge and Warrior I.', vi: 'Duỗi hông và xoay chân ra ngoài; tạo lực trong Cây cầu và Chiến binh I.' },
    feel: { en: 'Firm in Bridge; stretched deeply in Pigeon and Sleeping Swan.', vi: 'Săn chắc trong Cây cầu; được giãn sâu trong Bồ câu và Thiên nga ngủ.' },
    cues: [
      { style: 'vinyasa', en: 'Press into your heels and lift your hips.', vi: 'Ấn gót chân xuống và nâng hông lên.' },
      { style: 'ashtanga', en: 'In Bridge, keep the glutes working but not clenched.', vi: 'Trong Cây cầu, giữ cơ mông làm việc nhưng không siết chặt.' },
      { style: 'yin', en: 'Let your seat get heavy and soft; sink toward the floor.', vi: 'Để mông nặng và mềm xuống; chìm về phía sàn.' },
      { style: 'vinyasa', en: 'Squeeze your seat gently to protect your lower back in the backbend.', vi: 'Siết nhẹ mông để bảo vệ lưng dưới trong tư thế ngả sau.' },
    ],
    works: ['bridge-pose', 'warrior-1', 'locust-pose', 'chair-pose'], stretches: ['sleeping-swan', 'pigeon', 'figure-four', 'happy-baby'],
    wordTrap: 'Cụm “gl” liền: “GLOOTS”, không phải “gơ-lút”. “Your seat” hoặc “your glutes” đều tự nhiên trong lớp.',
    near: ['gluteus-medius', 'hamstrings', 'piriformis'], under: ['piriformis', 'deep-rotators'],
  },
  {
    id: 'gluteus-medius', en: 'gluteus medius', plain: 'the side of your hip',
    vi: 'cơ mông nhỡ', viPlain: 'cơ bên hông', say: 'GLOO-tee-us MEE-dee-us', traps: ['cluster-gl', 'stress'],
    region: 'hip', view: ['back'], deep: false,
    does: { en: 'Lifts the leg sideways and keeps the pelvis level on one leg; the balance muscle.', vi: 'Nâng chân sang bên và giữ khung chậu cân bằng khi đứng một chân; cơ thăng bằng.' },
    feel: { en: 'The outer hip of the standing leg in Tree and Half Moon.', vi: 'Hông ngoài của chân trụ trong Cái cây và Bán nguyệt.' },
    cues: [
      { style: 'vinyasa', en: 'Keep your hips level; don’t let the standing hip push out.', vi: 'Giữ hai hông ngang bằng; đừng để hông chân trụ đẩy ra ngoài.' },
      { style: 'vinyasa', en: 'Press the outer edge of your back foot down and feel the side of your hip wake up.', vi: 'Ấn cạnh ngoài bàn chân sau xuống và cảm nhận bên hông được đánh thức.' },
      { style: 'yin', en: 'In Shoelace, breathe into the outer hip.', vi: 'Trong tư thế Dây giày, thở vào phần hông ngoài.' },
    ],
    works: ['tree-pose', 'half-moon', 'warrior-2', 'warrior-3', 'side-plank'], stretches: ['shoelace', 'figure-four', 'pigeon'],
    wordTrap: '“Medius” đọc “MEE-dee-us”, không phải “mê-đi-us”. Với học viên: “the side of your hip”.',
    near: ['gluteus-maximus', 'tensor-fasciae-latae'], under: ['gluteus-minimus'],
  },
  {
    id: 'gluteus-minimus', en: 'gluteus minimus', plain: 'the small deep muscle of your outer hip',
    vi: 'cơ mông bé', viPlain: 'cơ nhỏ sâu bên hông', say: 'GLOO-tee-us MIN-i-mus', traps: ['cluster-gl', 'stress'],
    region: 'hip', view: ['back'], deep: true,
    does: { en: 'Helps the gluteus medius hold the pelvis level and turns the thigh in slightly.', vi: 'Hỗ trợ cơ mông nhỡ giữ khung chậu cân bằng và hơi xoay đùi vào trong.' },
    feel: { en: 'Not felt on its own; part of the outer-hip balance work.', vi: 'Không cảm nhận riêng; là một phần công việc thăng bằng của hông ngoài.' },
    cues: [{ style: 'vinyasa', en: 'Steady your standing hip without gripping.', vi: 'Giữ vững hông chân trụ mà không gồng.' }],
    works: ['tree-pose', 'half-moon'], stretches: ['figure-four'],
    wordTrap: 'Không cần nói trong lớp; gộp vào “the side of your hip”.',
    near: ['gluteus-medius', 'piriformis'], under: [],
  },
  {
    id: 'piriformis', en: 'piriformis', plain: 'deep in your outer hip',
    vi: 'cơ hình lê', viPlain: 'cơ sâu bên ngoài hông', say: 'pir-i-FOR-mis', traps: ['stress', 'final-s'],
    region: 'hip', view: ['back'], deep: true,
    does: { en: 'Turns the thigh out and steadies the hip; the sciatic nerve runs beside or through it.', vi: 'Xoay đùi ra ngoài và giữ hông ổn định; dây thần kinh toạ chạy cạnh hoặc xuyên qua nó.' },
    feel: { en: 'The deep ache in the outer hip in Pigeon, Sleeping Swan and Figure Four.', vi: 'Cảm giác nhức sâu ở hông ngoài trong Bồ câu, Thiên nga ngủ và Số 4.' },
    cues: [
      { style: 'yin', en: 'You should feel this deep in your outer hip, not in your knee.', vi: 'Bạn nên cảm thấy căng sâu bên ngoài hông, không phải ở gối.' },
      { style: 'yin', en: 'Find your edge and let the hip soften a little more with each exhale.', vi: 'Tìm ngưỡng của bạn và để hông mềm thêm một chút sau mỗi hơi thở ra.' },
      { style: 'vinyasa', en: 'Flex your front foot to protect the knee as the hip opens.', vi: 'Gập bàn chân trước để bảo vệ gối khi hông mở.' },
    ],
    works: ['warrior-2', 'standing-poses'], stretches: ['sleeping-swan', 'pigeon', 'figure-four', 'shoelace'],
    wordTrap: 'Trọng âm “FOR”. Học viên bị đau thần kinh toạ hay biết từ này; đáng để nói đúng.',
    near: ['gluteus-maximus', 'deep-rotators', 'sacrum'], under: [],
  },
  {
    id: 'deep-rotators', en: 'deep hip rotators', latin: 'gemelli, obturators, quadratus femoris', plain: 'the small muscles deep in your hip',
    vi: 'nhóm cơ xoay ngoài sâu của hông', viPlain: 'các cơ nhỏ sâu trong hông', say: 'DEEP HIP ROH-tay-ters', traps: ['final-p', 'stress'],
    region: 'hip', view: ['back'], deep: true,
    does: { en: 'Turn the thigh out, with the piriformis; they let the knees open in Lotus and Bound Angle.', vi: 'Xoay đùi ra ngoài, cùng với cơ hình lê; giúp hai gối mở ra trong Hoa sen và Góc cố định.' },
    feel: { en: 'The releasing deep in the hip in a long Yin hold.', vi: 'Cảm giác buông sâu trong hông khi giữ lâu trong Yin.' },
    cues: [
      { style: 'yin', en: 'Let the thighs roll open from deep in the hip sockets.', vi: 'Để hai đùi mở ra từ sâu trong ổ khớp háng.' },
      { style: 'ashtanga', en: 'Rotate your front thigh out as you fold.', vi: 'Xoay đùi trước ra ngoài khi bạn gập người.' },
    ],
    works: ['warrior-2', 'lotus', 'bound-angle'], stretches: ['sleeping-swan', 'figure-four'],
    wordTrap: 'Gộp vào “deep in your hip”; không cần tên riêng.',
    near: ['piriformis', 'gluteus-maximus'], under: [],
  },
  {
    id: 'hip-adductors', en: 'adductors', plain: 'your inner thighs',
    vi: 'nhóm cơ khép đùi', viPlain: 'mặt trong đùi', say: 'a-DUK-ters', traps: ['stress', 'final-z'],
    region: 'hip', view: ['front', 'back'], deep: false,
    latin: 'adductor longus, brevis, magnus; pectineus; gracilis',
    does: { en: 'Draw the legs together and steady the pelvis; they open in wide-legged poses and Bound Angle.', vi: 'Khép hai chân lại và giữ vững khung chậu; được mở trong các tư thế dang chân rộng và Góc cố định.' },
    feel: { en: 'The inner thigh stretch in Wide-Legged Forward Fold and Frog; working when you squeeze a block.', vi: 'Cảm giác giãn mặt trong đùi trong Gập người dang rộng chân và Con ếch; làm việc khi bạn kẹp gạch.' },
    cues: [
      { style: 'vinyasa', en: 'Squeeze the block between your thighs.', vi: 'Kẹp viên gạch giữa hai đùi.' },
      { style: 'yin', en: 'In Frog, let your inner thighs soften toward the floor; don’t push.', vi: 'Trong Con ếch, để mặt trong đùi mềm xuống sàn; đừng ép.' },
      { style: 'ashtanga', en: 'In Prasarita, draw your inner thighs back as you fold.', vi: 'Trong Prasarita, kéo mặt trong đùi ra sau khi bạn gập người.' },
      { style: 'vinyasa', en: 'Let your inner thighs open as you sink into Warrior II.', vi: 'Để mặt trong đùi mở ra khi bạn hạ sâu vào Chiến binh II.' },
    ],
    works: ['chair-pose', 'bridge-pose', 'eagle-pose'], stretches: ['wide-legged-fold', 'frog', 'bound-angle', 'warrior-2', 'dragonfly'],
    wordTrap: '“Adductors” (khép) và “abductors” (dạng) nghe gần giống nhau; nhấn rõ âm “d” và “b”. Với học viên: “inner thighs”.',
    near: ['iliopsoas', 'sartorius', 'gracilis', 'hamstrings'], under: [],
  },
  {
    id: 'sartorius', en: 'sartorius', plain: 'the long strap muscle across your thigh',
    vi: 'cơ may', viPlain: 'cơ dài chéo qua đùi', say: 'sar-TOR-ee-us', traps: ['stress', 'final-s'],
    region: 'thigh', view: ['front'], deep: false,
    does: { en: 'The longest muscle in the body; it crosses the thigh to help you sit cross-legged.', vi: 'Cơ dài nhất cơ thể; chạy chéo qua đùi để giúp bạn ngồi khoanh chân.' },
    feel: { en: 'Rarely felt alone; part of lifting the knee out and up into Tree Pose.', vi: 'Hiếm khi cảm nhận riêng; là một phần của việc nâng gối ra ngoài và lên trong Cái cây.' },
    cues: [{ style: 'vinyasa', en: 'Open your knee out to the side as you place the foot in Tree.', vi: 'Mở gối ra bên khi bạn đặt bàn chân trong Cái cây.' }],
    works: ['tree-pose', 'lotus'], stretches: ['reclined-hero'],
    wordTrap: 'Tên đẹp (“cơ thợ may”) nhưng không cần dùng trong lớp.',
    near: ['quadriceps', 'hip-adductors', 'tensor-fasciae-latae'], under: [],
  },
  {
    id: 'quadriceps', en: 'quadriceps', plain: 'the front of your thighs', shortEn: 'quads',
    vi: 'cơ tứ đầu đùi', viPlain: 'mặt trước đùi', say: 'KWOD-ri-seps', traps: ['stress', 'final-ps'],
    region: 'thigh', view: ['front'], deep: false,
    latin: 'rectus femoris, vastus lateralis, medialis, intermedius',
    does: { en: 'Straighten the knee; the rectus femoris also lifts the thigh. They hold you in Chair and Warrior.', vi: 'Duỗi thẳng gối; cơ thẳng đùi còn nâng đùi lên. Chúng giữ bạn trong Cái ghế và Chiến binh.' },
    feel: { en: 'Burning in Chair Pose; stretched in Hero and Reclined Hero and the back leg of a lunge.', vi: 'Nóng rát trong Cái ghế; được giãn trong Anh hùng, Anh hùng nằm và chân sau của tư thế chùng chân.' },
    cues: [
      { style: 'vinyasa', en: 'Lift your kneecaps to engage the front of your thighs.', vi: 'Nâng xương bánh chè để kích hoạt mặt trước đùi.' },
      { style: 'ashtanga', en: 'In Chair, sit back into your heels and feel your thighs working.', vi: 'Trong Cái ghế, ngồi lùi về gót chân và cảm nhận đùi đang làm việc.' },
      { style: 'yin', en: 'In Saddle, let the front of your thighs lengthen; come up if the knees complain.', vi: 'Trong tư thế Yên ngựa, để mặt trước đùi dài ra; ngồi dậy nếu gối khó chịu.' },
      { style: 'vinyasa', en: 'Press through your front foot and feel the front of your thigh working.', vi: 'Ấn qua bàn chân trước và cảm nhận mặt trước đùi đang làm việc.' },
    ],
    works: ['chair-pose', 'warrior-1', 'warrior-2', 'downward-dog', 'standing-forward-fold'], stretches: ['hero-pose', 'saddle', 'low-lunge', 'dancer-pose', 'camel-pose'],
    wordTrap: 'Trọng âm đầu “KWOD”; nhớ cụm cuối “ps”. “Quads” là cách nói ngắn; “the front of your thighs” dễ hiểu nhất.',
    near: ['sartorius', 'tensor-fasciae-latae', 'patella'], under: [],
  },
  {
    id: 'hamstrings', en: 'hamstrings', plain: 'the back of your thighs',
    vi: 'nhóm cơ đùi sau (cơ gân kheo)', viPlain: 'mặt sau đùi', say: 'HAM-strings', traps: ['cluster-str', 'final-ngz'],
    region: 'thigh', view: ['back'], deep: false,
    latin: 'biceps femoris, semitendinosus, semimembranosus',
    does: { en: 'Bend the knee and pull the hip back; the muscles every forward fold stretches.', vi: 'Gập gối và kéo hông về sau; nhóm cơ mà mọi tư thế gập người đều kéo giãn.' },
    feel: { en: 'The pull behind the thigh in Forward Fold and Downward Dog; working in Bridge and Locust.', vi: 'Cảm giác kéo phía sau đùi trong Gập người và Chó úp mặt; làm việc trong Cây cầu và Châu chấu.' },
    cues: [
      { style: 'vinyasa', en: 'Bend your knees as much as you need to keep your back long.', vi: 'Chùng gối bao nhiêu tuỳ cần để giữ lưng dài.' },
      { style: 'ashtanga', en: 'Lift your sitting bones toward the ceiling in Downward Dog.', vi: 'Nâng xương ngồi lên hướng trần nhà trong Chó úp mặt.' },
      { style: 'yin', en: 'In Caterpillar, let your back round and the backs of your legs soften.', vi: 'Trong Sâu bướm, để lưng cong tròn và mặt sau chân mềm ra.' },
      { style: 'vinyasa', en: 'Fold from your hips, not from your waist.', vi: 'Gập từ hông, không phải từ eo.' },
    ],
    works: ['bridge-pose', 'locust-pose', 'warrior-3'], stretches: ['standing-forward-fold', 'downward-dog', 'caterpillar', 'seated-forward-fold', 'half-splits'],
    wordTrap: 'Cụm “str” liền và đuôi “ngz”: “HAM-strings”, không phải “ham-sờ-trin”. Luôn số nhiều.',
    near: ['gluteus-maximus', 'hip-adductors', 'calves'], under: [],
  },
  {
    id: 'it-band', en: 'IT band', latin: 'iliotibial band', plain: 'the thick band down the outside of your thigh',
    vi: 'dải chậu chày', viPlain: 'dải gân ngoài đùi', say: 'EYE-TEE band', traps: ['final-nd'],
    region: 'thigh', view: ['front', 'back'], deep: false,
    does: { en: 'A long strip of tendon, not a muscle; it steadies the outer knee and tightens when the TFL and glutes grip.', vi: 'Một dải gân dài, không phải cơ; giữ vững mặt ngoài gối và căng lên khi cơ TFL và cơ mông gồng.' },
    feel: { en: 'The outer thigh and knee in Shoelace and crossed-leg twists.', vi: 'Mặt ngoài đùi và gối trong Dây giày và các tư thế vặn bắt chéo chân.' },
    cues: [
      { style: 'yin', en: 'Cross your knees and let the outer thighs release.', vi: 'Bắt chéo hai gối và để mặt ngoài đùi buông ra.' },
      { style: 'vinyasa', en: 'In Eagle, hug your thighs together and feel the outer hips.', vi: 'Trong Đại bàng, ép hai đùi vào nhau và cảm nhận hông ngoài.' },
    ],
    works: [], stretches: ['shoelace', 'eagle-pose', 'supine-twist'],
    wordTrap: 'Nói hai chữ cái “I-T” rồi “band”; đừng đọc “it” như từ “it”.',
    near: ['tensor-fasciae-latae', 'quadriceps', 'hamstrings'], under: [],
  },
  {
    id: 'tibialis-anterior', en: 'tibialis anterior', plain: 'the front of your shin',
    vi: 'cơ chày trước', viPlain: 'cơ trước ống chân', say: 'tib-ee-AY-lis an-TEER-ee-or', traps: ['stress'],
    region: 'lower-leg', view: ['front'], deep: false,
    does: { en: 'Pulls the foot and toes up toward the shin; works when you flex the feet.', vi: 'Kéo bàn chân và ngón chân lên về phía ống chân; làm việc khi bạn gập bàn chân.' },
    feel: { en: 'The front of the shin when you flex your feet strongly in Staff Pose; stretched in Hero when the feet point back.', vi: 'Phía trước ống chân khi bạn gập mạnh bàn chân trong tư thế Cây gậy; được giãn trong Anh hùng khi bàn chân duỗi về sau.' },
    cues: [
      { style: 'ashtanga', en: 'Flex your feet and pull your toes toward you.', vi: 'Gập bàn chân và kéo ngón chân về phía bạn.' },
      { style: 'yin', en: 'In Toe Squat and Hero, let the fronts of the shins and ankles stretch slowly.', vi: 'Trong Ngồi trên ngón chân và Anh hùng, để phía trước ống chân và cổ chân giãn từ từ.' },
    ],
    works: ['staff-pose', 'boat-pose'], stretches: ['hero-pose', 'saddle', 'ankle-stretch'],
    wordTrap: 'Với học viên: “your shins”. Chú ý từ “shin” khác “chin” (cằm): âm “sh” đầu.',
    near: ['quadriceps', 'calves', 'tibia'], under: [],
  },
  {
    id: 'calves', en: 'calves', latin: 'gastrocnemius + soleus', plain: 'the back of your lower legs',
    vi: 'cơ bắp chân (cơ bụng chân và cơ dép)', viPlain: 'bắp chân', say: 'KAHVZ', traps: ['final-vz', 'long-a'],
    region: 'lower-leg', view: ['back'], deep: false,
    does: { en: 'Point the foot and lift the heel; the soleus works even with the knee bent.', vi: 'Duỗi bàn chân và nhấc gót; cơ dép làm việc cả khi gối gập.' },
    feel: { en: 'The stretch down the back of the lower leg in Downward Dog; working when you rise onto the toes.', vi: 'Cảm giác giãn dọc mặt sau cẳng chân trong Chó úp mặt; làm việc khi bạn kiễng chân.' },
    cues: [
      { style: 'vinyasa', en: 'Reach your heels toward the floor; they don’t have to touch.', vi: 'Hướng gót chân xuống sàn; không nhất thiết phải chạm.' },
      { style: 'vinyasa', en: 'Pedal your feet to wake up your calves.', vi: 'Đạp luân phiên hai bàn chân để làm ấm bắp chân.' },
      { style: 'yin', en: 'In Squat, let your heels sink; use a blanket under them if they lift.', vi: 'Trong tư thế Ngồi xổm, để gót chân chìm xuống; kê chăn dưới gót nếu gót nhấc lên.' },
    ],
    works: ['tiptoe-balance', 'chair-pose'], stretches: ['downward-dog', 'squat', 'half-splits', 'malasana'],
    wordTrap: 'Số ít “calf” (KAHF), số nhiều “calves” (KAHVZ) với âm “v”. Nguyên âm dài.',
    near: ['hamstrings', 'achilles-tendon', 'tibialis-posterior'], under: ['tibialis-posterior'],
  },
  {
    id: 'tibialis-posterior', en: 'tibialis posterior', plain: 'the deep muscle that holds up your arch',
    vi: 'cơ chày sau', viPlain: 'cơ sâu nâng vòm bàn chân', say: 'tib-ee-AY-lis pos-TEER-ee-or', traps: ['stress'],
    region: 'lower-leg', view: ['back'], deep: true,
    does: { en: 'Supports the inner arch of the foot and turns the sole inward.', vi: 'Nâng đỡ vòm trong bàn chân và xoay lòng bàn chân vào trong.' },
    feel: { en: 'The lift of the inner arch when you press the big-toe mound down and draw the arch up.', vi: 'Cảm giác nâng vòm trong khi bạn ấn gốc ngón cái xuống và kéo vòm lên.' },
    cues: [
      { style: 'vinyasa', en: 'Lift your inner arches and press the base of your big toes down.', vi: 'Nâng vòm trong bàn chân và ấn gốc ngón chân cái xuống.' },
    ],
    works: ['mountain-pose', 'tree-pose', 'all-standing-poses'], stretches: [],
    wordTrap: 'Không cần nói trong lớp; “lift your arches” là đủ.',
    near: ['calves', 'arch'], under: [],
  },
  {
    id: 'fibularis-longus', en: 'fibularis longus', latin: 'peroneus longus', plain: 'the outside of your lower leg',
    vi: 'cơ mác dài', viPlain: 'cơ ngoài cẳng chân', say: 'fib-yoo-LAIR-is LONG-gus', traps: ['stress'],
    region: 'lower-leg', view: ['front', 'back'], deep: false,
    does: { en: 'Turns the sole outward and steadies the ankle; works hard in one-legged balances.', vi: 'Xoay lòng bàn chân ra ngoài và giữ vững cổ chân; làm việc nhiều trong các tư thế thăng bằng một chân.' },
    feel: { en: 'The outer shin flickering as the ankle corrects itself in Tree Pose.', vi: 'Mặt ngoài cẳng chân rung nhẹ khi cổ chân tự điều chỉnh trong Cái cây.' },
    cues: [{ style: 'vinyasa', en: 'Spread your toes and feel the four corners of your foot.', vi: 'Xoè các ngón chân và cảm nhận bốn góc bàn chân.' }],
    works: ['tree-pose', 'warrior-3', 'half-moon'], stretches: ['hero-pose'],
    wordTrap: 'Không cần tên này; “the outside of your lower leg”.',
    near: ['calves', 'tibialis-anterior'], under: [],
  },
  {
    id: 'achilles-tendon', en: 'Achilles tendon', plain: 'the cord above your heel',
    vi: 'gân gót (gân Achilles)', viPlain: 'gân sau gót chân', say: 'uh-KIL-eez TEN-dun', traps: ['stress', 'final-z'],
    region: 'lower-leg', view: ['back'], deep: false,
    does: { en: 'The thick tendon joining the calf to the heel; it lengthens as the heel drops in Downward Dog.', vi: 'Gân dày nối bắp chân với gót; dài ra khi gót hạ xuống trong Chó úp mặt.' },
    feel: { en: 'The firm cord just above the heel; tender if the calves are tight.', vi: 'Sợi gân chắc ngay trên gót; nhạy cảm nếu bắp chân bị căng.' },
    cues: [{ style: 'vinyasa', en: 'Let your heels sink slowly; never bounce.', vi: 'Để gót chân hạ xuống từ từ; không bao giờ nhún nảy.' }],
    works: [], stretches: ['downward-dog', 'squat'],
    wordTrap: '“Achilles” đọc “uh-KIL-eez”, ba âm tiết, trọng âm giữa.',
    near: ['calves', 'calcaneus'], under: [],
  },
  {
    id: 'plantar-fascia', en: 'plantar fascia', plain: 'the sole of your foot',
    vi: 'cân gan chân', viPlain: 'gan bàn chân', say: 'PLAN-tar FASH-uh', traps: ['cluster-pl', 'stress'],
    region: 'foot', view: ['back'], deep: false,
    does: { en: 'The strong sheet under the foot that keeps the arch; it stretches in Toe Squat.', vi: 'Lớp màng chắc dưới bàn chân giữ vòm chân; được giãn trong tư thế Ngồi trên ngón chân.' },
    feel: { en: 'The sole of the foot, intensely, in Toe Squat; rolling a ball underfoot.', vi: 'Gan bàn chân, rất rõ, trong Ngồi trên ngón chân; khi lăn bóng dưới chân.' },
    cues: [
      { style: 'yin', en: 'Tuck your toes under and sit back on your heels. Stay with the breath.', vi: 'Bấm các ngón chân xuống và ngồi lùi lên gót. Ở lại cùng hơi thở.' },
      { style: 'vinyasa', en: 'Spread your toes and press evenly through the sole of your foot.', vi: 'Xoè các ngón chân và ấn đều qua gan bàn chân.' },
    ],
    works: ['mountain-pose'], stretches: ['toe-squat', 'downward-dog'],
    wordTrap: '“Fascia” đọc “FASH-uh”. “The sole of your foot” dễ hiểu hơn.',
    near: ['calcaneus', 'arch'], under: [],
  },
]
