export const forearmPlank = {
  id: 'forearm-plank',
  styles: ['vinyasa'],
  family: 'core',
  level: 'moderate',
  en: 'Forearm Plank',
  aka: ['Dolphin Plank'],
  sa: null,
  say: null,
  vi: 'Tấm ván cẳng tay',
  breath: {
    en: 'Breathe steadily through the whole hold. On each exhale, draw your belly in a little more.',
    vi: 'Thở đều trong suốt thời gian giữ. Mỗi hơi thở ra, thu bụng vào thêm một chút.',
  },
  cues: [
    { id: 'forearm-plank__cue-1', kind: 'transition', en: 'From all fours, lower onto your forearms, elbows under your shoulders.', vi: 'Từ tư thế bốn điểm, hạ xuống chống cẳng tay, khuỷu tay ngay dưới vai.' },
    { id: 'forearm-plank__cue-2', kind: 'transition', en: 'Step your feet back one at a time and lift your knees.', vi: 'Bước từng chân ra sau và nhấc hai gối lên.' },
    { id: 'forearm-plank__cue-3', kind: 'alignment', en: 'Press your forearms down and lift the space between your shoulder blades.', vi: 'Ấn cẳng tay xuống và nâng vùng giữa hai bả vai lên.' },
    { id: 'forearm-plank__cue-4', kind: 'alignment', en: 'Draw your belly in and lengthen your tailbone toward your heels.', vi: 'Thu bụng vào và kéo dài xương cụt về phía gót chân.' },
    { id: 'forearm-plank__cue-5', kind: 'alignment', en: 'Keep your hips level with your shoulders.', vi: 'Giữ hông ngang bằng với vai.' },
    { id: 'forearm-plank__cue-6', kind: 'soften', en: 'Keep your neck long, and let your jaw soften.', vi: 'Giữ cổ dài, và để hàm thả lỏng.' },
    { id: 'forearm-plank__cue-7', kind: 'breath', en: 'Stay for five breaths, or for as long as your breath stays smooth.', vi: 'Giữ năm nhịp thở, hoặc lâu bao nhiêu tuỳ hơi thở vẫn còn êm.' },
    { id: 'forearm-plank__cue-8', kind: 'safety', en: 'If your lower back starts to ache, lower your knees down.', vi: 'Nếu lưng dưới bắt đầu mỏi, hạ hai gối xuống.' },
    { id: 'forearm-plank__cue-9', kind: 'transition', en: 'Lower your knees, and rest back in Child’s Pose.', vi: 'Hạ gối xuống, và lùi về nghỉ ở tư thế Em bé.' },
  ],
  modifications: [
    { id: 'forearm-plank__mod-1', en: 'Keep your knees on the floor, with your hips in line with your shoulders.', vi: 'Giữ hai gối trên sàn, hông thẳng hàng với vai.', props: [] },
    { id: 'forearm-plank__mod-2', en: 'Hold a block between your hands to keep your forearms parallel.', vi: 'Kẹp một viên gạch giữa hai bàn tay để giữ hai cẳng tay song song.', props: ['block'] },
    { id: 'forearm-plank__mod-3', en: 'Rest your elbows on a folded blanket if they feel sore.', vi: 'Kê khuỷu tay lên chăn gấp nếu khuỷu tay thấy đau.', props: ['blanket'] },
  ],
  safety: [
    { id: 'forearm-plank__safe-1', en: 'If your shoulders hurt, check that your elbows are right under them.', vi: 'Nếu vai đau, kiểm tra xem khuỷu tay đã nằm ngay dưới vai chưa.' },
    { id: 'forearm-plank__safe-2', en: 'Forearm Plank is often kinder to sore wrists than Plank on your hands.', vi: 'Tấm ván cẳng tay thường nhẹ nhàng hơn cho cổ tay đau so với Tấm ván chống bàn tay.' },
    { id: 'forearm-plank__safe-3', en: 'In pregnancy, keep the hold short, or keep your knees down.', vi: 'Khi mang thai, giữ ngắn thôi, hoặc để hai gối trên sàn.' },
  ],
  muscles: {
    working: ['transversus-abdominis', 'rectus-abdominis', 'serratus-anterior', 'deltoids', 'quadriceps'],
    lengthening: [],
  },
  joints: ['elbow', 'shoulder-joint', 'lumbar-spine'],
  transitionsTo: ['dolphin-pose', 'child-pose', 'side-plank'],
  counterPoses: ['child-pose'],
  figure: 'forearm-plank',
}
