export const locustPose = {
  id: 'locust-pose',
  styles: ['vinyasa'],
  family: 'backbend',
  level: 'moderate',
  en: 'Locust Pose',
  sa: 'Śalabhāsana',
  say: 'shah-lah-BAH-sah-nah',
  vi: 'Châu chấu',
  breath: {
    en: 'Inhale to lift. Breathe steadily for three to five breaths. Exhale to lower down and rest.',
    vi: 'Hít vào để nâng lên. Thở đều ba đến năm nhịp. Thở ra để hạ xuống và nghỉ.',
  },
  cues: [
    { id: 'locust-pose__cue-1', kind: 'transition', en: 'Lie on your belly, arms by your sides, palms facing down.', vi: 'Nằm sấp, hai tay dọc theo người, lòng bàn tay úp xuống.' },
    { id: 'locust-pose__cue-2', kind: 'alignment', en: 'Press the tops of your feet down, and reach your legs long.', vi: 'Ấn mu bàn chân xuống, và duỗi dài hai chân.' },
    { id: 'locust-pose__cue-3', kind: 'alignment', en: 'Inhale, lift your chest, your arms and your legs.', vi: 'Hít vào, nâng ngực, hai tay và hai chân lên.' },
    { id: 'locust-pose__cue-4', kind: 'alignment', en: 'Reach back through your fingertips, and draw your shoulder blades together.', vi: 'Vươn ra sau qua đầu ngón tay, và khép hai bả vai lại.' },
    { id: 'locust-pose__cue-5', kind: 'alignment', en: 'Keep your legs hip-width apart, and lift from your inner thighs.', vi: 'Giữ hai chân rộng bằng hông, và nâng từ mặt trong đùi.' },
    { id: 'locust-pose__cue-6', kind: 'soften', en: 'Keep your neck long, and soften your jaw.', vi: 'Giữ cổ dài, và thả lỏng hàm.' },
    { id: 'locust-pose__cue-7', kind: 'breath', en: 'Stay for three to five breaths.', vi: 'Giữ ba đến năm nhịp thở.' },
    { id: 'locust-pose__cue-8', kind: 'safety', en: 'If your lower back pinches, keep your legs down and lift only your chest.', vi: 'Nếu lưng dưới bị chèn, giữ chân trên sàn và chỉ nâng ngực.' },
    { id: 'locust-pose__cue-9', kind: 'transition', en: 'Exhale, lower down, and rest with your head turned to one side.', vi: 'Thở ra, hạ xuống, và nghỉ với đầu quay sang một bên.' },
  ],
  modifications: [
    { id: 'locust-pose__mod-1', en: 'Lift your chest only, or your legs only.', vi: 'Chỉ nâng ngực, hoặc chỉ nâng chân.', props: [] },
    { id: 'locust-pose__mod-2', en: 'Lift one leg at a time, keeping both hips on the floor.', vi: 'Nâng từng chân một, giữ hai bên hông trên sàn.', props: [] },
    { id: 'locust-pose__mod-3', en: 'Place a folded blanket under your hips for padding.', vi: 'Kê chăn gấp dưới hông cho êm.', props: ['blanket'] },
  ],
  safety: [
    { id: 'locust-pose__safe-1', en: 'If you have a lower back injury, keep the lift small, and come down at any pinching.', vi: 'Nếu bạn có chấn thương lưng dưới, nâng thấp thôi, và hạ xuống khi thấy bị chèn.' },
    { id: 'locust-pose__safe-2', en: 'In pregnancy, skip lying on your belly. On all fours, lift one arm and the opposite leg instead.', vi: 'Khi mang thai, tránh nằm sấp. Thay vào đó, ở tư thế bốn điểm, nâng một tay và chân đối diện.' },
  ],
  muscles: {
    working: ['erector-spinae', 'gluteus-maximus', 'hamstrings', 'rhomboids'],
    lengthening: ['rectus-abdominis', 'pectoralis-major'],
  },
  joints: ['lumbar-spine', 'thoracic-spine'],
  transitionsTo: ['bow-pose', 'child-pose', 'downward-dog'],
  counterPoses: ['child-pose'],
  figure: 'locust-pose',
}
