export const plank = {
  id: 'plank',
  styles: ['vinyasa'],
  family: 'core',
  level: 'moderate',
  en: 'Plank Pose',
  aka: ['High Plank'],
  sa: 'Phalakāsana',
  say: 'pah-lah-KAH-sah-nah',
  vi: 'Tấm ván',
  breath: {
    en: 'Inhale to shift forward into Plank. Breathe evenly while you hold. Exhale to lower down, or to lift back to Downward Dog.',
    vi: 'Hít vào, dịch người về trước vào Tấm ván. Thở đều trong khi giữ. Thở ra để hạ người xuống, hoặc nâng hông về Chó úp mặt.',
  },
  cues: [
    { id: 'plank__cue-1', kind: 'transition', en: 'From Downward Dog, inhale and shift forward, shoulders over your wrists.', vi: 'Từ Chó úp mặt, hít vào và dịch người về trước, vai thẳng trên cổ tay.' },
    { id: 'plank__cue-2', kind: 'alignment', en: 'Spread your fingers wide and press the floor away.', vi: 'Xoè rộng các ngón tay và đẩy sàn ra xa.' },
    { id: 'plank__cue-3', kind: 'alignment', en: 'Draw your belly in and reach back through your heels.', vi: 'Thu bụng vào và đẩy gót chân ra sau.' },
    { id: 'plank__cue-4', kind: 'alignment', en: 'Make one long line from the crown of your head to your heels.', vi: 'Tạo một đường thẳng dài từ đỉnh đầu đến gót chân.' },
    { id: 'plank__cue-5', kind: 'alignment', en: 'Keep your neck long, and look at the floor just in front of your hands.', vi: 'Giữ cổ dài, và nhìn xuống sàn ngay phía trước hai bàn tay.' },
    { id: 'plank__cue-6', kind: 'soften', en: 'Let your shoulders stay wide, and soften your jaw.', vi: 'Giữ vai rộng, và thả lỏng hàm.' },
    { id: 'plank__cue-7', kind: 'breath', en: 'Stay for three to five breaths.', vi: 'Giữ ba đến năm nhịp thở.' },
    { id: 'plank__cue-8', kind: 'safety', en: 'If this is too much, lower your knees and keep that long line.', vi: 'Nếu quá sức, hạ hai gối xuống và vẫn giữ đường thẳng dài đó.' },
    { id: 'plank__cue-9', kind: 'transition', en: 'Exhale, lower halfway down to Chaturanga, or lift your hips back to Downward Dog.', vi: 'Thở ra, hạ người xuống một nửa vào Chaturanga, hoặc nâng hông về Chó úp mặt.' },
  ],
  modifications: [
    { id: 'plank__mod-1', en: 'Lower your knees to the floor, keeping your hips in line with your shoulders.', vi: 'Hạ hai gối xuống sàn, giữ hông thẳng hàng với vai.', props: [] },
    { id: 'plank__mod-2', en: 'Roll the edge of a blanket under the heels of your hands to ease your wrists.', vi: 'Cuộn mép chăn kê dưới gốc bàn tay để đỡ cho cổ tay.', props: ['blanket'] },
    { id: 'plank__mod-3', en: 'Practise Plank standing up, with your hands on a wall.', vi: 'Tập Tấm ván ở tư thế đứng, hai tay chống vào tường.', props: ['wall'] },
  ],
  safety: [
    { id: 'plank__safe-1', en: 'If your wrists hurt, press into your knuckles and fingertips, or come down onto your forearms.', vi: 'Nếu cổ tay đau, dồn lực vào các khớp ngón tay và đầu ngón tay, hoặc hạ xuống chống cẳng tay.' },
    { id: 'plank__safe-2', en: 'If your lower back sags or aches, lower your knees and draw your belly in.', vi: 'Nếu lưng dưới bị võng hoặc mỏi, hạ gối xuống và thu bụng vào.' },
    { id: 'plank__safe-3', en: 'In pregnancy, keep the hold short, and take your knees down whenever you need to.', vi: 'Khi mang thai, giữ ngắn thôi, và hạ gối xuống bất cứ khi nào bạn cần.' },
  ],
  muscles: {
    working: ['transversus-abdominis', 'rectus-abdominis', 'serratus-anterior', 'triceps-brachii', 'quadriceps'],
    lengthening: [],
  },
  joints: ['wrist', 'elbow', 'shoulder-joint'],
  transitionsTo: ['chaturanga', 'downward-dog', 'side-plank'],
  counterPoses: ['child-pose'],
  figure: 'plank',
}
