export const warrior2 = {
  id: 'warrior-2',
  styles: ['vinyasa', 'ashtanga'],
  family: 'standing',
  en: 'Warrior II',
  sa: 'Vīrabhadrāsana II',
  say: 'vee-rah-bah-DRAH-sah-nah TWO',
  vi: 'Chiến binh II',
  ashtanga: { series: 'primary', section: 'standing', note: { en: 'Comes after Warrior I in the standing sequence; five breaths each side.', vi: 'Đứng sau Chiến binh I trong chuỗi đứng; năm nhịp thở mỗi bên.' } },
  breath: {
    en: 'Exhale into the pose. Stay for five slow breaths. Inhale to straighten the front leg and change sides.',
    vi: 'Thở ra khi vào tư thế. Giữ năm nhịp thở chậm. Hít vào để duỗi thẳng chân trước và đổi bên.',
  },
  cues: [
    { id: 'warrior-2__cue-1', kind: 'transition', en: 'Step your feet wide apart.', vi: 'Bước hai chân rộng ra.' },
    { id: 'warrior-2__cue-2', kind: 'alignment', en: 'Turn your right toes out, and your left toes in slightly.', vi: 'Xoay mũi chân phải ra ngoài, mũi chân trái hơi xoay vào trong.' },
    { id: 'warrior-2__cue-3', kind: 'alignment', en: 'Bend your front knee so it stacks over your ankle.', vi: 'Gập gối trước sao cho gối thẳng trên cổ chân.' },
    { id: 'warrior-2__cue-4', kind: 'alignment', en: 'Press into the outer edge of your back foot.', vi: 'Ấn vào cạnh ngoài của bàn chân sau.' },
    { id: 'warrior-2__cue-5', kind: 'alignment', en: 'Reach your arms out wide, parallel to the floor.', vi: 'Vươn hai tay sang hai bên, song song với sàn.' },
    { id: 'warrior-2__cue-6', kind: 'soften', en: 'Relax your shoulders away from your ears.', vi: 'Thả lỏng vai, hạ vai xa khỏi tai.' },
    { id: 'warrior-2__cue-7', kind: 'alignment', en: 'Gaze softly over your front fingertips.', vi: 'Nhìn nhẹ nhàng qua đầu ngón tay trước.' },
    { id: 'warrior-2__cue-8', kind: 'breath', en: 'Stay here for five breaths.', vi: 'Giữ ở đây trong năm nhịp thở.' },
  ],
  modifications: [
    { id: 'warrior-2__mod-1', en: 'Shorten your stance if your front knee feels strained.', vi: 'Thu hẹp khoảng cách hai chân nếu gối trước thấy căng.', props: [] },
    { id: 'warrior-2__mod-2', en: 'Rest your hands on your hips to give your shoulders a break.', vi: 'Đặt hai tay lên hông để vai được nghỉ.', props: [] },
    { id: 'warrior-2__mod-3', en: 'You can sit on the edge of a chair with your front leg bent.', vi: 'Bạn có thể ngồi ở mép ghế với chân trước gập.', props: ['chair'] },
  ],
  safety: [
    { id: 'warrior-2__safe-1', en: 'Keep your front knee tracking over your second toe. Don’t let it fall inward.', vi: 'Giữ gối trước thẳng hướng với ngón chân thứ hai. Đừng để gối đổ vào trong.' },
    { id: 'warrior-2__safe-2', en: 'If you have a knee injury, don’t bend as deeply, and come out sooner.', vi: 'Nếu bạn có chấn thương gối, đừng gập quá sâu và thoát thế sớm hơn.' },
  ],
  muscles: {
    working: ['quadriceps', 'gluteus-medius', 'deltoids', 'rectus-abdominis', 'transversus-abdominis'],
    lengthening: ['hip-adductors', 'iliopsoas', 'pectoralis-major'],
  },
  joints: ['knee', 'ankle', 'hip-joint', 'shoulder-joint'],
  transitionsTo: ['reverse-warrior', 'extended-side-angle', 'triangle'],
  figure: 'warrior-2',
}
