export const caterpillar = {
  id: 'caterpillar',
  styles: ['yin'],
  family: 'forward-fold',
  level: 'gentle',
  en: 'Caterpillar',
  sa: null,
  saNote: { en: 'Caterpillar is the Yin name. The yang pose is Seated Forward Fold, Paścimottānāsana, folded from the hips with a long spine.', vi: 'Sâu bướm là tên Yin. Tư thế yang là Ngồi gập người về trước, Paścimottānāsana, gập từ hông với lưng dài.' },
  vi: 'Sâu bướm',
  yin: {
    holdMinutes: 4,
    target: ['spine', 'hamstrings'],
    counter: 'savasana',
    note: {
      en: 'Three to five minutes. The aim is the lower back and the backs of the legs, with the spine allowed to round. Bend the knees freely; nothing should pull behind the knees or tingle down the legs.',
      vi: 'Ba đến năm phút. Mục tiêu là lưng dưới và mặt sau chân, cột sống được phép cong tròn. Cứ chùng gối thoải mái; phía sau gối không được bị kéo căng và chân không được tê dọc xuống.',
    },
  },
  breath: {
    en: 'Breathe into your back. Let each exhale round you a little further.',
    vi: 'Thở vào lưng. Để mỗi hơi thở ra giúp bạn cong tròn thêm một chút.',
  },
  cues: [
    { id: 'caterpillar__cue-1', kind: 'transition', en: 'Sit on a folded blanket, with your legs straight out in front of you.', vi: 'Ngồi trên chăn gấp, hai chân duỗi thẳng phía trước.' },
    { id: 'caterpillar__cue-2', kind: 'alignment', en: 'Roll a blanket under your knees, or lay a bolster along your legs.', vi: 'Cuộn chăn đặt dưới đầu gối, hoặc đặt gối ôm dọc trên chân.' },
    { id: 'caterpillar__cue-3', kind: 'transition', en: 'Fold forward, and let your back round like a caterpillar.', vi: 'Gập người về trước, để lưng cong tròn như một con sâu bướm.' },
    { id: 'caterpillar__cue-4', kind: 'soften', en: 'Find your edge, and let your head hang.', vi: 'Tìm ngưỡng của bạn, và để đầu buông xuống.' },
    { id: 'caterpillar__cue-5', kind: 'soften', en: 'Let the backs of your legs soften. Your feet can relax.', vi: 'Để mặt sau chân mềm ra. Bàn chân có thể thả lỏng.' },
    { id: 'caterpillar__cue-6', kind: 'breath', en: 'Halfway. There’s nowhere to get to. Just stay with the breath.', vi: 'Được một nửa rồi. Không cần phải đến đâu cả. Chỉ cần ở lại với hơi thở.' },
    { id: 'caterpillar__cue-7', kind: 'safety', en: 'If you feel tingling down your leg, bend your knees and come up a little.', vi: 'Nếu thấy tê dọc chân, chùng gối và nâng người lên một chút.' },
    { id: 'caterpillar__cue-8', kind: 'transition', en: 'Slowly roll up, one vertebra at a time.', vi: 'Từ từ cuộn người lên, từng đốt sống một.' },
    { id: 'caterpillar__cue-9', kind: 'soften', en: 'Lie down on your back, and notice the rebound along your spine.', vi: 'Nằm ngửa, và cảm nhận dư âm dọc cột sống.' },
  ],
  modifications: [
    { id: 'caterpillar__mod-1', en: 'Rest your chest on a bolster lying along your legs.', vi: 'Tựa ngực lên gối ôm đặt dọc trên chân.', props: ['bolster'] },
    { id: 'caterpillar__mod-2', en: 'Bend your knees over a rolled blanket.', vi: 'Chùng gối trên một tấm chăn cuộn.', props: ['blanket'] },
    { id: 'caterpillar__mod-3', en: 'Rest your forehead on a block.', vi: 'Tựa trán lên một viên gạch.', props: ['block'] },
  ],
  safety: [
    { id: 'caterpillar__safe-1', en: 'Feel it along your back and the backs of your legs. Pain or tingling down your leg means bend your knees.', vi: 'Cảm giác nên ở dọc lưng và mặt sau chân. Đau hoặc tê dọc chân nghĩa là cần chùng gối.' },
    { id: 'caterpillar__safe-2', en: 'With a disc injury in the lower back, skip the rounded fold, and take Legs Up the Wall instead.', vi: 'Nếu bị thoát vị đĩa đệm ở lưng dưới, bỏ qua tư thế gập cong lưng, thay bằng Gác chân lên tường.' },
    { id: 'caterpillar__safe-3', en: 'In pregnancy, open your legs a little to make room for your belly.', vi: 'Khi mang thai, mở hai chân rộng ra một chút để chừa chỗ cho bụng.' },
  ],
  muscles: {
    working: [],
    lengthening: ['hamstrings', 'erector-spinae'],
  },
  joints: ['lumbar-spine', 'hip-joint'],
  transitionsTo: ['savasana', 'reclined-twist'],
  figure: 'caterpillar',
}
